(in-package :cl-meld)

(deftuple setcolor (:type-addr :type-int :type-int :type-int) :action :linear)
(deftuple setedgelabel (:type-addr :type-addr :type-string) :action :linear)
(deftuple write-string (:type-addr :type-string) :action :linear)
(deftuple setColor2 (:type-addr :type-int) :action)
(deftuple stop-program (:type-addr) :action :linear)
(deftuple set-priority (:type-addr :type-float) :action :linear)
(deftuple add-priority (:type-addr :type-float) :action :linear)
(deftuple schedule-next (:type-addr) :action :linear)                                                 
(deftuple set-default-priority (:type-addr :type-float) :action :linear)
(deftuple set-moving (:type-addr) :action :linear)
(deftuple set-static (:type-addr) :action :linear)
(deftuple set-affinity (:type-addr :type-addr) :action :linear)
(deftuple set-cpu (:type-addr :type-int) :action :linear)
(deftuple remove-priority (:type-addr) :action :linear)
(deftuple moveTo (:type-addr :type-int :type-int :type-int) :action)
