
TARGET = /usr/local

install:
	mkdir -p $(TARGET)/bin
	install --mode=555 meld-compile-file $(TARGET)/bin/
	install --mode=555 meld-compile-directory $(TARGET)/bin/
	install --mode=555 meld-compile-from-directory $(TARGET)/bin/
