
/**
 * @file myAppMotionSCCode.hpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2023-02-10                                                                     
 **/	

#ifndef myAppMotionSCCode_H_
#define myAppMotionSCCode_H_

#include "robots/slidingCubes/slidingCubesSimulator.h"
#include "robots/slidingCubes/slidingCubesWorld.h"
#include "robots/slidingCubes/slidingCubesBlockCode.h"
static const int ELECTFIRST_MSG_ID = 1001;


using namespace SlidingCubes;

class MyAppMotionSCCode : public SlidingCubesBlockCode {
private:
	SlidingCubesBlock *module = nullptr;
	bool isLeader=false;

public :
	MyAppMotionSCCode(SlidingCubesBlock *host);
	~MyAppMotionSCCode() {};

/**
  * This function is called on startup of the blockCode, it can be used to perform initial
  *  configuration of the host or this instance of the program.
  * @note this can be thought of as the main function of the module
  */
    void startup() override;

/**
  * @brief Message handler for the message 'electFirst'
  * @param _msg Pointer to the message received by the module, requires casting
  * @param sender Connector of the module that has received the message and that is connected to the sender
  */
   void myElectFirstFunc(std::shared_ptr<Message>_msg,P2PNetworkInterface *sender);

/**
  * @brief Provides the user with a pointer to the configuration file parser, which can be used to read additional user information from each block config. Has to be overridden in the child class.
  * @param config : pointer to the TiXmlElement representing the block configuration file, all information related to concerned block have already been parsed
  *
  */
    void parseUserBlockElements(TiXmlElement *config) override;

   /**
    * @brief Provides the user with a pointer to the configuration file parser, which can be used to read additional user information from it.
    * @param config : pointer to the TiXmlDocument representing the configuration file, all information related to VisibleSim's core have already been parsed
    *
    * Called from BuildingBlock constructor, only once.
    */
    void parseUserElements(TiXmlDocument *config) override;

    /**
  * @brief Callback function executed whenever the module finishes a motion
  */
    void onMotionEnd() override;

    bool tryToMove();
    void onGlDraw() override;
/*****************************************************************************/
/** needed to associate code to module                                      **/
	static BlockCode *buildNewBlockCode(BuildingBlock *host) {
	    return(new MyAppMotionSCCode((SlidingCubesBlock*)host));
	}
/*****************************************************************************/
};

#endif /* myAppMotionSCCode_H_ */