
/**
 * @file myCSGappBBCode.hpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2023-05-11                                                                     
 **/	

#ifndef myCSGappBBCode_H_
#define myCSGappBBCode_H_

#include "robots/blinkyBlocks/blinkyBlocksSimulator.h"
#include "robots/blinkyBlocks/blinkyBlocksWorld.h"
#include "robots/blinkyBlocks/blinkyBlocksBlockCode.h"
static const int BROADCAST_MSG_ID = 1001;
static const int BACK_MSG_ID = 1002;

using namespace BlinkyBlocks;

class MyCSGappBBCode : public BlinkyBlocksBlockCode {
private:
    BlinkyBlocksBlock *module = nullptr;
    uint16_t distance=0;
    uint16_t currentRound=0;
    int nbWaitedAnswers=0;
    P2PNetworkInterface *parent= nullptr;
    uint16_t maxDistance=0;
public :
	MyCSGappBBCode(BlinkyBlocksBlock *host);
	~MyCSGappBBCode() {};

/**
  * This function is called on startup of the blockCode, it can be used to perform initial
  *  configuration of the host or this instance of the program.
  * @note this can be thought of as the main function of the module
  */
    void startup() override;

    /**
  * @brief Message handler for the message 'broadcast'
  * @param _msg Pointer to the message received by the module, requires casting
  * @param sender Connector of the module that has received the message and that is connected to the sender
  */
    void myBroadcastFunc(std::shared_ptr<Message>_msg,P2PNetworkInterface *sender);

/**
  * @brief Message handler for the message 'back'
  * @param _msg Pointer to the message received by the module, requires casting
  * @param sender Connector of the module that has received the message and that is connected to the sender
  */
    void myBackFunc(std::shared_ptr<Message>_msg,P2PNetworkInterface *sender);


/*****************************************************************************/
/** needed to associate code to module                                      **/
	static BlockCode *buildNewBlockCode(BuildingBlock *host) {
	    return(new MyCSGappBBCode((BlinkyBlocksBlock*)host));
	}
/*****************************************************************************/
};

#endif /* myCSGappCode_H_ */