
/**
 * @file datomMotionsCode.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2024-06-16
 **/

#include "datomMotionsCode.hpp"

DatomMotionsCode::DatomMotionsCode(DatomsBlock *host):DatomsBlockCode(host),module(host) {
    // @warning Do not remove block below, as a blockcode with a NULL host might be created
    //  for command line parsing
    if (not host) return;

}

void DatomMotionsCode::startup() {
    console << "start " << getId() << "\n";

    currentPathStep=0;
    if (isLeader) { // At least one module must be "leader" in the config file
        setColor(module->nbPossibleMotions());
        /*auto lst=module->getAllMotions();
        for (auto &pos:lst) {
            OUTPUT << getId() << ":" << pos.first << " / " << (int)pos.second << endl;
            if (path.size()>currentPathStep && pos.first==path[currentPathStep]) {
                module->moveTo(pos.first);
                currentPathStep++;
            }
        }*/
        if (currentPathStep<path.size()) {
            module->moveTo(path[currentPathStep++]);
        }
    }

    //setColor(module->getNbNeighbors());
}

vector<string_view> split(string_view str, char delim) {
    vector<string_view> result;
    auto left = str.begin();
    for (auto it = left; it != str.end(); ++it)
    {
        if (*it == delim)
        {
            result.emplace_back(&*left, it - left);
            left = it + 1;
        }
    }
    if (left != str.end())
        result.emplace_back(&*left, str.end() - left);
    return result;
}

void DatomMotionsCode::parseUserBlockElements(TiXmlElement *config) {
    const char *attr = config->Attribute("leader");
    isLeader = (attr?Simulator::extractBoolFromString(attr):false);
    if (isLeader) {
        std::cout << getId() << " is leader!" << std::endl; // complete with your code
    }

    attr = config->Attribute("piston");
    if (attr) {
        if (strncmp(attr,"012A",4)==0) {
            module->setPiston(Piston012A);
        } else if (strncmp(attr,"0579",4)==0) {
            module->setPiston(Piston0579);
        } else if (strncmp(attr,"136B",4)==0) {
            module->setPiston(Piston136B);
        } else if (strncmp(attr,"2345",4)==0) {
            module->setPiston(Piston2345);
        } else if (strncmp(attr,"4678",4)==0) {
            module->setPiston(Piston4678);
        } else if (strncmp(attr,"89AB",4)==0) {
            module->setPiston(Piston89AB);
        }
    }

    attr = config->Attribute("path");
    if (attr) {
        string_view str(attr);
        auto tabPos= split(str,';');
        for (auto &p:tabPos) {
            if (p[0]=='{' && p[p.size()-1]=='}') p=p.substr(1,p.size()-2);
            auto tabCells=split(p,',');
            path.push_back(Cell3DPosition(stoi(string(tabCells[0])),stoi(string(tabCells[1])),stoi(string(tabCells[2]))));
        }
    }
}

void DatomMotionsCode::onMotionEnd() {
    // complete with your code
    console << " End of motion to " << module->position << "\n";
    if (currentPathStep<path.size()) {
        cout << "try to go to:" << path[currentPathStep] << "\n";
        module->moveTo(path[currentPathStep++]);
    }

}

void DatomMotionsCode::onUserKeyPressed(unsigned char c, int x, int y) {
    switch (c) {
        case 'a' : // update with your code
            std::cout << "key a" << endl;
            break;
        case 'd' : break;
    }
}
