
/**
 * @file datomMotionsCode.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2024-06-16                                                                     
 **/
 
#include "datomMotionsCode.hpp"

DatomMotionsCode::DatomMotionsCode(DatomsBlock *host):DatomsBlockCode(host),module(host) {
    // @warning Do not remove block below, as a blockcode with a NULL host might be created
    //  for command line parsing
    if (not host) return;

}

void DatomMotionsCode::startup() {
    console << "start " << getId() << "\n";

    if (isLeader) { // At least one module must be "leader" in the config file
        setColor(RED);
    }	
}

void DatomMotionsCode::parseUserBlockElements(TiXmlElement *config) {
    const char *attr = config->Attribute("leader");
    isLeader = (attr?Simulator::extractBoolFromString(attr):false);
    if (isLeader) {
        std::cout << getId() << " is leader!" << std::endl; // complete with your code
    }
}

void DatomMotionsCode::onMotionEnd() {
    // complete with your code
    console << " End of motion to " << module->position << "\n";
}

void DatomMotionsCode::onUserKeyPressed(unsigned char c, int x, int y) {
    switch (c) {
        case 'a' : // update with your code
            std::cout << "key a" << endl;
            break;
        case 'd' : break;
    }
}
