
/**
 * @file myBridgeAppCode.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2023-10-17
 **/

#include "myBridgeAppCode.hpp"
#include "robots/catoms3D/catoms3DMotionEngine.h"
#include "robots/catoms3D/catoms3DRotationEvents.h"

MyBridgeAppCode::MyBridgeAppCode(Catoms3DBlock *host):Catoms3DBlockCode(host),module(host) {
    // @warning Do not remove block below, as a blockcode with a NULL host might be created
    //  for command line parsing
    if (not host) return;

    // Registers a callback (myBroadcastFunc) to the message of type R
    addMessageEventFunc2(BROADCAST_MSG_ID,
                         std::bind(&MyBridgeAppCode::myBroadcastFunc,this,
                                   std::placeholders::_1, std::placeholders::_2));

    addMessageEventFunc2(BROADCAST2_MSG_ID,
                         std::bind(&MyBridgeAppCode::myBroadcastFunc2,this,
                                   std::placeholders::_1, std::placeholders::_2));

    // Registers a callback (myAcknowledgeFunc) to the message of type K
    addMessageEventFunc2(ACKNOWLEDGE_MSG_ID,
                         std::bind(&MyBridgeAppCode::myAcknowledgeFunc,this,
                                   std::placeholders::_1, std::placeholders::_2));

    addMessageEventFunc2(ACKNOWLEDGE2_MSG_ID,
                         std::bind(&MyBridgeAppCode::onMessageReceived,this,
                                   std::placeholders::_1, std::placeholders::_2));


}



/*
map<double, vector<Cell3DPosition>> nextPos {
        {1, {{1,0,0},{1,2,3},{1,3,3},{3,3,3},{4,3,3},{5,3,3},{6,3,4},{6,2,4}} },
        {54,{{1,0,0},{2,4,0}}}
};
*/


map<double, vector<Cell3DPosition>> nextPos {
        {1, {{1,0,0},{1,2,3},{2,3,2},{1,2,3},{2,2,2},{1,1,1},{2,1,1},{2,2,1}} },
        {2, {{1,0,0},{0,1,3},{0,1,2},{0,1,1},{1,1,2},{1,1,1},{2,1,1},{2,2,2}}},
        {3,{{1,0,0},{1,3,3},{1,2,3},{2,3,2}}},
        {4,{{1,0,0},{1,3,4},{1,2,3},{1,1,3},{2,1,2},{2,1,3},{3,2,2},{3,3,2}}},
        {5,{{1,0,0},{1,2,3},{1,1,3},{1,1,2},{1,1,1},{2,1,1},{3,2,2}}},
        {6,{{1,0,0},{0,2,3},{1,2,3},{2,2,3}}},
        {7,{{1,0,0},{0,2,3},{1,2,3},{2,3,4},{3,3,4}}},
        {8,{{1,0,0},{1,2,3},{2,2,4},{3,2,4}}},
        {9,{{1,0,0},{1,2,3},{2,3,4}}},
        {10,{{1,0,0},{0,1,1},{1,1,1},{2,1,1},{2,1,2},{2,1,3},{2,2,4}}},
        {23,{{1,0,0},{0,7,3},{1,7,3},{1,8,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,2,1},{4,2,2},{3,2,3}}},
        {24,{{1,0,0},{1,7,4},{0,7,3},{1,7,3},{1,8,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,2,1},{4,2,2},{4,2,3},{4,2,4}}},
        {25,{{1,0,0},{0,7,3},{1,7,3},{1,8,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{4,3,2},{3,3,3},{4,3,4}}},
        {26,{{1,0,0},{1,6,4},{1,7,4},{0,7,3},{1,7,3},{1,8,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,2,1},{4,2,2},{4,2,3}}},
        {27,{{1,0,0},{0,7,3},{1,7,3},{1,8,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,4,4},{4,3,3},{5,3,4},{5,2,4}}},
        {28,{{1,0,0},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,4,4},{4,3,3},{5,3,4}}},
        {29,{{1,0,0},{1,7,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{5,2,3}}},
        {30,{{1,0,0},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,4},{6,2,4}}},
        {31,{{1,0,0},{1,6,2},{1,7,2},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,4}}},
        {32,{{1,0,0},{0,3,3},{1,3,2},{1,2,3},{1,2,2},{1,1,1},{0,1,1},{0,2,1}}},
        {33,{{1,0,0},{0,3,3},{1,3,2},{1,2,3},{1,2,2}}},
        {34,{{1,0,0},{1,4,4},{0,3,3},{1,3,2}}},
        {35,{{1,0,0},{1,5,4},{1,4,4},{0,3,3},{0,2,3},{0,2,2},{0,3,2}}},
        {36,{{1,0,0},{0,3,3},{0,2,3},{0,2,2}}},
        {37,{{1,0,0},{0,4,3},{0,3,3},{0,2,3}}},
        {38, {{1,0,0},{1,3,3},{1,3,4},{1,2,4}}},
        {39,{{1,0,0},{1,5,2},{1,4,2},{1,3,3},{1,3,4},{0,3,4},{0,2,4}}},
        {40,{{1,0,0},{1,4,2},{1,3,3},{1,3,4}}},
        {41,{{1,0,0},{1,4,1},{2,4,1},{3,3,1},{3,4,2},{3,3,3},{2,3,3},{1,3,3},{0,3,3},{0,3,4}}},
        {42,{{1,0,0},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,2,3}}},
        {43,{{1,0,0},{0,7,1},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{7,3,4},{7,2,4}}},
        {44,{{1,0,0},{1,7,1},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{7,3,4}}},
        {45,{{1,0,0},{0,6,1},{1,6,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,3,2},{6,2,2}}},
        {46,{{1,0,0},{1,6,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,3,2}}},
        {47,{{1,0,0},{2,7,1},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{6,3,1},{6,2,1}}},
        {48,{{1,0,0},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{6,3,1},{6,3,0},{6,2,0}}},
        {49,{{1,0,0},{2,6,1},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{6,3,1},{6,3,0}}},
        {50,{{1,0,0},{2,5,1},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{6,3,1},{7,3,0},{7,2,0}}},
        {51,{{1,0,0},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{6,3,1},{7,3,0}}},
        {52,{{1,0,0},{2,4,1},{3,4,1},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{7,3,2},{7,2,2}}},
        {53,{{1,0,0},{3,3,1},{3,4,2},{3,3,3},{4,3,3},{5,3,3},{6,3,3},{6,4,2},{7,3,2}}},
        {54,{{1,0,0},{2,4,0}}}
};
size_t currentPosNum=nextPos[1][0][0];

void MyBridgeAppCode::startup() {
    console << "start " << getId() << "\n";
    sum = Vector3D(0,0,0);
    VecPos = Cell3DPosition(0,0,0);
    Poly = MyPolygon(30);
    Poly1 = MyPolygon(30);

    if (isLeader) {
        module->setColor(RED);
        currentRound=1;
        distance=0;
        nbWaitedAnswers=sendMessageToAllNeighbors("distance(1,1)",new MessageOf<pair<int,int>>(BROADCAST_MSG_ID,make_pair(distance+1,currentRound)),1000,100,0);
        if (target && target->isInTarget(module->position)) {
            setColor(BLACK);
        }
    } else {
        currentRound=0;
    }
}

void MyBridgeAppCode::myBroadcastFunc(std::shared_ptr<Message>_msg, P2PNetworkInterface*sender) {

    MessageOf<pair<int,int>>* msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
    pair<int,int> msgData = *msg->getData();


    console << "rec. Flood (" << msgData.first << "," << msgData.second << ") from " << sender->getConnectedBlockId() << "\n";
    if (parent==nullptr /**|| distance > msgData.first**/) {
        distance=msgData.first;
        //setColor(distance);
        currentRound=msgData.second;
        parent=sender;
        string str="distance(";
        str+=to_string(distance+1)+","+to_string(currentRound)+")";
        nbWaitedAnswers=sendMessageToAllNeighbors(str.c_str(),new MessageOf<pair<int,int>>(BROADCAST_MSG_ID,make_pair(distance+1,currentRound)),1000,100,1,sender);
        if (nbWaitedAnswers==0) {
            sum = Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(module->position);
            VecPos = module->position;
            if(VecPos.pt[2] ==0) {
                listBase.push_back(VecPos);
                setColor(BLUE);
            }

            sendMessage("ack2parent",new MessageOf<pair<Vector3D, vector<Cell3DPosition>>>(ACKNOWLEDGE_MSG_ID, make_pair(sum,listBase)),parent,1000,100);
        }
    } else {
        sendMessage("ack2sender",new MessageOf<pair<Vector3D, vector<Cell3DPosition>>>(ACKNOWLEDGE_MSG_ID, make_pair(Vector3D(0,0,0), vector<Cell3DPosition>())),sender,1000,100);
    }


}

void MyBridgeAppCode::myAcknowledgeFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
    MessageOf<pair<Vector3D,vector<Cell3DPosition>>>* msg = static_cast<MessageOf<pair<Vector3D,vector<Cell3DPosition>>>*>(_msg.get());
    pair<Vector3D,vector<Cell3DPosition>> msgData = *msg->getData();;
    nbWaitedAnswers--;
    console << "rec. Ack(" << msgData.first << ", " << ") from " << sender->getConnectedBlockId() << "\n";
    console << "rec. Ack(" << nbWaitedAnswers   << ") from " << sender->getConnectedBlockId() << "\n";

    sum += msgData.first;
    VecPos = module->position;


    if(not msgData.second.empty())
        listBase.insert(listBase.end(), msgData.second.begin(), msgData.second.end());



    if (nbWaitedAnswers == 0) {
        setColor(WHITE);
        sum += Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(module->position);
        if (VecPos[2]==0){
            listBase.push_back(VecPos);
            module->setColor(BLUE);
        }

        if (parent == nullptr) {


            g.x = (float) sum[0] / (float) sum[3];
            g.y = (float) sum[1] / (float) sum[3];
            g.z = (float) sum[2] / (float) sum[3];
            cerr << sum << endl;
            cerr << "G(" << g.x << ", " << g.y << ", " << g.z << ")\n";
            for(auto &x: listBase) {
                cerr << x << " ";
            }
            cerr <<"\n";


            for(unsigned int i= 0 ; i<1 ; i++ ){
                z=Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(listBase[i]);
                Poly.addPoint(Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6)));
            }


            for(auto &x: listBase) {
                z = Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(x);
                y= Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6));
                Poly.insertPoint(y);
            }





            cerr << Poly.affichage() <<  "\n";
            y= Vector2D(g.x,g.y);
            cerr << "la verticale passant par le centre de gravite coupe la surface de sustentation? :" << Poly.isInside(y) <<"\n";
            isStable= (Poly.isInside(y)==1);
            if (Poly.isInside(y)==1){
                cerr << "Le corps est stable \n";
                module->setColor(GREEN);
            }
            else{
                cerr << "Le corps est instable \n";
            }

            object_present = true;
            isStable=true;
            sum += Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum]);
            sum -= Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(module->position);
            g.x = (float) sum[0] / (float) sum[3];
            g.y = (float) sum[1] / (float) sum[3];
            g.z = (float) sum[2] / (float) sum[3];
            //cerr << sum << endl;
            cerr << "G1(" << g.x << ", " << g.y << ", " << g.z << ")\n";
            y= Vector2D(g.x,g.y);
            if(Poly.isInside(y)==1){
                cerr << "poly is inside:"<<Poly.isInside(y)<<"\n";
                cerr << "you can move \n";
                tryToMove();
            }else{
                cerr << "poly is inside:"<<Poly.isInside(y)<<"\n";
                cerr<< "you can't move\n";
                sum -= Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum]);
                sum += Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(module->position);
                g.x = (float) sum[0] / (float) sum[3];
                g.y = (float) sum[1] / (float) sum[3];
                g.z = (float) sum[2] / (float) sum[3];
                //cerr << sum << endl;
                cerr << "G2(" << g.x << ", " << g.y << ", " << g.z << ")\n";

            }





        } else {
            //PAS RACINE
            sendMessage("ack2parent", new MessageOf<pair<Vector3D, vector<Cell3DPosition>>>(ACKNOWLEDGE_MSG_ID, make_pair(sum,listBase)), parent, 1000,
                        100);
        }
    }
}

bool MyBridgeAppCode::tryToMove() {
    vector<std::pair<const Catoms3DMotionRulesLink*, Catoms3DRotation>> tab = Catoms3DMotionEngine::getAllRotationsForModule(module);
    Cell3DPosition pos;
    cout << "tryToMove\n";
    short n;
    currentPosNum=nextPos[module->blockId][0][0];
    cout << "Search dest (" << module->blockId << "):" << nextPos[module->blockId][currentPosNum] << endl;
    bool found=false;
    auto it = tab.begin();
    while (it!=tab.end() && !found) {
        it->second.init(((Catoms3DGlBlock*)module->ptrGlBlock)->mat);
        it->second.getFinalPositionAndOrientation(pos,n);
        found = (pos==nextPos[module->blockId][currentPosNum]);
        cout << "found: " << pos << endl;
        if (found) {
            scheduler->schedule(new Catoms3DRotationStartEvent(getScheduler()->now(), module, it->second.pivot,pos));
        }
        it++;
    }

    return found;
}

void MyBridgeAppCode::parseUserBlockElements(TiXmlElement *config) {
    const char *attr = config->Attribute("leader");
    isLeader = (attr?Simulator::extractBoolFromString(attr):false);
    if (isLeader) {
        std::cout << getId() << " is leader!" << std::endl; // complete with your code
    }

    attr = config->Attribute("target");
    if (attr) {
        Cell3DPosition targetPos=Simulator::extractCell3DPositionFromString(attr);
    }
}

void MyBridgeAppCode::RequestMobileObject(){

    round ++;
    nbWaitedAnswers=sendMessageToAllNeighbors("REQUEST_OBJECT",new MessageOf<int>(BROADCAST2_MSG_ID,round),1000,100,0);


}

void MyBridgeAppCode::myBroadcastFunc2(std::shared_ptr<Message>_msg, P2PNetworkInterface*sender){
    MessageOf<int>* msg = static_cast<MessageOf<int>*>(_msg.get());
    int msgData = *msg->getData();
    if (msgData>round) {
        round = msgData;
        parent=sender;
        if (object_present) {

            object_present = false;
            MobileObject obj;
            obj.sum = sum;
            obj.Poly = Poly;
            obj.listBase=listBase;
            cerr << "le msg a envoyer a la racine est:"<< obj.sum << ""<<endl;
            Poly.affichage();
            sendMessage("Grant_Object",new MessageOf<MobileObject>(ACKNOWLEDGE2_MSG_ID, obj),parent,1000,100);
        }else{

            nbWaitedAnswers=sendMessageToAllNeighbors("REQUEST_OBJECT",new MessageOf<int>(BROADCAST2_MSG_ID,round),1000,100,1,sender);

        }

    }
}

void MyBridgeAppCode::onMessageReceived(std::shared_ptr<Message> _msg, P2PNetworkInterface* sender) {
    MessageOf<MobileObject>* msg = static_cast<MessageOf<MobileObject>*>(_msg.get());
    MobileObject msgData = *msg->getData();
    if(parent == nullptr){
        mobileObject = *msg->getData();
        object_present=true;
        cerr << "test de mobile object" <<mobileObject.sum <<"fin test" <<endl;
        sum = mobileObject.sum;
        Poly = mobileObject.Poly;
        listBase = mobileObject.listBase;


        if(module->position[2]==0){

            module->setColor(WHITE);
            //Enlever l'element de lisbase
            listBase.erase(std::remove(listBase.begin(), listBase.end(),module->position),
                           listBase.end());
            //initialiser Poly
            Poly=Poly1;
            //remplire Poly
            for(unsigned int i= 0 ; i<1 ; i++ ){
                z=Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(listBase[i]);
                Poly.addPoint(Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6)));
            }
            for(auto &x: listBase) {
                z = Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(x);
                y= Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6));
                Poly.insertPoint(y);
            }
            //cerr<< "ici un changement de poly"<<endl;
            //Poly.affichage();

        }
        if(nextPos[module->blockId][1][2]==0){
            listBase.push_back(nextPos[module->blockId][1]);
            z = Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][1]);
            y= Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6));
            Poly.insertPoint(y);
            y= Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6));
            Poly.insertPoint(y);
            y= Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6));
            Poly.insertPoint(y);
            y= Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6));
            Poly.insertPoint(y);
            //cerr<< "ici un changement de poly"<<endl;
            //Poly.affichage();
        }

        sum += Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][1]);
        sum -= Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(module->position);
        g.x = (float) sum[0] / (float) sum[3];
        g.y = (float) sum[1] / (float) sum[3];
        g.z = (float) sum[2] / (float) sum[3];
        cerr << sum << endl;
        cerr << "G1(" << g.x << ", " << g.y << ", " << g.z << ")\n";
        y= Vector2D(g.x,g.y);
        cerr << Poly.affichage() <<  "\n";
        isStable= (Poly.isInside(y)==1);
        if(Poly.isInside(y)==1){
            tryToMove();
        }


    }else{

        mobileObject = *msg->getData();
        sendMessage("Grant_Object", new MessageOf<MobileObject>(ACKNOWLEDGE2_MSG_ID, mobileObject), parent, 1000,
                    100);
    }

}


auto it=nextPos.begin();
void MyBridgeAppCode::onMotionEnd() {
    // complete with your code

    short x = nextPos[module->blockId][0][0];
    nextPos[module->blockId][0]= {static_cast<short>(x+1),0,0};
    if (currentPosNum<nextPos[module->blockId].size()-1){
        if(nextPos[module->blockId][currentPosNum+1][2]==0){
            setColor(BLUE);
            listBase.push_back(nextPos[module->blockId][currentPosNum+1]);
            z = Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum+1]);
            y= Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6));
            Poly.insertPoint(y);
            y= Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6));
            Poly.insertPoint(y);
            y= Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6));
            Poly.insertPoint(y);
            y= Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6));
            Poly.insertPoint(y);
            //cerr<< "ici un changement de poly"<<endl;
            //Poly.affichage();
        }
        if(nextPos[module->blockId][currentPosNum][2]==0){
            //Enlever l'element de lisbase
            listBase.erase(std::remove(listBase.begin(), listBase.end(),nextPos[module->blockId][currentPosNum]),
                           listBase.end());
            //initialiser Poly
            Poly=Poly1;
            //remplire Poly
            for(unsigned int i= 0 ; i<1 ; i++ ){
                z=Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(listBase[i]);
                Poly.addPoint(Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6)));
                Poly.addPoint(Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6)));
            }
            for(auto &x: listBase) {
                z = Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(x);
                y= Vector2D(z[0]+(0.45308*6),z[1]+(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]+(0.45308*6),z[1]-(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]-(0.45308*6),z[1]-(0.45308*6));
                Poly.insertPoint(y);
                y= Vector2D(z[0]-(0.45308*6),z[1]+(0.45308*6));
                Poly.insertPoint(y);
            }
            //cerr<< "ici un changement de poly"<<endl;
            //Poly.affichage();

        }
        sum += Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum+1]);
        sum -= Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum]);
        g.x = (float) sum[0] / (float) sum[3];
        g.y = (float) sum[1] / (float) sum[3];
        g.z = (float) sum[2] / (float) sum[3];
        cerr << sum << endl;
        cerr << "G1(" << g.x << ", " << g.y << ", " << g.z << ")\n";
        y= Vector2D(g.x,g.y);
        isStable= (Poly.isInside(y)==1);
        if(Poly.isInside(y)==1){
            cerr << "poly is inside:"<<Poly.isInside(y)<<"\n";
            cerr << "you can move \n";
            tryToMove();
        }else{
            cerr << "poly is inside:"<<Poly.isInside(y)<<"\n";
            cerr<< "you can't move \n";
            isStable=true;
            sum -= Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum+1]);
            sum += Catoms3DWorld::getWorld()->lattice->gridToWorldPosition(nextPos[module->blockId][currentPosNum]);
            g.x = (float) sum[0] / (float) sum[3];
            g.y = (float) sum[1] / (float) sum[3];
            g.z = (float) sum[2] / (float) sum[3];
            cerr << sum << endl;
            cerr << "G2(" << g.x << ", " << g.y << ", " << g.z << ")\n";


        }
    }else {
        isLeader=false;
        it++;
        cout<<"new block id is:"<<it->first<<"end."<< endl; // accede à la clé
        auto * block = static_cast<MyBridgeAppCode*>(BaseSimulator::getWorld()->getBlockById(it->first)->blockCode);
        block->parent = nullptr;
        block->isLeader=true;
        block->RequestMobileObject();
    }

    console << " End of motion to " << module->position << "\n";
}

void glPushPin(float h,int faces) {
    float prec = 2.0*M_PI/float(faces);
    const float h1 = 4.0;
    const float h2 = h-8.0;
    const float r0 = 0.5;
    const float r1 = 2.5;
    float a;
    double x0,y0,x1,y1;
    // pin top
    glBegin(GL_TRIANGLE_FAN);
    glNormal3f(0,0,1);
    glVertex3d(0,0,h);
    a=0;
    for (int i=0; i<=faces; i++) {
        x0 = r1*cos(a);
        y0 = r1*sin(a);
        glVertex3d(x0,y0,h);
        a+=prec;
    }
    glEnd();
    // pin body
    glBegin(GL_QUAD_STRIP);
    a=0;
    for (int i=0; i<=faces; i++) {
        x0 = r1*cos(a);
        y0 = r1*sin(a);
        glNormal3f(x0,y0,0);
        glVertex3d(x0,y0,h);
        glVertex3d(x0,y0,h2);
        a+=prec;
    }
    glEnd();
    // pin base
    glBegin(GL_QUAD_STRIP);
    a=0;
    glNormal3f(0,0,-1.0);
    for (int i=0; i<=faces; i++) {
        x0 = cos(a);
        y0 = sin(a);
        glVertex3d(r1*x0,r1*y0,h2);
        glVertex3d(r0*x0,r0*y0,h2);
        a+=prec;
    }
    glEnd();
    WHITE.glMaterial(GL_FRONT,GL_AMBIENT_AND_DIFFUSE);
// pointe
    glBegin(GL_TRIANGLES);
    a=prec;
    x0=r0;
    y0=0.0;
    for (int i=0; i<faces; i++) {
        x1 = r0*cos(a);
        y1 = r0*sin(a);
        glNormal3f(h1*x0,h1*y0,-r0);
        glVertex3d(x0,y0,h1);
        glVertex3f(0,0,0);
        glNormal3f(h1*x1,h1*y1,-r0);
        glVertex3d(x1,y1,h1);
        a+=prec;
        x0=x1;y0=y1;
    }
    glEnd();
    // pied
    glBegin(GL_QUAD_STRIP);
    a=0;
    for (int i=0; i<=faces; i++) {
        x0 = r0*cos(a);
        y0 = r0*sin(a);
        glNormal3f(x0,y0,0);
        glVertex3d(x0,y0,h2);
        glVertex3d(x0,y0,h1);
        a+=prec;
    }
    glEnd();

}

void MyBridgeAppCode::onGlDraw() {
    static float green[4]={0.0,2.0,0.0,1.0};
    static float red[4]={2.0,0.0,0.0,1.0};
    auto bbs=Catoms3DWorld::getWorld()->getMap();
    float z0 = lattice->gridScale[2] * (0.5 - M_SQRT2_2)+0.01;
    for (auto &bb:bbs) {
        auto tc = static_cast<MyBridgeAppCode*>(bb.second->blockCode);
        if (tc->isLeader) {
            if (isStable) glMaterialfv(GL_FRONT,GL_AMBIENT_AND_DIFFUSE,green);
            else glMaterialfv(GL_FRONT,GL_AMBIENT_AND_DIFFUSE,red);
            WHITE.glMaterial(GL_FRONT,GL_SPECULAR);
            glPushMatrix();
            glLineWidth(10);
            glBegin(GL_LINE_LOOP);
            for(int i=0;i<tc->Poly.N;i++)
                glVertex3f(tc->Poly.tabPts[i].x , tc->Poly.tabPts[i].y,z0);
            glEnd(); //glLines, GL_POINTS
            glPushMatrix();
            //glTranslatef(tc->g.x,tc->g.y,tc->g.z);
            glTranslatef(tc->g.x,tc->g.y,z0);
            if (isStable) GREEN.glMaterial(GL_FRONT,GL_AMBIENT_AND_DIFFUSE);
            else RED.glMaterial(GL_FRONT,GL_AMBIENT_AND_DIFFUSE);
            glPushPin(tc->g.z-z0,20);

            //cout << tc->g.x << "," << tc->g.y << "," << tc->g.z << endl;
            //*glDisable(GL_TEXTURE_2D);
            /*glNormal3f(0,0,1);
            glBegin(GL_QUADS);
            glVertex3f(-20,-1,0);
            glVertex3f(20,-1,0);
            glVertex3f(20,1,0);
            glVertex3f(-20,1,0);
            glVertex3f(-1,-20,0);
            glVertex3f(1,-20,0);
            glVertex3f(1,20,0);
            glVertex3f(-1,20,0);
            glEnd();
            glPopMatrix();


            glBegin(GL_LINES);
            glVertex3f(tc->g.x,tc->g.y,tc->g.z);
            glVertex3f(tc->g.x,tc->g.y,0);
            glEnd();
            glLineWidth(1);*/
            glPopMatrix();
        }
    }
}

