
/**
 * @file myBridgeAppCode.hpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2023-10-17                                                                     
 **/	

#ifndef myBridgeAppCode_H_
#define myBridgeAppCode_H_

#include "robots/catoms3D/catoms3DSimulator.h"
#include "robots/catoms3D/catoms3DWorld.h"
#include "robots/catoms3D/catoms3DBlockCode.h"
#include "robots/catoms3D/catoms3DMotionEngine.h"
#include "mypolygon.h"

static const int BROADCAST_MSG_ID = 1002;
static const int BROADCAST2_MSG_ID = 1001;
static const int ACKNOWLEDGE_MSG_ID = 1003;
static const int ACKNOWLEDGE2_MSG_ID = 1004;

using namespace Catoms3D;

struct Gravity {
    float x, y, z;
};
struct MobileObject {
    Vector3D sum;
    MyPolygon Poly;
    vector<Cell3DPosition> listBase;

    MobileObject() : sum(Vector3D(0, 0, 0)), Poly(30), listBase() {}
};

class MyBridgeAppCode : public Catoms3DBlockCode {
private:
	Catoms3DBlock *module = nullptr;
    bool isLeader=false;
    int distance=0;
    int currentRound=0;
    int nbWaitedAnswers=0;
    int round=0;
    Vector3D sum;
    Cell3DPosition VecPos;
    Cell3DPosition position;
    int total=0;
    P2PNetworkInterface *parent= nullptr;
    Gravity g;
    vector<Cell3DPosition> listBase;
    Vector3D z;
    Vector2D y;
    MyPolygon Poly = MyPolygon(30);
    MyPolygon Poly1 = MyPolygon(30);
    bool isStable=false;
    MobileObject mobileObject;
    bool object_present = false;

public :
	MyBridgeAppCode(Catoms3DBlock *host);
	~MyBridgeAppCode() {};

/**
  * This function is called on startup of the blockCode, it can be used to perform initial
  *  configuration of the host or this instance of the program.
  * @note this can be thought of as the main function of the module
  */
    void startup() override;

    bool tryToMove();
    void myBroadcastFunc(std::shared_ptr<Message>_msg,P2PNetworkInterface *sender);

    void myBroadcastFunc2(std::shared_ptr<Message>_msg,P2PNetworkInterface *sender);
    void onMessageReceived(std::shared_ptr<Message> _msg, P2PNetworkInterface* sender);

    void myAcknowledgeFunc(std::shared_ptr<Message>_msg,P2PNetworkInterface *sender);
/**
  * @brief Callback function executed whenever the module finishes a motion
  */
    void parseUserBlockElements(TiXmlElement *config) override;

    void RequestMobileObject();

    void onMotionEnd() override;

    void onGlDraw() override;

/*****************************************************************************/
/** needed to associate code to module                                      **/
	static BlockCode *buildNewBlockCode(BuildingBlock *host) {
	    return(new MyBridgeAppCode((Catoms3DBlock*)host));
	}
/*****************************************************************************/
};

#endif /* myBridgeAppCode_H_ */