#to remove depricated char* warnings
NOSTRINGWARN = -Wno-write-strings

MPICPP = $(shell mpic++ --version > /dev/null && echo exists)

ifeq (exists, $(MPICPP))
	CXX = mpic++
else
	CXX = g++
endif

CXXFLAGS += -DMULTI_NODE_PER_PROC=1
LIBRARIES +=  -lboost_serialization-mt -lboost_mpi-mt

-include Makefile.common

# DO NOT DELETE
