#!/bin/sh

# run either meld-mpi or meld-bbsim or ...

# entire command line
all="$@"

# see if -a is specified, if not, report error

aname=""
while [ "$#" -gt "0" ]
do
    if [ ${aname:-empty} == empty ]; then
	opt=$1;
	shift;
	case $opt in
	    -a)
		case $1 in 
		    mpi)
			aname=meld-mpi
			;;
		    bbsim)
			aname=meld-bbsim
			;;
		    *)
			echo "Unknown api: $1"
			exit 1;
		esac
		;;
	esac
    else
	break
    fi
done
if [ ${aname:-empty} == empty ]; then
    echo "Did not specify an api, use -a <api>"
    exit 1;
fi
pushd $(dirname $0) > /dev/null
thisdir=`pwd`
popd > /dev/null
PATH=$PATH:$thisdir
$aname $all


