#!/bin/sh

TARGET=${1}
shift
FILES="${*}"

if [ -z "$TARGET" ]; then
	echo "No target directory provided"
	exit 1
fi
if [ -z "$FILES" ]; then
	echo "No input files provided"
	exit 1
fi

ARG=""
for file in $FILES; do
	if [ ! -f "${file}" ]; then
		continue
	fi
	base=`basename $file .meld`
	ARG="$ARG $file $PWD/$TARGET/$base"
done
meld-compile-file $ARG
