BaseSimulator::Clock
ClockType
Resolution
Accuracy
BuildingBlock* BaseSimulator::Clock::hostBlock
Referenced by Clock, setClockProperties, getTimeUS, getSchedulerTimeForLocalTime.
ClockType BaseSimulator::Clock::type
Referenced by Clock.
Accuracy BaseSimulator::Clock::accuracy
Referenced by setClockProperties.
Resolution BaseSimulator::Clock::resolution
Referenced by setClockProperties, getTime.
double BaseSimulator::Clock::D
Referenced by setClockProperties, getTimeUS, getSchedulerTimeForLocalTime.
double BaseSimulator::Clock::y0
Referenced by setClockProperties, getTimeUS, getSchedulerTimeForLocalTime.
double BaseSimulator::Clock::x0
Referenced by Clock, getTimeUS, getSchedulerTimeForLocalTime.
double BaseSimulator::Clock::sigma
Referenced by setClockProperties, getTimeUS, getSchedulerTimeForLocalTime.
boost::rand48 BaseSimulator::Clock::generator
Referenced by Clock, setClockProperties, getTimeUS, getSchedulerTimeForLocalTime.
list<ReferencePoint> BaseSimulator::Clock::referencePoints
Referenced by getTimeUS, getSchedulerTimeForLocalTime, cleanReferencePoints.
uint64_t BaseSimulator::Clock::getTime(uint64_t simTime)
returns the current local time for the concerned block
References resolution, getTimeUS, getTimeMS.
uint64_t BaseSimulator::Clock::getTime()
References BaseSimulator::getScheduler.
uint64_t BaseSimulator::Clock::getSchedulerTimeForLocalTime(uint64_t localTime)
References hostBlock, BaseSimulator::BuildingBlock::blockId, sigma, generator, cleanReferencePoints, referencePoints, y0, D, x0.
BaseSimulator::Clock::Clock(ClockType clockType, BuildingBlock *h)
References hostBlock, type, x0, BaseSimulator::getScheduler, BaseSimulator::Scheduler::now, generator, BaseSimulator::BuildingBlock::blockId, setClockProperties.
virtual BaseSimulator::Clock::~Clock()
void BaseSimulator::Clock::setClockProperties(ClockType clockType)
References XMEGA_RTC_OSC1K_ULPRC, resolution, accuracy, D, y0, XMEGA_RTC_OSC1K_CRC, hostBlock, BaseSimulator::BuildingBlock::blockId, generator, sigma, XMEGA_RTC_OSC32K_EXT.
Referenced by Clock.
uint64_t BaseSimulator::Clock::getTimeMS(uint64_t simTime)
References getTimeUS.
Referenced by getTime.
uint64_t BaseSimulator::Clock::getTimeUS(uint64_t simTime)
References hostBlock, BaseSimulator::BuildingBlock::blockId, sigma, generator, cleanReferencePoints, referencePoints, D, y0, x0.
Referenced by getTime, getTimeMS.
void BaseSimulator::Clock::cleanReferencePoints()
References BaseSimulator::getScheduler, BaseSimulator::Scheduler::now, referencePoints.
Referenced by getTimeUS, getSchedulerTimeForLocalTime.