MeldProcess::VMCommand
commandType* MeldProcess::VMCommand::data
Referenced by VMCommand, getContentSize, getType, getTimestamp, getSource, getData, setTimestamp, copyData, MeldProcess::AddNeighborVMCommand::AddNeighborVMCommand, MeldProcess::RemoveNeighborVMCommand::RemoveNeighborVMCommand, MeldProcess::SetColorVMCommand::getColor, MeldProcess::SendMessageVMCommand::getDestFace, MeldProcess::SendMessageVMCommand::getDestId, MeldProcess::ReceiveMessageVMCommand::ReceiveMessageVMCommand, MeldProcess::ReceiveMessageVMCommand::~ReceiveMessageVMCommand, MeldProcess::AccelVMCommand::AccelVMCommand, MeldProcess::ShakeVMCommand::ShakeVMCommand, MeldProcess::WorkEndVMCommand::getNbProcessedMsg, MeldProcess::DebbuggerVMCommand::getDebuggerCommand.
MeldProcess::VMCommand::VMCommand(commandType *d, commandType s, commandType t, commandType src)
References data, CONTENT_SIZE, TYPE, TIMESTAMP, BaseSimulator::getScheduler, BaseSimulator::Scheduler::now, NODE.
MeldProcess::VMCommand::VMCommand(commandType *d)
References data.
commandType MeldProcess::VMCommand::getContentSize()
References data, CONTENT_SIZE.
Referenced by getSize.
commandType MeldProcess::VMCommand::getSize()
References getContentSize.
Referenced by MeldProcess::MeldProcessVM::sendCommand, copyData.
commandType MeldProcess::VMCommand::getType()
References data, TYPE.
commandType MeldProcess::VMCommand::getTimestamp()
References data, TIMESTAMP.
commandType MeldProcess::VMCommand::getSource()
References data, NODE.
Referenced by MeldProcess::ReceiveMessageVMCommand::ReceiveMessageVMCommand.
commandType * MeldProcess::VMCommand::getData()
References data.
Referenced by MeldProcess::MeldProcessDebugger::handleDebugCommand, MeldProcess::MeldProcessVM::sendCommand, MeldProcess::MeldProcessVM::handleCommand.
void MeldProcess::VMCommand::setTimestamp(commandType ts)
References data, TIMESTAMP.
void MeldProcess::VMCommand::copyData()
References getSize, data.
Referenced by MeldProcess::MeldProcessVM::handleCommand, MeldProcess::ReceiveMessageVMCommand::ReceiveMessageVMCommand.
commandType MeldProcess::VMCommand::getType(commandType *d)
References TYPE.
Referenced by MeldProcess::MeldProcessVM::sendCommand, MeldProcess::MeldProcessVM::handleDeterministicMode, MeldProcess::MeldProcessVM::handleCommand.
commandType MeldProcess::VMCommand::getTimestamp(commandType *d)
References TIMESTAMP.
Referenced by MeldProcess::MeldProcessVM::handleCommand.
string MeldProcess::VMCommand::getString(commandType t)
References VM_COMMAND_SET_COLOR, VM_COMMAND_SEND_MESSAGE, VM_COMMAND_DEBUG, VM_COMMAND_WORK_END, VM_COMMAND_TIME_INFO, VM_COMMAND_POLL_START, VM_COMMAND_END_POLL, ERRPUT.