RobotBlocks::PointRel3D
short RobotBlocks::PointRel3D::x
Referenced by RobotBlocks::RobotBlocksBlock::getP2PNetworkInterfaceByRelPos, RobotBlocks::Capability::getCenter, RobotBlocks::ValidationMatrix::get, RobotBlocks::ValidationMatrix::set, fromString, RobotBlocks::operator<<, rotateY, rotateZ, set, isInBoundingBox, RobotBlocks::operator!=, RobotBlocks::operator==, RobotBlocks::PresenceMatrix::add, RobotBlocks::PresenceMatrix::get, RobotBlocks::PresenceMatrix::set, RobotBlocks::RobotBlocksWorld::getPresenceMatrix.
short RobotBlocks::PointRel3D::y
Referenced by RobotBlocks::RobotBlocksBlock::getP2PNetworkInterfaceByRelPos, RobotBlocks::Capability::getCenter, RobotBlocks::ValidationMatrix::get, RobotBlocks::ValidationMatrix::set, fromString, RobotBlocks::operator<<, rotateY, rotateZ, set, RobotBlocks::operator!=, RobotBlocks::operator==, RobotBlocks::PresenceMatrix::add, RobotBlocks::PresenceMatrix::get, RobotBlocks::PresenceMatrix::set, RobotBlocks::RobotBlocksWorld::getPresenceMatrix.
short RobotBlocks::PointRel3D::z
Referenced by RobotBlocks::RobotBlocksBlock::getP2PNetworkInterfaceByRelPos, RobotBlocks::Capability::getCenter, RobotBlocks::ValidationMatrix::get, RobotBlocks::ValidationMatrix::set, fromString, RobotBlocks::operator<<, rotateY, rotateZ, set, isInBoundingBox, RobotBlocks::operator!=, RobotBlocks::operator==, RobotBlocks::PresenceMatrix::add, RobotBlocks::PresenceMatrix::get, RobotBlocks::PresenceMatrix::set, RobotBlocks::RobotBlocksWorld::getPresenceMatrix.
PointRel3D::PointRel3D()
PointRel3D::PointRel3D(short vx, short vy, short vz)
PointRel3D::PointRel3D(const string &str)
References fromString.
void PointRel3D::set(short vx, short vy, short vz)
References x, y, z.
Referenced by RobotBlocks::Capability::getMotionVector.
bool PointRel3D::isInBoundingBox(short x0, short x1, short y0, short y1, short z0, short z1)
References x, z.
void PointRel3D::fromString(const string &str)
References x, y, z.
Referenced by RobotBlocks::RobotBlocksCapabilities::RobotBlocksCapabilities, PointRel3D.
void PointRel3D::fromString(const string &str, const PointRel3D &ref)
References x, y, z.
PointRel3D PointRel3D::rotateY(int n) const
References x, z, y.
PointRel3D PointRel3D::rotateZ(int n) const
References x, y, z.
Referenced by RobotBlocks::Capability::Capability.
bool RobotBlocks::PointRel3D::isZero()
bool RobotBlocks::PointRel3D::isSet() const
References operator==, operator!=, operator<<.
bool operator==(const PointRel3D p1, const PointRel3D p2)
Referenced by isSet.
bool operator!=(const PointRel3D p1, const PointRel3D p2)
Referenced by isSet.
ostream& operator<<(ostream &f, const PointRel3D &pt)
Referenced by isSet.