BaseSimulator::BuildingBlock
State
int BaseSimulator::BuildingBlock::nextId
Referenced by RobotBlocks::RobotBlocksBlock::setPrevNext.
int BaseSimulator::BuildingBlock::P2PNetworkInterfaceNextLocalId
list<P2PNetworkInterface*> BaseSimulator::BuildingBlock::P2PNetworkInterfaceList
Referenced by addP2PNetworkInterfaceAndConnectTo.
list<EventPtr> BaseSimulator::BuildingBlock::localEventsList
boost::interprocess::interprocess_mutex BaseSimulator::BuildingBlock::mutex_state
int BaseSimulator::BuildingBlock::blockId
Referenced by BlinkyBlocks::BlinkyBlocksBlock::~BlinkyBlocksBlock, BlinkyBlocks::BlinkyBlocksBlock::addNeighbor, BlinkyBlocks::BlinkyBlocksBlock::removeNeighbor, BlinkyBlocks::operator<<, BlinkyBlocks::BlinkyBlocksBlock::getInterfaceDestId, BlinkyBlocks::BlinkyBlocksWorld::addBlock, BlinkyBlocks::BlinkyBlocksWorld::linkBlocks, BlinkyBlocks::BlinkyBlocksWorld::menuChoice, addP2PNetworkInterfaceAndConnectTo, Catoms2D::Catoms2DBlock::~Catoms2DBlock, Catoms2D::operator<<, Catoms2D::MotionStopEvent::consume, Catoms2D::GenericCodeBlock::GenericCodeBlock, Catoms2D::Catoms2DWorld::addBlock, Catoms2D::Catoms2DWorld::connectBlock, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms2D::Catoms2DWorld::linkBlock, Catoms2D::Catoms2DWorld::menuChoice, Catoms3D::Catoms3DBlock::~Catoms3DBlock, Catoms3D::operator<<, Catoms3D::MotionStopEvent::consume, Catoms3D::Catoms3DWorld::addBlock, Catoms3D::Catoms3DWorld::connectBlock, Catoms3D::Catoms3DWorld::disconnectBlock, Catoms3D::Catoms3DWorld::linkBlock, Catoms3D::Catoms3DWorld::menuChoice, BaseSimulator::Clock::Clock, BaseSimulator::Clock::setClockProperties, BaseSimulator::Clock::getTimeUS, BaseSimulator::Clock::getSchedulerTimeForLocalTime, MeldInterpret::MeldInterpretVM::MeldInterpretVM, MeldInterpret::MeldInterpretVM::down, MeldInterpret::MeldInterpretVM::up, MeldInterpret::MeldInterpretVM::north, MeldInterpret::MeldInterpretVM::south, MeldInterpret::MeldInterpretVM::east, MeldInterpret::MeldInterpretVM::west, MeldProcess::MeldProcessVM::MeldProcessVM, MultiCores::MultiCoresWorld::addBlock, P2PNetworkInterface::getConnectedBlockId, RobotBlocks::RobotBlocksBlock::~RobotBlocksBlock, RobotBlocks::RobotBlocksBlock::setPrevNext, RobotBlocks::operator<<, RobotBlocks::MotionStopEvent::consume, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::GenericCodeBlock::GenericCodeBlock, RobotBlocks::RobotBlocksWorld::addBlock, RobotBlocks::RobotBlocksWorld::connectBlock, RobotBlocks::RobotBlocksWorld::disconnectBlock, RobotBlocks::RobotBlocksWorld::linkBlock, RobotBlocks::RobotBlocksWorld::menuChoice, SmartBlocks::SmartBlocksBlock::~SmartBlocksBlock, SmartBlocks::SmartBlocksBlock::getP2PNetworkInterfaceByDestBlockId, SmartBlocks::SmartBlocksWorld::addBlock.
BlockCode* BaseSimulator::BuildingBlock::blockCode
Referenced by BlinkyBlocks::BlinkyBlocksBlock::BlinkyBlocksBlock, Catoms2D::Catoms2DBlock::Catoms2DBlock, Catoms2D::MotionEndEvent::consume, Catoms3D::Catoms3DBlock::Catoms3DBlock, Catoms3D::MotionEndEvent::consume, CodeStartEvent::consumeBlockEvent, MeldInterpret::VMStopEvent::consume, MeldProcess::VMStopEvent::consume, MeldProcess::MeldProcessVM::broadcastDebugCommand, MeldProcess::MeldProcessVM::sendCommand, MultiCores::MultiCoresBlock::MultiCoresBlock, RobotBlocks::RobotBlocksBlock::RobotBlocksBlock, RobotBlocks::MotionEndEvent::consume, SmartBlocks::SmartBlocksBlock::SmartBlocksBlock, SmartBlocks::MotionEndEvent::consume.
State BaseSimulator::BuildingBlock::state
Referenced by BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::stop, BlockEvent::consume.
Clock* BaseSimulator::BuildingBlock::clock
Referenced by BlinkyBlocks::BlinkyBlocksBlock::BlinkyBlocksBlock.
boost::rand48 BaseSimulator::BuildingBlock::generator
BaseSimulator::BuildingBlock::BuildingBlock(int bId)
References OUTPUT.
BaseSimulator::BuildingBlock::~BuildingBlock()
References OUTPUT.
unsigned int BaseSimulator::BuildingBlock::getNextP2PInterfaceLocalId()
list<P2PNetworkInterface*>& BaseSimulator::BuildingBlock::getP2PNetworkInterfaceList()
Referenced by BlinkyBlocks::BlinkyBlocksBlock::BlinkyBlocksBlock, Catoms2D::Catoms2DBlock::Catoms2DBlock.
P2PNetworkInterface * BaseSimulator::BuildingBlock::getP2PNetworkInterfaceByDestBlockId(int destBlockId)
Referenced by MeldInterpret::MeldInterpretVM::tuple_send.
bool BaseSimulator::BuildingBlock::addP2PNetworkInterfaceAndConnectTo(BuildingBlock *destBlock)
References OUTPUT, blockId, getP2PNetworkInterfaceByBlockRef, P2PNetworkInterfaceList, P2PNetworkInterface::connect.
Referenced by addP2PNetworkInterfaceAndConnectTo, MultiCores::MultiCoresScheduler::waitForVMMessage.
bool BaseSimulator::BuildingBlock::addP2PNetworkInterfaceAndConnectTo(int destBlockId)
References BaseSimulator::getWorld, BaseSimulator::World::getBlockById, addP2PNetworkInterfaceAndConnectTo, getP2PNetworkInterfaceByBlockRef, P2PNetworkInterface::connect.
P2PNetworkInterface * BaseSimulator::BuildingBlock::getP2PNetworkInterfaceByBlockRef(BuildingBlock *destBlock)
Referenced by addP2PNetworkInterfaceAndConnectTo, Catoms2D::Catoms2DBlock::canMove.
void BaseSimulator::BuildingBlock::scheduleLocalEvent(EventPtr pev)
References P2PNetworkInterface::availabilityDate, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::now, BaseSimulator::Scheduler::schedule.
Referenced by NetworkInterfaceStopTransmittingEvent::consume, SetColorEvent::consumeBlockEvent, AddNeighborEvent::consumeBlockEvent, RemoveNeighborEvent::consumeBlockEvent, TapEvent::consumeBlockEvent, AccelEvent::consumeBlockEvent, ShakeEvent::consumeBlockEvent, MeldInterpret::VMSetIdEvent::consume, MeldInterpret::VMSendMessageEvent::consumeBlockEvent, MeldInterpret::VMHandleDebugCommandEvent::consumeBlockEvent, MeldInterpret::VMEndPollEvent::consumeBlockEvent, MeldInterpret::ComputePredicateEvent::consumeBlockEvent, MeldInterpret::AddTupleEvent::consumeBlockEvent, MeldInterpret::RemoveTupleEvent::consumeBlockEvent, MeldProcess::VMSetIdEvent::consume, MeldProcess::VMSendMessageEvent::consumeBlockEvent, MeldProcess::VMHandleDebugCommandEvent::consumeBlockEvent, MeldProcess::VMEndPollEvent::consumeBlockEvent, MultiCores::VMStartComputationEvent::consume, MultiCores::VMEndComputationEvent::consume, MultiCores::VMStartTransmissionEvent::consume.
void BaseSimulator::BuildingBlock::processLocalEvent()
References BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::trace, BaseSimulator::Scheduler::now, BaseSimulator::Scheduler::schedule.
Referenced by ProcessLocalEvent::consumeBlockEvent.
virtual void BaseSimulator::BuildingBlock::updateGlData()
virtual void BaseSimulator::BuildingBlock::addNeighbor(P2PNetworkInterface *ni, BuildingBlock *target)
Referenced by P2PNetworkInterface::connect.
virtual void BaseSimulator::BuildingBlock::removeNeighbor(P2PNetworkInterface *ni)
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::deleteBlock, P2PNetworkInterface::connect, RobotBlocks::RobotBlocksWorld::deleteBlock.
virtual void BaseSimulator::BuildingBlock::stop()
void BaseSimulator::BuildingBlock::lock()
Referenced by BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::stop, BaseSimulator::World::lock.
void BaseSimulator::BuildingBlock::unlock()
Referenced by BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::stop.
State BaseSimulator::BuildingBlock::getState()
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::deleteBlock, MeldInterpret::MeldInterpretVM::equilibrium, MeldProcess::MeldProcessVM::dateHasBeenReachedByAll, MeldProcess::MeldProcessVM::equilibrium, RobotBlocks::RobotBlocksWorld::deleteBlock.
void BaseSimulator::BuildingBlock::setState(State s)
int BaseSimulator::BuildingBlock::getNextRandomNumber()
Referenced by SetColorEvent::SetColorEvent, MeldInterpret::VMSendMessageEvent::VMSendMessageEvent, MeldInterpret::VMEndPollEvent::VMEndPollEvent, MeldInterpret::MeldInterpretVM::execute_iter, MeldProcess::VMSendMessageEvent::VMSendMessageEvent, MeldProcess::VMEndPollEvent::VMEndPollEvent.
uint64_t BaseSimulator::BuildingBlock::getTime()
Referenced by MeldInterpret::MeldInterpretVM::myGetTime.
uint64_t BaseSimulator::BuildingBlock::getSchedulerTimeForLocalTime(uint64_t localTime)