GlutContext
int GlutContext::keyboardModifier
GlutSlidingMainWindow * GlutContext::mainWindow
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::deleteBlock, init, deleteContext, reshapeFunc, addTrace, RobotBlocks::RobotBlocksWorld::deleteBlock.
GlutSlidingDebugWindow * GlutContext::debugWindow
Referenced by init, deleteContext, reshapeFunc.
GlutPopupWindow * GlutContext::popup
Referenced by init, deleteContext, reshapeFunc.
GlutPopupMenuWindow * GlutContext::popupMenu
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms3D::Catoms3DWorld::createPopupMenu, reshapeFunc, RobotBlocks::RobotBlocksWorld::createPopupMenu.
GlutHelpWindow * GlutContext::helpWindow
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createHelpWindow, Catoms2D::Catoms2DWorld::createHelpWindow, Catoms3D::Catoms3DWorld::createHelpWindow, reshapeFunc, RobotBlocks::RobotBlocksWorld::createHelpWindow.
int GlutContext::screenWidth
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, init, reshapeFunc, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
int GlutContext::screenHeight
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Catoms3D::Catoms3DWorld::createPopupMenu, init, reshapeFunc, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, RobotBlocks::RobotBlocksWorld::createPopupMenu, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
int GlutContext::initialScreenWidth
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, reshapeFunc, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
int GlutContext::initialScreenHeight
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, reshapeFunc, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
bool GlutContext::fullScreenMode
Referenced by init, reshapeFunc, setFullScreenMode.
bool GlutContext::saveScreenMode
Referenced by reshapeFunc.
int GlutContext::lastMotionTime
Referenced by reshapeFunc.
int GlutContext::lastMousePos[2]
Referenced by reshapeFunc.
bool GlutContext::mustSaveImage
Referenced by reshapeFunc.
int GlutContext::frameCount
Referenced by reshapeFunc.
int GlutContext::previousTime
Referenced by reshapeFunc.
float GlutContext::fps
Referenced by reshapeFunc.
void GlutContext::init(int argc, char **argv)
References screenWidth, screenHeight, fullScreenMode, initShaders, reshapeFunc, mainWindow, debugWindow, popup.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::BlinkyBlocksWorld, Catoms2D::Catoms2DWorld::Catoms2DWorld, Catoms3D::Catoms3DWorld::Catoms3DWorld, RobotBlocks::RobotBlocksWorld::RobotBlocksWorld, SmartBlocks::SmartBlocksWorld::SmartBlocksWorld.
void GlutContext::deleteContext()
References mainWindow, debugWindow, popup, BaseSimulator::getScheduler, BaseSimulator::Scheduler::start.
Referenced by mainLoop.
void GlutContext::mainLoop(void)
References BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::start, SCHEDULER_MODE_FASTEST, BaseSimulator::Scheduler::waitForSchedulerEnd, BaseSimulator::Scheduler::stop, BaseSimulator::getScheduler, deleteContext.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void GlutContext::addTrace(const string &str, int id, const Color &color)
References mainWindow, GlutSlidingMainWindow::addTrace, BaseSimulator::getScheduler, BaseSimulator::Scheduler::now.
Referenced by BaseSimulator::Scheduler::trace.
void GlutContext::reshapeFunc(int w, int h)
References screenWidth, screenHeight, BlinkyBlocks::getWorld, BlinkyBlocks::BlinkyBlocksWorld::getCamera, Camera::setW_H, Camera::glProjection, mainWindow, GlutSlidingMainWindow::reshapeFunc, debugWindow, GlutSlidingDebugWindow::reshapeFunc, popup, GlutPopupWindow::isShown, GlutPopupWindow::show, GlutSlidingMainWindow::mouseFunc, GlutSlidingDebugWindow::mouseFunc, Camera::mouseMove, helpWindow, GlutWindow::passiveMotionFunc, popupMenu, lastMotionTime, lastMousePos, GlutPopupMenuWindow::mouseFunc, GlutPopupMenuWindow::show, BlinkyBlocks::BlinkyBlocksWorld::menuChoice, GlutHelpWindow::mouseFunc, Camera::mouseDown, BaseSimulator::getWorld, BaseSimulator::World::getBlockByNum, BaseSimulator::World::getSelectedBlock, BaseSimulator::World::tapBlock, BaseSimulator::getScheduler, GlBlock::blockId, Camera::mouseUp, Camera::mouseZoom, GlBlock::toggleHighlight, BaseSimulator::World::setSelectedBlock, GlutSlidingMainWindow::select, BaseSimulator::World::setSelectedFace, BaseSimulator::World::createPopupMenu, GlutSlidingDebugWindow::keyFunc, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::start, SCHEDULER_MODE_REALTIME, BaseSimulator::Scheduler::stop, SCHEDULER_MODE_FASTEST, BaseSimulator::World::getCamera, Camera::setTarget, GlBlock::getPosition, fullScreenMode, initialScreenWidth, initialScreenHeight, BaseSimulator::World::createHelpWindow, GlutHelpWindow::showHide, GlutSlidingMainWindow::openClose, saveScreenMode, mustSaveImage, GlutPopupWindow::setCenterPosition, GlutPopupWindow::setInfo, GlBlock::getPopupInfo, GlutSlidingMainWindow::hasSelectedBlock, BaseSimulator::Scheduler::state, frameCount, previousTime, fps, GlutWindow::drawString, shadowedRenderingStep1, BaseSimulator::World::glDraw, shadowedRenderingStep2, shadowedRenderingStep3, shadowedRenderingStep4, GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, GlutPopupWindow::glDraw, GlutPopupMenuWindow::glDraw, GlutHelpWindow::glDraw, Camera::glLookAt, BaseSimulator::World::glDrawId, BaseSimulator::World::glDrawIdByMaterial.
Referenced by init.
void GlutContext::setFullScreenMode(bool b)
References fullScreenMode.
Referenced by CommandLine::CommandLine.
void GlutContext::passiveMotionFunc(int x, int y)
void GlutContext::motionFunc(int x, int y)
void GlutContext::mouseFunc(int button, int state, int x, int y)
void GlutContext::keyboardFunc(unsigned char c, int x, int y)
void GlutContext::drawFunc(void)
void GlutContext::idleFunc(void)
int GlutContext::selectFunc(int x, int y)
int GlutContext::selectFaceFunc(int x, int y)
int GlutContext::processHits(GLint hits, GLuint *buffer)
bool GlutContext::saveScreen(char *title)
void * GlutContext::lanceScheduler(void *param)
void GlutContext::calculateFPS(void)
void GlutContext::showFPS(void)