Catoms3D::Catoms3DBlock
P2PNetworkInterface* Catoms3D::Catoms3DBlock::tabInterfaces[12][12]
boost::interprocess::interprocess_mutex Catoms3D::Catoms3DBlock::mutex_vm
Catoms3DGlBlock* Catoms3D::Catoms3DBlock::ptrGlBlock
ptr to the GL object
Referenced by getNeighborPos, getInterface, getGlBlock, Catoms3D::MotionStartEvent::consume, Catoms3D::Catoms3DWorld::deleteBlock.
Color Catoms3D::Catoms3DBlock::color
color of the block
Referenced by setColor, Catoms3D::operator<<.
Cell3DPosition Catoms3D::Catoms3DBlock::position
position of the block in the grid of cells;
Referenced by setPositionAndOrientation, Catoms3D::Catoms3DWorld::connectBlock, Catoms3D::Catoms3DWorld::disconnectBlock, Catoms3D::Catoms3DWorld::deleteBlock.
short Catoms3D::Catoms3DBlock::orientationCode
number of the connector that is along the x axis.
Referenced by Catoms3DBlock, setPositionAndOrientation.
Catoms3DBlockCode*(* Catoms3D::Catoms3DBlock::buildNewBlockCode) (Catoms3DBlock *))(Catoms3DBlock *)
Referenced by Catoms3DBlock.
Catoms3D::Catoms3DBlock::Catoms3DBlock(int bId, Catoms3DBlockCode *(*catoms3DBlockCodeBuildingFunction)(Catoms3DBlock *))
Constructor.
bId id of the block catoms3DBlockCodeBuildingFunction : code block function
References OUTPUT, buildNewBlockCode, BaseSimulator::BuildingBlock::blockCode, orientationCode.
Catoms3D::Catoms3DBlock::~Catoms3DBlock()
References OUTPUT, BaseSimulator::BuildingBlock::blockId.
Catoms3DGlBlock* Catoms3D::Catoms3DBlock::getGlBlock()
References ptrGlBlock.
Referenced by Catoms3D::Rotations::Rotations, Catoms3D::Catoms3DWorld::updateGlData.
void Catoms3D::Catoms3DBlock::setGlBlock(Catoms3DGlBlock *ptr)
References setColor, setVisible, setPositionAndOrientation, getInterface.
Referenced by Catoms3D::Catoms3DWorld::addBlock.
void Catoms3D::Catoms3DBlock::setColor(const Color &)
References color, Catoms3D::getWorld, Catoms3D::Catoms3DWorld::updateGlData.
Referenced by setGlBlock, Catoms3D::MotionStartEvent::consume, Catoms3D::MotionStopEvent::consume, Catoms3D::Catoms3DWorld::addBlock.
void Catoms3D::Catoms3DBlock::setVisible(bool visible)
References Catoms3D::getWorld, Catoms3D::Catoms3DWorld::updateGlData.
Referenced by setGlBlock.
void Catoms3D::Catoms3DBlock::setPositionAndOrientation(const Cell3DPosition &p, short code)
References orientationCode, position, Matrice::setRotationZ, Catoms3D::tabOrientationAngles, Matrice::setRotationY, Matrice::setRotationX, Matrice::setTranslation, Catoms3D::getWorld, OUTPUT, Catoms3D::Catoms3DWorld::updateGlData.
Referenced by setGlBlock, Catoms3D::MotionStopEvent::consume, Catoms3D::Catoms3DWorld::addBlock.
P2PNetworkInterface * Catoms3D::Catoms3DBlock::getInterface(const Cell3DPosition &pos)
Get the interface from the neighbor position in the grid.
pos position of the cell (if in the grid) return interface if it exists one connected, NULL otherwise
References Catoms3D::getWorld, Catoms3D::Catoms3DWorld::gridToWorldPosition, ptrGlBlock, Catoms3D::Catoms3DGlBlock::mat, Matrice::inverse, Catoms3D::Catoms3DWorld::getBlocksSize, Catoms3D::tabConnectorPositions.
Referenced by setGlBlock, Catoms3D::Catoms3DWorld::disconnectBlock, Catoms3D::Catoms3DWorld::linkBlock, Catoms3D::Catoms3DWorld::deleteBlock.
P2PNetworkInterface* Catoms3D::Catoms3DBlock::getInterface(int d)
References getNeighborPos, getDirection, getOrientationFromMatrix, Catoms3D::operator<<.
bool Catoms3D::Catoms3DBlock::getNeighborPos(short connectorId, Cell3DPosition &pos)
Get the position of the gridcell in the direction of the given connector.
connectorId id of connector (0..11) pos position of the cell (if in the grid) return true if the cell is in the grid, false otherwise.
References Catoms3D::getWorld, Catoms3D::Catoms3DWorld::getBlocksSize, Catoms3D::Catoms3DWorld::getGridSize, Vecteur::set, Catoms3D::tabConnectorPositions, Vecteur::pt, ptrGlBlock, Catoms3D::Catoms3DGlBlock::mat, Catoms3D::Catoms3DWorld::worldToGridPosition.
Referenced by getInterface, Catoms3D::Catoms3DWorld::linkBlock.
int Catoms3D::Catoms3DBlock::getDirection(P2PNetworkInterface *)
Referenced by getInterface.
short Catoms3D::Catoms3DBlock::getOrientationFromMatrix(const Matrice &mat)
References Matrice::inverse, Vecteur::set, Catoms3D::tabConnectorPositions.
Referenced by getInterface, Catoms3D::Rotations::getFinalPositionAndOrientation.