MeldProcess::MeldProcessDebugger
void(* MeldProcess::MeldProcessDebugger::debuggerCommandHandler) (uint64_t *))(uint64_t *)
Referenced by MeldProcessDebugger, handleDebugCommand, pauseSim, handleBreakAtTimeReached.
MeldProcessDebugger * MeldProcess::MeldProcessDebugger::debugger
Referenced by MeldProcessDebugger.
MeldProcess::MeldProcessDebugger::MeldProcessDebugger()
References debugger, debuggerCommandHandler, MeldProcess::sendCommand, MeldProcess::pauseSimulation, MeldProcess::unPauseSimulation, MeldProcess::quit, ERRPUT.
MeldProcess::MeldProcessDebugger::~MeldProcessDebugger()
int MeldProcess::MeldProcessDebugger::sendCmd(int id, DebbuggerVMCommand &c)
References MeldProcess::MeldProcessVM::sendCommand, MeldProcess::MeldProcessVM::broadcastDebugCommand.
Referenced by MeldProcess::sendCommand.
void MeldProcess::MeldProcessDebugger::pauseSim(int t)
References MeldProcess::getScheduler, SCHEDULER_MODE_REALTIME, MeldProcess::MeldProcessScheduler::pause, debuggerCommandHandler.
Referenced by MeldProcess::pauseSimulation.
void MeldProcess::MeldProcessDebugger::unPauseSim()
References MeldProcess::getScheduler, MeldProcess::MeldProcessScheduler::unPause.
Referenced by MeldProcess::unPauseSimulation.
void MeldProcess::MeldProcessDebugger::handleDebugCommand(DebbuggerVMCommand *c)
References debuggerCommandHandler, MeldProcess::VMCommand::getData.
Referenced by MeldProcess::handleDebugCommand.
void MeldProcess::MeldProcessDebugger::timeOut(int num)
void MeldProcess::MeldProcessDebugger::waitForDebuggerEnd()
void MeldProcess::MeldProcessDebugger::detachDebuggerThread()
void MeldProcess::MeldProcessDebugger::sendTerminateCmd(int id)
void MeldProcess::MeldProcessDebugger::handlePauseRequest()
Referenced by MeldProcess::MeldProcessScheduler::startPaused.
void MeldProcess::MeldProcessDebugger::handleBreakAtTimeReached(uint64_t t)
References debuggerCommandHandler.
Referenced by MeldProcess::MeldProcessScheduler::startPaused.
static MeldProcessDebugger* MeldProcess::MeldProcessDebugger::getDebugger()
static void MeldProcess::MeldProcessDebugger::createDebugger()
static void MeldProcess::MeldProcessDebugger::deleteDebugger()
References MeldProcess::handleDebugCommand.
void MeldProcess::MeldProcessDebugger::print(string s, bool arrow=true)
References MeldProcess::MeldProcessVM::isInDebuggingMode.