GlutSlidingMainWindow
int GlutSlidingMainWindow::openingLevel
GlutButton* GlutSlidingMainWindow::buttonOpen
GlutButton * GlutSlidingMainWindow::buttonClose
multimap<uint64_t,BlockDebugData*> GlutSlidingMainWindow::traces
GlutSlider* GlutSlidingMainWindow::slider
GlBlock* GlutSlidingMainWindow::selectedBlock
GlutSlidingMainWindow::GlutSlidingMainWindow(GLint px, GLint py, GLint pw, GLint ph, const char *titreTexture)
References ID_SW_BUTTON_OPEN, ID_SW_BUTTON_CLOSE, ID_SW_SLD.
GlutSlidingMainWindow::~GlutSlidingMainWindow()
void GlutSlidingMainWindow::openClose()
References GlutButton::isActivated, GlutWindow::x, GlutWindow::w, GlutButton::activate.
Referenced by GlutContext::reshapeFunc.
int GlutSlidingMainWindow::mouseFunc(int button, int state, int mx, int my)
References GlutWindow::mouseFunc, ID_SW_BUTTON_OPEN, GlutWindow::x, GlutWindow::w, GlutButton::activate, ID_SW_BUTTON_CLOSE.
Referenced by GlutContext::reshapeFunc.
void GlutSlidingMainWindow::reshapeFunc(int wx, int wy, int mw, int mh)
References GlutWindow::setGeometry, GlutSlider::update.
Referenced by GlutContext::reshapeFunc.
void GlutSlidingMainWindow::glDraw()
References GlutWindow::bindTexture, GlutWindow::x, GlutWindow::y, GlutWindow::w, GlutWindow::h, BaseSimulator::getScheduler, BaseSimulator::Scheduler::now, GlutWindow::drawString, GlBlock::getInfo, GlutSlider::getPosition, GlBlock::blockId, GlutWindow::glDraw.
Referenced by GlutContext::reshapeFunc.
void GlutSlidingMainWindow::addTrace(int id, const string &str, const Color &color)
References BaseSimulator::getScheduler, GlBlock::blockId, GlutSlider::incDataTextLines.
Referenced by GlutContext::addTrace.
void GlutSlidingMainWindow::select(GlBlock *sb)
References GlBlock::blockId, GlutSlider::setDataTextLines.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::deleteBlock, GlutContext::reshapeFunc, RobotBlocks::RobotBlocksWorld::deleteBlock.
bool GlutSlidingMainWindow::hasSelectedBlock()
Referenced by GlutContext::reshapeFunc.
bool GlutSlidingMainWindow::isOpened()