PointRel3D
short PointRel3D::x
Referenced by Capability::getCenter, StateMatrix::get, StateMatrix::set, StateMatrix::lock, StateMatrix::conditionalDistance, fromString, operator<<, rotateY, rotateZ, set, isInBoundingBox, operator<=, operator>, operator!=.
short PointRel3D::y
Referenced by Capability::getCenter, StateMatrix::get, StateMatrix::set, StateMatrix::lock, StateMatrix::conditionalDistance, fromString, operator<<, rotateY, rotateZ, set, operator<=, operator>, operator!=.
short PointRel3D::z
Referenced by Capability::getCenter, StateMatrix::get, StateMatrix::set, StateMatrix::lock, StateMatrix::conditionalDistance, fromString, operator<<, rotateY, rotateZ, set, isInBoundingBox, operator<=, operator>, operator!=.
PointRel3D::PointRel3D()
PointRel3D::PointRel3D(short vx, short vy, short vz)
PointRel3D::PointRel3D(const string &str)
References fromString.
void PointRel3D::set(short vx, short vy, short vz)
References x, y, z.
Referenced by StateMatrix::conditionalDistance.
bool PointRel3D::isInBoundingBox(short x0, short x1, short y0, short y1, short z0, short z1)
References x, z.
void PointRel3D::fromString(const string &str)
References x, y, z.
Referenced by Capabilities::Capabilities, PointRel3D.
void PointRel3D::fromString(const string &str, const PointRel3D &ref)
References x, y, z.
PointRel3D PointRel3D::rotateY(int n) const
References x, z, y.
PointRel3D PointRel3D::rotateZ(int n) const
References x, y, z.
Referenced by Capability::Capability.
ostream& operator<<(ostream &f, const PointRel3D &pt)
bool operator<=(const PointRel3D p1, const PointRel3D p2)
bool operator>(const PointRel3D p1, const PointRel3D p2)
bool operator!=(const PointRel3D p1, const PointRel3D p2)