Message
uint64_t Message::nextId
uint64_t Message::nbMessages
uint64_t Message::id
unsigned int Message::type
Referenced by MeldInterpret::AddTupleMessage::AddTupleMessage, MeldInterpret::RemoveTupleMessage::RemoveTupleMessage, clone, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors.
P2PNetworkInterface* Message::sourceInterface
Referenced by clone, MessageOf< T >::clone.
P2PNetworkInterface * Message::destinationInterface
Referenced by clone, MessageOf< T >::clone.
Message::Message()
References MESSAGE_CONSTRUCTOR_INFO.
Message::~Message()
References MESSAGE_DESTRUCTOR_INFO.
string Message::getMessageName()
virtual unsigned int Message::size()
Referenced by MultiCores::VMDataMessage::size.
Message * Message::clone()
References sourceInterface, destinationInterface, type.
Referenced by Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors.
uint64_t Message::getNbMessages()
Referenced by Catoms2D::Catoms2DScheduler::startPaused, Catoms3D::Catoms3DScheduler::startPaused, cppScheduler::CppScheduler::startPaused, MeldInterpret::MeldInterpretScheduler::startPaused, MeldProcess::MeldProcessScheduler::startPaused, MultiCores::MultiCoresScheduler::startPaused, RobotBlocks::RobotBlocksScheduler::startPaused, SmartBlocks::SmartBlocksScheduler::startPaused.