GlutPopupMenuWindow
bool GlutPopupMenuWindow::isVisible
GlutPopupMenuWindow::GlutPopupMenuWindow(GlutWindow *parent, GLint px, GLint py, GLint pw, GLint ph)
virtual GlutPopupMenuWindow::~GlutPopupMenuWindow()
void GlutPopupMenuWindow::show(bool v)
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms3D::Catoms3DWorld::createPopupMenu, GlutContext::reshapeFunc, RobotBlocks::RobotBlocksWorld::createPopupMenu.
void GlutPopupMenuWindow::setCenterPosition(int ix, int iy)
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms3D::Catoms3DWorld::createPopupMenu, RobotBlocks::RobotBlocksWorld::createPopupMenu.
void GlutPopupMenuWindow::addButton(int id, const char *titre)
References GlutWindow::children, GlutWindow::setGeometry, GlutWindow::h, GlutWindow::w.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms3D::Catoms3DWorld::createPopupMenu, RobotBlocks::RobotBlocksWorld::createPopupMenu.
int GlutPopupMenuWindow::mouseFunc(int button, int state, int x, int y)
References GlutWindow::mouseFunc.
Referenced by GlutContext::reshapeFunc.
void GlutPopupMenuWindow::glDraw()
References GlutWindow::x, GlutWindow::y, GlutWindow::w, GlutWindow::h, GlutWindow::glDraw.
Referenced by GlutContext::reshapeFunc.
void GlutPopupMenuWindow::activate(unsigned int n, bool value)
References GlutWindow::children, GlutWindow::id.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DWorld::createPopupMenu, RobotBlocks::RobotBlocksWorld::createPopupMenu.
void GlutPopupMenuWindow::addTrace(int id, int time, const string &str)