MeldInterpret::MeldInterpretScheduler
boost::thread* MeldInterpret::MeldInterpretScheduler::schedulerThread
int MeldInterpret::MeldInterpretScheduler::schedulerMode
Referenced by start.
boost::interprocess::interprocess_semaphore* MeldInterpret::MeldInterpretScheduler::sem_schedulerStart
Referenced by start, unPause.
MeldInterpret::MeldInterpretScheduler::MeldInterpretScheduler()
References OUTPUT, SCHEDULER_MODE_REALTIME.
MeldInterpret::MeldInterpretScheduler::~MeldInterpretScheduler()
References OUTPUT.
void * MeldInterpret::MeldInterpretScheduler::startPaused()
References OUTPUT, SCHEDULER_MODE_FASTEST, BlinkyBlocks::getWorld, SCHEDULER_MODE_REALTIME, Event::getNextId, Event::getNbLivingEvents, Message::getNbMessages.
void MeldInterpret::MeldInterpretScheduler::createScheduler()
Referenced by BlinkyBlocks::createScheduler.
void MeldInterpret::MeldInterpretScheduler::deleteScheduler()
Referenced by BlinkyBlocks::deleteScheduler.
static MeldInterpretScheduler* MeldInterpret::MeldInterpretScheduler::getScheduler()
void MeldInterpret::MeldInterpretScheduler::printInfo()
References OUTPUT.
void MeldInterpret::MeldInterpretScheduler::start(int mode)
References schedulerMode, sem_schedulerStart.
void MeldInterpret::MeldInterpretScheduler::waitForSchedulerEnd()
void MeldInterpret::MeldInterpretScheduler::stop(uint64_t date)
void MeldInterpret::MeldInterpretScheduler::pause(uint64_t date)
void MeldInterpret::MeldInterpretScheduler::unPause()
References sem_schedulerStart, OUTPUT.
bool MeldInterpret::MeldInterpretScheduler::isPaused()
bool MeldInterpret::MeldInterpretScheduler::schedule(Event *ev)
References OUTPUT, Event::id, SCHEDULER_MODE_REALTIME, SCHEDULER_MODE_FASTEST, ERRPUT.
Referenced by MeldInterpret::MeldInterpretVM::tuple_send.
bool MeldInterpret::MeldInterpretScheduler::scheduleLock(Event *ev)
void MeldInterpret::MeldInterpretScheduler::SemWaitOrReadDebugMessage()
int MeldInterpret::MeldInterpretScheduler::getMode()