RobotBlocks::GenericCodeBlock
multimap<int,eventFunc> RobotBlocks::GenericCodeBlock::eventFuncMap
Referenced by addMessageEventFunc, processLocalEvent.
RobotBlocksScheduler* RobotBlocks::GenericCodeBlock::scheduler
Referenced by sendMessage, sendMessageToAllNeighbors.
RobotBlocksBlock* RobotBlocks::GenericCodeBlock::module
Referenced by sendMessageToAllNeighbors.
ConsoleStream RobotBlocks::GenericCodeBlock::console
Referenced by sendMessage, sendMessageToAllNeighbors.
RobotBlocks::GenericCodeBlock::GenericCodeBlock(RobotBlocksBlock *host)
References RobotBlocks::getScheduler, BaseSimulator::BlockCode::hostBlock, ConsoleStream::setInfo, BaseSimulator::BuildingBlock::blockId, BaseSimulator::BlockCode::addDebugAttributes.
RobotBlocks::GenericCodeBlock::~GenericCodeBlock()
References processLocalEvent, addMessageEventFunc, sendMessageToAllNeighbors, sendMessage.
void RobotBlocks::GenericCodeBlock::processLocalEvent(EventPtr pev)
References EVENT_NI_RECEIVE, eventFuncMap, OUTPUT.
Referenced by ~GenericCodeBlock.
void RobotBlocks::GenericCodeBlock::addMessageEventFunc(int type, eventFunc)
References eventFuncMap.
Referenced by ~GenericCodeBlock.
int RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors(Message *, int t0, int dt, int nexcept,...)
References module, RobotBlocks::RobotBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, scheduler, BaseSimulator::Scheduler::now, OUTPUT, BaseSimulator::BuildingBlock::blockId, Message::type, P2PNetworkInterface::hostBlock, Message::clone, BaseSimulator::Scheduler::schedule.
Referenced by ~GenericCodeBlock.
int RobotBlocks::GenericCodeBlock::sendMessage(Message *, P2PNetworkInterface *, int t0, int dt)
References scheduler, BaseSimulator::Scheduler::now, BaseSimulator::Scheduler::schedule.
Referenced by ~GenericCodeBlock.
int RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors(const char *, Message *, int t0, int dt, int nexcept,...)
References module, RobotBlocks::RobotBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, scheduler, BaseSimulator::Scheduler::now, console, P2PNetworkInterface::getConnectedBlockId, OUTPUT, BaseSimulator::BuildingBlock::blockId, Message::type, P2PNetworkInterface::hostBlock, Message::clone, BaseSimulator::Scheduler::schedule.
int RobotBlocks::GenericCodeBlock::sendMessage(const char *, Message *, P2PNetworkInterface *, int t0, int dt)
References scheduler, BaseSimulator::Scheduler::now, console, P2PNetworkInterface::getConnectedBlockId, BaseSimulator::Scheduler::schedule.
void RobotBlocks::GenericCodeBlock::setColor(const Color &c)
References RobotBlocks::RobotBlocksBlock::setColor.