Matrice
double Matrice::m[16][16]
Referenced by Matrice, operator>>, operator<<, operator*, setRotationX, setRotationY, setRotationZ, determinant, inverse, transpose, set, setGLmat, setRotation, setFromGL, glLoadMatrix, glMultMatrix, fillArray, shadowedRenderingStep3.
Matrice::Matrice()
Matrice::Matrice(const float *)
References m.
void Matrice::identity()
References operator>>, BlinkyBlocks::operator<<, operator*.
Referenced by Catoms3D::Rotations::init, Catoms3D::Catoms3DGlBlock::Catoms3DGlBlock, setRotationX, setRotationY, setRotationZ.
double Matrice::operator[](const int i)
void Matrice::setTranslation(Vecteur V)
Referenced by Catoms3D::Catoms3DBlock::setPositionAndOrientation, Catoms3D::Rotations::Rotations, Catoms3D::Rotations::nextStep, Catoms3D::Rotations::getFinalPositionAndOrientation.
void Matrice::setTranslation(double Vx, double Vy, double Vz)
void Matrice::setTranslationGL(Vecteur V)
void Matrice::setHomothetie(double hx, double hy, double hz)
References operator*, det33.
void Matrice::setRotationX(double a)
References identity, M_PI, m.
Referenced by Catoms3D::Catoms3DBlock::setPositionAndOrientation.
void Matrice::setRotationY(double a)
References identity, M_PI, m.
Referenced by Catoms2D::MotionStepEvent::consume, Catoms3D::Catoms3DBlock::setPositionAndOrientation.
void Matrice::setRotationZ(double a)
References identity, M_PI, m.
Referenced by Catoms3D::Catoms3DBlock::setPositionAndOrientation.
void Matrice::setRotation(double a, const Vecteur &V)
References M_PI, m, Vecteur::pt.
Referenced by Catoms3D::Rotations::Rotations, Catoms3D::Rotations::nextStep, Catoms3D::Rotations::getFinalPositionAndOrientation.
double Matrice::determinant() const
References m, det33.
Referenced by inverse.
void Matrice::inverse(Matrice &) const
calculate the inverse of the current matrix
result of the invertion of the current matrix
References determinant, m, det33.
Referenced by LightSource::calcMatrices, Catoms3D::Catoms3DBlock::getOrientationFromMatrix, Catoms3D::Catoms3DBlock::getInterface, Catoms3D::Rotations::Rotations, shadowedRenderingStep3.
void Matrice::transpose(Matrice &) const
References m.
void Matrice::setGLmat(const Matrice &, const Vecteur &)
References m, Vecteur::pt.
void Matrice::set(double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double)
References m.
void Matrice::setFromGL(GLfloat *mat)
References m.
void Matrice::glLoadMatrix()
References m.
void Matrice::glMultMatrix()
References m.
Referenced by Catoms3D::Catoms3DGlBlock::glDraw.
void Matrice::fillArray(GLdouble *)
References m.
Referenced by LightSource::calcMatrices.
void Matrice::fillArray(GLfloat *)
References m.
istream& operator>>(istream &f, Matrice &p)
ostream& operator<<(ostream &f, Matrice &p)
const Matrice operator*(const Matrice, const Matrice)
const Vecteur operator*(const Matrice, const Vecteur)