SmartBlocks::SmartBlocksWorld
SmartBlocksBlock** SmartBlocks::SmartBlocksWorld::tabPtrBlocks
Referenced by SmartBlocksWorld, ~SmartBlocksWorld, getPresenceMatrix, getPresenceMatrix0, isBorder, isSingle.
int SmartBlocks::SmartBlocksWorld::gridSize[2][2]
Referenced by SmartBlocksWorld, addBlock, linkBlocks, linkBlock, getPresenceMatrix, getPresenceMatrix0, isBorder, isSingle, glDraw, connectBlock.
GLfloat SmartBlocks::SmartBlocksWorld::blockSize[3][3]
Referenced by SmartBlocksWorld, glDraw, updateGlData.
Camera* SmartBlocks::SmartBlocksWorld::camera
Referenced by SmartBlocksWorld, ~SmartBlocksWorld, getCamera.
ObjLoader::ObjLoader* SmartBlocks::SmartBlocksWorld::objBlock
Referenced by SmartBlocksWorld, ~SmartBlocksWorld, glDraw, glDrawId.
ObjLoader::ObjLoader * SmartBlocks::SmartBlocksWorld::objRepere
Referenced by SmartBlocksWorld, ~SmartBlocksWorld, glDraw.
presence* SmartBlocks::SmartBlocksWorld::targetGrid
Referenced by SmartBlocksWorld, ~SmartBlocksWorld, getTargetGridPtr.
SmartBlocksCapabilities* SmartBlocks::SmartBlocksWorld::capabilities
Referenced by ~SmartBlocksWorld, getCapabilities.
int SmartBlocks::SmartBlocksWorld::tabStatsData[10][10]
Referenced by SmartBlocksWorld, addStat, printStats.
int SmartBlocks::SmartBlocksWorld::nbreStats
Referenced by SmartBlocksWorld, addStat, printStats.
GLuint SmartBlocks::SmartBlocksWorld::idTextureFloor
Referenced by SmartBlocksWorld, glDraw, loadTextures.
GLuint SmartBlocks::SmartBlocksWorld::idTextureDigits
Referenced by SmartBlocks::SmartBlocksGlBlock::glDraw, SmartBlocksWorld, loadTextures.
SmartBlocks::SmartBlocksWorld::SmartBlocksWorld(int gw, int gh, int argc, char *argv[])
References gridSize, tabPtrBlocks, blockSize, targetGrid, GlutContext::init, idTextureFloor, idTextureDigits, objBlock, objRepere, camera, M_PI, Camera::setLightParameters, Camera::setTarget, nbreStats, tabStatsData.
Referenced by createWorld.
SmartBlocks::SmartBlocksWorld::~SmartBlocksWorld()
References tabPtrBlocks, objBlock, objRepere, camera, targetGrid, capabilities.
void SmartBlocks::SmartBlocksWorld::linkBlock(int ix, int iy)
References getGridPtr, gridSize, SmartBlocks::North, SmartBlocks::South, SmartBlocks::East, SmartBlocks::West.
Referenced by linkBlocks, connectBlock.
void SmartBlocks::SmartBlocksWorld::createWorld(int gw, int gh, int argc, char *argv[])
References BaseSimulator::World::world, SmartBlocksWorld.
Referenced by SmartBlocks::createWorld.
void SmartBlocks::SmartBlocksWorld::deleteWorld()
References BaseSimulator::World::world.
Referenced by SmartBlocks::deleteWorld.
static SmartBlocksWorld* SmartBlocks::SmartBlocksWorld::getWorld()
References BaseSimulator::World::world.
Referenced by SmartBlocks::MotionStartEvent::consume, SmartBlocks::MotionStepEvent::consume, SmartBlocks::MotionStopEvent::consume, SmartBlocks::getWorld.
void SmartBlocks::SmartBlocksWorld::printInfo()
References addBlock.
void SmartBlocks::SmartBlocksWorld::addBlock(int blockId, SmartBlocksBlockCode *(*smartBlockCodeBuildingFunction)(SmartBlocksBlock *), const Vecteur &pos, const Color &col)
References BaseSimulator::World::buildingBlocksMap, BaseSimulator::BuildingBlock::blockId, SmartBlocks::getScheduler, BaseSimulator::Scheduler::schedule, BaseSimulator::World::tabGlBlocks, SmartBlocks::SmartBlocksBlock::setGlBlock, SmartBlocks::SmartBlocksBlock::setPosition, SmartBlocks::SmartBlocksBlock::setColor, SmartBlocks::SmartBlocksBlock::getGridPosition, gridSize, setGridPtr.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, printInfo.
void SmartBlocks::SmartBlocksWorld::setBlocksSize(float *siz)
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
presence* SmartBlocks::SmartBlocksWorld::getTargetGridPtr(int *gs)
References targetGrid.
presence SmartBlocks::SmartBlocksWorld::getTargetGrid(int ix, int iy)
void SmartBlocks::SmartBlocksWorld::setTargetGrid(presence value, int ix, int iy)
References initTargetGrid.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void SmartBlocks::SmartBlocksWorld::initTargetGrid()
Referenced by setTargetGrid.
SmartBlocksBlock* SmartBlocks::SmartBlocksWorld::getGridPtr(int x, int y)
Referenced by linkBlock.
void SmartBlocks::SmartBlocksWorld::setGridPtr(int x, int y, SmartBlocksBlock *ptr)
Referenced by SmartBlocks::MotionStopEvent::consume, addBlock, connectBlock, disconnectBlock.
void SmartBlocks::SmartBlocksWorld::setCapabilities(SmartBlocksCapabilities *capa)
References getPresenceMatrix0, getPresenceMatrix.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void SmartBlocks::SmartBlocksWorld::getPresenceMatrix0(const PointCel &pos, PresenceMatrix &pm)
References SmartBlocks::PresenceMatrix::grid, SmartBlocks::wallCell, SmartBlocks::PointCel::x, gridSize, SmartBlocks::PointCel::y, tabPtrBlocks, SmartBlocks::fullCell, SmartBlocks::emptyCell.
Referenced by setCapabilities.
void SmartBlocks::SmartBlocksWorld::getPresenceMatrix(const PointCel &pos, PresenceMatrix &pm)
References SmartBlocks::PresenceMatrix::grid, SmartBlocks::wallCell, SmartBlocks::PointCel::x, gridSize, SmartBlocks::PointCel::y, tabPtrBlocks, isBorder, isSingle, SmartBlocks::singleCell, SmartBlocks::borderCell, SmartBlocks::fullCell, SmartBlocks::emptyCell.
Referenced by setCapabilities.
SmartBlocksCapabilities* SmartBlocks::SmartBlocksWorld::getCapabilities()
References capabilities, linkBlocks, loadTextures, glDraw, glDrawId, updateGlData.
void SmartBlocks::SmartBlocksWorld::linkBlocks()
References gridSize, linkBlock.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, getCapabilities.
void SmartBlocks::SmartBlocksWorld::loadTextures(const string &str)
References idTextureFloor, GlutWindow::loadTexture, idTextureDigits.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, getCapabilities.
void SmartBlocks::SmartBlocksWorld::glDraw()
References idTextureFloor, gridSize, blockSize, objRepere, ObjLoader::ObjLoader::glDraw, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by getCapabilities.
void SmartBlocks::SmartBlocksWorld::glDrawId()
References BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by getCapabilities.
void SmartBlocks::SmartBlocksWorld::updateGlData(SmartBlocksBlock *blc)
References SmartBlocks::SmartBlocksBlock::getGlBlock, BaseSimulator::World::lock, blockSize, SmartBlocks::SmartBlocksBlock::position, GlBlock::setPosition, GlBlock::setColor, SmartBlocks::SmartBlocksBlock::color, BaseSimulator::World::unlock.
Referenced by SmartBlocks::SmartBlocksBlock::setPosition, SmartBlocks::SmartBlocksBlock::setColor, SmartBlocks::MotionStepEvent::consume, SmartBlocks::MotionStopEvent::consume, getCapabilities.
virtual Camera* SmartBlocks::SmartBlocksWorld::getCamera()
References camera, disconnectBlock, connectBlock.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void SmartBlocks::SmartBlocksWorld::disconnectBlock(SmartBlocksBlock *block)
References SmartBlocks::SmartBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, SmartBlocks::SmartBlocksBlock::position, Vecteur::pt, setGridPtr.
Referenced by SmartBlocks::MotionStartEvent::consume, getCamera.
void SmartBlocks::SmartBlocksWorld::connectBlock(SmartBlocksBlock *block)
References SmartBlocks::SmartBlocksBlock::position, Vecteur::pt, setGridPtr, linkBlock, gridSize.
Referenced by SmartBlocks::MotionStopEvent::consume, getCamera.
void SmartBlocks::SmartBlocksWorld::getGridSize(int &lx, int &ly)
References isBorder, isSingle, nbreWellPlacedBlock, createStats, addStat, printStats.
bool SmartBlocks::SmartBlocksWorld::isBorder(int x, int y)
References tabPtrBlocks, gridSize.
Referenced by getPresenceMatrix, getGridSize.
bool SmartBlocks::SmartBlocksWorld::isSingle(int x, int y)
References tabPtrBlocks, gridSize.
Referenced by getPresenceMatrix, getGridSize.
int SmartBlocks::SmartBlocksWorld::nbreWellPlacedBlock()
References BaseSimulator::World::buildingBlocksMap, SmartBlocks::SmartBlocksBlock::wellPlaced.
Referenced by printStats, getGridSize.
void SmartBlocks::SmartBlocksWorld::createStats(int)
Referenced by getGridSize.
void SmartBlocks::SmartBlocksWorld::addStat(int n, int v)
References tabStatsData, nbreStats.
Referenced by getGridSize.
void SmartBlocks::SmartBlocksWorld::printStats()
References OUTPUT, nbreWellPlacedBlock, nbreStats, tabStatsData, SmartBlocks::getScheduler, BaseSimulator::Scheduler::getNbreMessages.
Referenced by getGridSize.