MeldInterpret::MeldInterpretVM
NodeID MeldInterpret::MeldInterpretVM::blockId
Register MeldInterpret::MeldInterpretVM::reg[32][32]
int MeldInterpret::MeldInterpretVM::numNeighbors
int MeldInterpret::MeldInterpretVM::waiting
bool MeldInterpret::MeldInterpretVM::firstStart
bool MeldInterpret::MeldInterpretVM::debugging
bool MeldInterpret::MeldInterpretVM::configured
map< int, MeldInterpretVM * > MeldInterpret::MeldInterpretVM::vmMap
Referenced by MeldInterpretVM, equilibrium.
const unsigned char * MeldInterpret::MeldInterpretVM::meld_prog
Referenced by readProgram, tuple_do_handle.
char ** MeldInterpret::MeldInterpretVM::tuple_names
Referenced by readProgram, moveTupleToReg, execute_alloc, execute_addtuple, execute_update, execute_iter, execute_run_action0, execute_remove, tuple_do_handle, process_bytecode, facts_dump, print_program_info, databaseConsistencyChecker.
char ** MeldInterpret::MeldInterpretVM::rule_names
Referenced by process_bytecode.
unsigned char * MeldInterpret::MeldInterpretVM::arguments
Referenced by init_fields.
uint64_t MeldInterpret::MeldInterpretVM::currentLocalDate
Referenced by MeldInterpretVM.
bool MeldInterpret::MeldInterpretVM::hasWork
Referenced by MeldInterpretVM, equilibrium.
bool MeldInterpret::MeldInterpretVM::polling
Referenced by MeldInterpretVM.
bool MeldInterpret::MeldInterpretVM::deterministicSet
Referenced by MeldInterpretVM.
NodeID MeldInterpret::MeldInterpretVM::neighbors[6][6]
Referenced by processOneRule.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_INIT
Referenced by MeldInterpretVM, enqueue_init.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_EDGE
Referenced by MeldInterpretVM, init_consts.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_TERMINATE
Referenced by MeldInterpretVM, init_consts, tuple_do_handle.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_NEIGHBORCOUNT
Referenced by MeldInterpretVM, enqueue_count, init_all_consts, databaseConsistencyChecker.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_NEIGHBOR
Referenced by MeldInterpretVM, enqueue_face, init_all_consts, databaseConsistencyChecker.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_VACANT
Referenced by MeldInterpretVM, enqueue_face, init_all_consts, databaseConsistencyChecker.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_TAP
Referenced by MeldInterpretVM, enqueue_tap, init_all_consts.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_SETCOLOR
Referenced by MeldInterpretVM, init_all_consts, execute_run_action0.
tuple_type MeldInterpret::MeldInterpretVM::TYPE_SETCOLOR2
Referenced by MeldInterpretVM, init_all_consts, execute_run_action0.
BlinkyBlocks::BlinkyBlocksBlock* MeldInterpret::MeldInterpretVM::host
Referenced by MeldInterpretVM, myGetTime, tuple_send, down, up, north, south, east, west, setLED, equilibrium, execute_iter.
extern_funct_type* MeldInterpret::MeldInterpretVM::extern_functs
int* MeldInterpret::MeldInterpretVM::extern_functs_args
tuple_pqueue* MeldInterpret::MeldInterpretVM::delayedTuples
Referenced by ~MeldInterpretVM, processOneRule, tuple_send, vm_alloc.
tuple_queue* MeldInterpret::MeldInterpretVM::tuples
Referenced by ~MeldInterpretVM, vm_alloc.
tuple_pqueue* MeldInterpret::MeldInterpretVM::newStratTuples
Referenced by ~MeldInterpretVM, print_newStratTuples, enqueueNewTuple, processOneRule, vm_alloc.
tuple_queue* MeldInterpret::MeldInterpretVM::newTuples
Referenced by ~MeldInterpretVM, print_newTuples, enqueueNewTuple, processOneRule, vm_alloc.
tuple_queue MeldInterpret::MeldInterpretVM::receivedTuples[NUM_PORTS][NUM_PORTS]
Referenced by processOneRule, receive_tuple, vm_alloc.
MeldInterpret::MeldInterpretVM::MeldInterpretVM(BlinkyBlocks::BlinkyBlocksBlock *b)
References TYPE_INIT, TYPE_EDGE, TYPE_TERMINATE, TYPE_NEIGHBORCOUNT, TYPE_NEIGHBOR, TYPE_VACANT, TYPE_TAP, TYPE_SETCOLOR, TYPE_SETCOLOR2, OUTPUT, vm_alloc, vm_init, host, BaseSimulator::BuildingBlock::blockId, hasWork, polling, deterministicSet, currentLocalDate, enqueue_init, getNeighborCount, enqueue_count, vmMap.
MeldInterpret::MeldInterpretVM::~MeldInterpretVM()
References delayedTuples, tuples, newStratTuples, newTuples.
void MeldInterpret::MeldInterpretVM::processOneRule()
References queue_is_empty, newTuples, queue_dequeue, tuple_handle, p_empty, delayedTuples, p_peek, myGetTime, p_dequeue, tuple_send, _tuple_pentry::tuple, _tuple_pentry::rt, _tuple_pentry::records, record_type::count, newStratTuples, NUM_RULES, updateRuleState, PROCESS_RULE, RULE_ISPERSISTENT, process_bytecode, RULE_START, NOT_LINEAR, getNeighborCount, enqueue_count, NUM_PORTS, get_neighbor_ID, neighbors, enqueue_face, receivedTuples, tuple_print, enqueueNewTuple.
bool MeldInterpret::MeldInterpretVM::isWaiting()
byte MeldInterpret::MeldInterpretVM::updateRuleState(byte rid)
References RULE_NUM_INCLPREDS, TUPLES, RULE_INCLPRED_ID, INACTIVE_RULE, ACTIVE_RULE.
Referenced by processOneRule.
Time MeldInterpret::MeldInterpretVM::myGetTime()
References host, BaseSimulator::BuildingBlock::getTime.
Referenced by processOneRule, tuple_send.
void MeldInterpret::MeldInterpretVM::__myassert(string file, int line, string exp)
References printDebug, OUTPUT.
NodeID MeldInterpret::MeldInterpretVM::get_neighbor_ID(int face)
References UP, up, DOWN, down, WEST, west, EAST, east, NORTH, north, SOUTH, south, myassert.
Referenced by processOneRule, tuple_send, getNeighborCount.
void MeldInterpret::MeldInterpretVM::enqueueNewTuple(tuple_t tuple, record_type isNew)
References myassert, TUPLE_TYPE, NUM_TYPES, TYPE_IS_STRATIFIED, p_enqueue, newStratTuples, TYPE_STRATIFICATION_ROUND, queue_enqueue, newTuples.
Referenced by enqueue_face, enqueue_count, enqueue_tap, enqueue_init, processOneRule, receive_tuple, tuple_send, execute_addtuple.
void MeldInterpret::MeldInterpretVM::enqueue_face(NodeID neighbor, meld_int face, int isNew)
References TYPE_VACANT, tuple_alloc, SET_TUPLE_FIELD, TYPE_NEIGHBOR, enqueueNewTuple.
Referenced by processOneRule.
void MeldInterpret::MeldInterpretVM::enqueue_count(meld_int count, int isNew)
References TYPE_NEIGHBORCOUNT, tuple_alloc, SET_TUPLE_FIELD, enqueueNewTuple.
Referenced by MeldInterpretVM, processOneRule.
void MeldInterpret::MeldInterpretVM::enqueue_tap()
References TYPE_TAP, tuple_alloc, enqueueNewTuple.
void MeldInterpret::MeldInterpretVM::enqueue_init()
References TYPE_INIT, tuple_alloc, enqueueNewTuple.
Referenced by MeldInterpretVM.
void MeldInterpret::MeldInterpretVM::init_all_consts()
References init_consts, NUM_TYPES, TYPE_NAME, TYPE_TAP, TYPE_NEIGHBOR, TYPE_NEIGHBORCOUNT, TYPE_VACANT, TYPE_SETCOLOR, TYPE_SETCOLOR2.
Referenced by vm_init.
void MeldInterpret::MeldInterpretVM::userRegistration()
void MeldInterpret::MeldInterpretVM::receive_tuple(int isNew, tuple_t tpl, byte face)
References TUPLE_TYPE, TYPE_SIZE, tuple_print, TYPE_IS_LINEAR, TYPE_IS_ACTION, receivedTuples, queue_enqueue, _tuple_queue::head, _tuple_entry::next, FREE_TUPLE, queue_dequeue_pos, enqueueNewTuple.
void MeldInterpret::MeldInterpretVM::free_chunk()
void MeldInterpret::MeldInterpretVM::tuple_send(tuple_t tuple, NodeID rt, meld_int delay, int isNew)
References myassert, TUPLE_TYPE, NUM_TYPES, p_enqueue, delayedTuples, myGetTime, enqueueNewTuple, up, UP, down, DOWN, west, WEST, east, EAST, north, NORTH, south, SOUTH, TYPE_SIZE, host, BaseSimulator::BuildingBlock::getP2PNetworkInterfaceByDestBlockId, get_neighbor_ID, P2PNetworkInterface::connectedInterface, MeldInterpret::getScheduler, MeldInterpret::MeldInterpretScheduler::schedule.
Referenced by processOneRule, execute_send, execute_send_delay.
void MeldInterpret::MeldInterpretVM::tuple_handle(tuple_t tuple, int isNew, Register *registers)
References TUPLE_TYPE, myassert, NUM_TYPES, tuple_do_handle.
Referenced by processOneRule, execute_remove.
void MeldInterpret::MeldInterpretVM::vm_init()
References init_all_consts, init_fields.
Referenced by MeldInterpretVM.
void MeldInterpret::MeldInterpretVM::vm_alloc()
References tuples, NUM_TYPES, newTuples, newStratTuples, delayedTuples, myassert, receivedTuples, NUM_PORTS.
Referenced by MeldInterpretVM.
byte MeldInterpret::MeldInterpretVM::getNeighborCount()
References NUM_PORTS, get_neighbor_ID, VACANT.
Referenced by MeldInterpretVM, processOneRule.
Uid MeldInterpret::MeldInterpretVM::down(void)
References host, BlinkyBlocks::BlinkyBlocksBlock::getInterface, DOWN, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by get_neighbor_ID, tuple_send.
Uid MeldInterpret::MeldInterpretVM::up(void)
References host, BlinkyBlocks::BlinkyBlocksBlock::getInterface, UP, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by get_neighbor_ID, tuple_send.
Uid MeldInterpret::MeldInterpretVM::north(void)
References host, BlinkyBlocks::BlinkyBlocksBlock::getInterface, NORTH, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by get_neighbor_ID, tuple_send.
Uid MeldInterpret::MeldInterpretVM::south(void)
References host, BlinkyBlocks::BlinkyBlocksBlock::getInterface, SOUTH, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by get_neighbor_ID, tuple_send.
Uid MeldInterpret::MeldInterpretVM::east(void)
References host, BlinkyBlocks::BlinkyBlocksBlock::getInterface, EAST, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by get_neighbor_ID, tuple_send.
Uid MeldInterpret::MeldInterpretVM::west(void)
References host, BlinkyBlocks::BlinkyBlocksBlock::getInterface, WEST, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by get_neighbor_ID, tuple_send.
void MeldInterpret::MeldInterpretVM::setColor(byte color)
References setLED, Colors.
void MeldInterpret::MeldInterpretVM::setColor(Color color)
References setLED.
void MeldInterpret::MeldInterpretVM::setLED(byte r, byte g, byte b, byte intensity)
References BaseSimulator::getScheduler, BaseSimulator::Scheduler::schedule, host.
Referenced by setColor.
void MeldInterpret::MeldInterpretVM::setColorWrapper(byte color)
Referenced by execute_run_action0.
void MeldInterpret::MeldInterpretVM::setLEDWrapper(byte r, byte g, byte b, byte intensity)
Referenced by execute_run_action0.
NodeID MeldInterpret::MeldInterpretVM::getGUID()
void MeldInterpret::MeldInterpretVM::print_newTuples()
References newTuples, _tuple_queue::head, _tuple_entry::next, tuple_print, _tuple_entry::tuple, _tuple_entry::records, record_type::count.
void MeldInterpret::MeldInterpretVM::print_newStratTuples()
References newStratTuples, tuple_pqueue::queue, _tuple_pentry::next, tuple_print, _tuple_pentry::tuple, _tuple_pentry::records, record_type::count.
void MeldInterpret::MeldInterpretVM::printDebug(string str)
References OUTPUT.
Referenced by __myassert, tuple_do_handle, tuple_print, facts_dump, print_program_info.
NodeID MeldInterpret::MeldInterpretVM::getBlockId()
Referenced by moveTupleToReg, execute_alloc, execute_addtuple, execute_update, execute_send, execute_call1, execute_send_delay, execute_iter, execute_run_action0, execute_remove, execute_mvintfield, execute_mvintreg, execute_mvfloatreg, execute_mvfloatfield, execute_mvfieldreg, execute_mvregfield, execute_mvfieldfield, execute_mvhostfield, execute_mvhostreg, execute_mvregreg, execute_not, execute_boolor, execute_boolequal, execute_boolnotequal, execute_addrequal, execute_addrnotequal, execute_intequal, execute_intnotequal, execute_intgreater, execute_intgreaterequal, execute_intlesser, execute_intlesserequal, execute_intmul, execute_intdiv, execute_intmod, execute_intplus, execute_intminus, execute_floatplus, execute_floatminus, execute_floatmul, execute_floatdiv, execute_floatequal, execute_floatnotequal, execute_floatlesser, execute_floatlesserequal, execute_floatgreater, execute_floatgreaterequal, tuple_do_handle, process_bytecode, tuple_print, databaseConsistencyChecker.
tuple_t MeldInterpret::MeldInterpretVM::tuple_alloc(tuple_type type)
References NUM_TYPES, ALLOC_TUPLE, TYPE_SIZE, TUPLE_TYPE.
Referenced by enqueue_face, enqueue_count, enqueue_tap, enqueue_init.
void MeldInterpret::MeldInterpretVM::tuple_do_handle(tuple_type type, void *tuple, int isNew, Register *reg)
References TYPE_TERMINATE, FREE_TUPLE, TERMINATE_CURRENT, getBlockId, tuple_print, TYPE_IS_ACTION, execute_run_action0, TYPE_IS_AGG, TYPE_IS_LINEAR, TUPLES, _tuple_queue::head, _tuple_entry::next, _tuple_entry::tuple, TYPE_SIZE, _tuple_entry::records, record_type::count, process_bytecode, TYPE_START, TUPLE_TYPE, NOT_LINEAR, PROCESS_TUPLE, tuple_names, queue_dequeue_pos, queue_enqueue, TYPE_AGGREGATE, AGG_FIELD, TYPE_FIELD_SIZE, TYPE_ARG_OFFSET, TYPE_ARG_SIZE, record_type::agg_queue, AGG_AGG, AGG_FIRST, queue_is_empty, aggregate_free, aggregate_recalc, ALLOC_TUPLE, queue_init, meld_prog, printDebug, RETURN_INSTR, NEXT_INSTR, PERS_ITER_INSTR, LINEAR_ITER_INSTR, NOT_INSTR, SEND_INSTR, RULE_INSTR, RULE_DONE_INSTR, SEND_DELAY_INSTR, RETURN_LINEAR_INSTR, RETURN_DERIVED_INSTR, MVINTFIELD_INSTR, MVFIELDFIELD_INSTR, MVFIELDREG_INSTR, MVPTRREG_INSTR, MVREGFIELD_INSTR, MVHOSTFIELD_INSTR, MVFLOATFIELD_INSTR, MVFLOATREG_INSTR, MVHOSTREG_INSTR, ADDRNOTEQUAL_INSTR, ADDREQUAL_INSTR, INTMINUS_INSTR, INTEQUAL_INSTR, INTNOTEQUAL_INSTR, INTPLUS_INSTR, INTLESSER_INSTR, INTGREATEREQUAL_INSTR, ALLOC_INSTR, BOOLOR_INSTR, INTLESSEREQUAL_INSTR, INTGREATER_INSTR, INTMUL_INSTR, INTDIV_INSTR, FLOATPLUS_INSTR, FLOATMINUS_INSTR, FLOATMUL_INSTR, FLOATDIV_INSTR, FLOATEQUAL_INSTR, FLOATNOTEQUAL_INSTR, FLOATLESSER_INSTR, FLOATLESSEREQUAL_INSTR, FLOATGREATER_INSTR, FLOATGREATEREQUAL_INSTR, MVREGREG_INSTR, BOOLEQUAL_INSTR, BOOLNOTEQUAL_INSTR, IF_INSTR, CALL1_INSTR, ADDLINEAR_INSTR, ADDPERS_INSTR, RUNACTION_INSTR, UPDATE_INSTR, REMOVE_INSTR, IF_ELSE_INSTR, JUMP_INSTR, INTMOD_INSTR.
Referenced by tuple_handle.
void MeldInterpret::MeldInterpretVM::tuple_print(tuple_t tuple, FILE *fp)
References TUPLE_TYPE, MAX_STRING_SIZE, getBlockId, TYPE_NAME, TYPE_NUMARGS, GET_TUPLE_FIELD, TYPE_ARG_TYPE, FIELD_INT, MELD_INT, FIELD_FLOAT, MELD_FLOAT, FIELD_ADDR, FIELD_LIST_INT, FIELD_LIST_FLOAT, FIELD_LIST_ADDR, FIELD_SET_INT, FIELD_SET_FLOAT, myassert, FIELD_TYPE, FIELD_BOOL, MELD_BOOL, printDebug.
Referenced by print_newTuples, print_newStratTuples, processOneRule, receive_tuple, tuple_do_handle, facts_dump.
void MeldInterpret::MeldInterpretVM::tuple_dump(void *tuple)
int MeldInterpret::MeldInterpretVM::process_bytecode(tuple_t tuple, const unsigned char *pc, int isNew, int isLinear, Register *reg, byte state)
References PROCESS_TYPE, PROCESS_TUPLE, getBlockId, tuple_names, TUPLE_TYPE, PROCESS_ITER, PROCESS_RULE, RULE_ISPERSISTENT, RULE_NUMBER, rule_names, moveTupleToReg, RETURN_INSTR, RET_RET, NEXT_INSTR, RET_NEXT, PERS_ITER_INSTR, ITER_OUTER_JUMP, execute_iter, DECIDE_NEXT_ITER, LINEAR_ITER_INSTR, NOT_INSTR, NOT_BASE, execute_not, SEND_INSTR, SEND_BASE, execute_send, RESET_LINEAR_INSTR, RESET_LINEAR_BASE, NOT_LINEAR, RESET_LINEAR_JUMP, END_LINEAR_INSTR, RET_LINEAR, RULE_INSTR, RULE_BASE, FETCH, RULE_DONE_INSTR, RULE_DONE_BASE, SEND_DELAY_INSTR, SEND_DELAY_BASE, execute_send_delay, RETURN_LINEAR_INSTR, RETURN_DERIVED_INSTR, RET_DERIVED, MVINTFIELD_INSTR, MVINTFIELD_BASE, execute_mvintfield, MVINTREG_INSTR, MVINTREG_BASE, execute_mvintreg, MVFIELDFIELD_INSTR, MVFIELDFIELD_BASE, execute_mvfieldfield, MVFIELDREG_INSTR, MVFIELDREG_BASE, execute_mvfieldreg, MVPTRREG_INSTR, MVPTRREG_BASE, MVFIELDFIELDR_INSTR, MVREGFIELD_INSTR, MVREGFIELD_BASE, execute_mvregfield, MVHOSTFIELD_INSTR, MVHOSTFIELD_BASE, execute_mvhostfield, MVFLOATFIELD_INSTR, MVFLOATFIELD_BASE, execute_mvfloatfield, MVFLOATREG_INSTR, MVFLOATREG_BASE, execute_mvfloatreg, MVHOSTREG_INSTR, MVHOSTREG_BASE, execute_mvhostreg, ADDRNOTEQUAL_INSTR, OP_BASE, execute_addrnotequal, ADDREQUAL_INSTR, execute_addrequal, INTMINUS_INSTR, execute_intminus, INTEQUAL_INSTR, execute_intequal, INTNOTEQUAL_INSTR, execute_intnotequal, INTPLUS_INSTR, execute_intplus, INTLESSER_INSTR, execute_intlesser, INTGREATEREQUAL_INSTR, execute_intgreaterequal, ALLOC_INSTR, ALLOC_BASE, execute_alloc, BOOLOR_INSTR, execute_boolor, INTLESSEREQUAL_INSTR, execute_intlesserequal, INTGREATER_INSTR, execute_intgreater, INTMUL_INSTR, execute_intmul, INTDIV_INSTR, execute_intdiv, FLOATPLUS_INSTR, execute_floatplus, FLOATMINUS_INSTR, execute_floatminus, FLOATMUL_INSTR, execute_floatmul, FLOATDIV_INSTR, execute_floatdiv, FLOATEQUAL_INSTR, execute_floatequal, FLOATNOTEQUAL_INSTR, execute_floatnotequal, FLOATLESSER_INSTR, execute_floatlesser, FLOATLESSEREQUAL_INSTR, execute_floatlesserequal, FLOATGREATER_INSTR, execute_floatgreater, FLOATGREATEREQUAL_INSTR, execute_floatgreaterequal, MVREGREG_INSTR, MVREGREG_BASE, execute_mvregreg, BOOLEQUAL_INSTR, execute_boolequal, BOOLNOTEQUAL_INSTR, execute_boolnotequal, IF_INSTR, IF_BASE, eval_reg, IF_JUMP, CALL1_INSTR, CALL1_BASE, execute_call1, ADDLINEAR_INSTR, ADDLINEAR_BASE, execute_addtuple, ADDPERS_INSTR, ADDPERS_BASE, RUNACTION_INSTR, RUNACTION_BASE, execute_run_action, UPDATE_INSTR, UPDATE_BASE, execute_update, REMOVE_INSTR, REMOVE_BASE, execute_remove, IF_ELSE_INSTR, IF_ELSE_BASE, JUMP_INSTR, JUMP_BASE, INTMOD_INSTR, execute_intmod.
Referenced by processOneRule, execute_iter, aggregate_recalc, tuple_do_handle.
void MeldInterpret::MeldInterpretVM::init_fields(void)
References NUM_TYPES, TYPE_NUMARGS, arguments, TYPE_ARG_TYPE, FIELD_INT, FIELD_TYPE, FIELD_FLOAT, FIELD_BOOL, FIELD_ADDR, FIELD_LIST_INT, FIELD_LIST_FLOAT, FIELD_LIST_ADDR, FIELD_SET_INT, FIELD_SET_FLOAT, FIELD_STRING, myassert, TYPE_FIELD_SIZE.
Referenced by vm_init.
void MeldInterpret::MeldInterpretVM::init_consts(void)
References NUM_TYPES, TYPE_NAME, TYPE_EDGE, TYPE_TERMINATE.
Referenced by init_all_consts.
void MeldInterpret::MeldInterpretVM::facts_dump(void)
References MAX_STRING_SIZE, NUM_TYPES, TUPLES, tuple_names, TYPE_SIZE, printDebug, _tuple_entry::next, tuple_print, _tuple_entry::tuple, TYPE_IS_AGG, _tuple_entry::records, record_type::agg_queue, _tuple_queue::head, record_type::count.
void MeldInterpret::MeldInterpretVM::print_program_info(void)
References MAX_STRING_SIZE, NUM_TYPES, tuple_names, TYPE_SIZE, TYPE_IS_AGG, TYPE_IS_LINEAR, TYPE_IS_ROUTING, TYPE_NUMARGS, TYPE_OFFSET, TYPE_ARG_OFFSET, TYPE_ARG_SIZE, printDebug.
char* MeldInterpret::MeldInterpretVM::arg2String(tuple_t tuple, byte index)
byte MeldInterpret::MeldInterpretVM::val_is_float(const byte x)
Referenced by execute_iter.
byte MeldInterpret::MeldInterpretVM::val_is_int(const byte x)
Referenced by execute_iter.
byte MeldInterpret::MeldInterpretVM::val_is_field(const byte x)
Referenced by execute_iter.
void * MeldInterpret::MeldInterpretVM::eval_field(tuple_t tuple, const unsigned char **pc)
References VAL_FIELD_NUM, GET_TUPLE_FIELD.
Referenced by execute_iter, execute_mvintfield, execute_mvfloatfield, execute_mvfieldreg, execute_mvregfield, execute_mvfieldfield, execute_mvhostfield.
int MeldInterpret::MeldInterpretVM::execute_iter(const unsigned char *pc, Register *reg, int isNew, int isLinear)
References ITER_INNER_JUMP, ITER_TYPE, FETCH, TUPLES, queue_length, host, BaseSimulator::BuildingBlock::getNextRandomNumber, _tuple_entry::tuple, _tuple_entry::next, getBlockId, tuple_names, RET_NO_RET, ITER_NUM_ARGS, PERS_ITER_BASE, ITER_MATCH_FIELD, TYPE_ARG_TYPE, TYPE_ARG_SIZE, ITER_MATCH_VAL, GET_TUPLE_FIELD, val_is_int, eval_int, val_is_float, eval_float, val_is_field, eval_field, myassert, moveTupleToReg, process_bytecode, TYPE_IS_LINEAR, TUPLE_TYPE, PROCESS_ITER, RET_LINEAR, RET_DERIVED, RET_RET.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_run_action(const unsigned char *pc, Register *reg, int isNew)
References FETCH, TUPLE_TYPE, execute_run_action0.
Referenced by process_bytecode.
void * MeldInterpret::MeldInterpretVM::eval_reg(const unsigned char value, const unsigned char **pc, Register *reg)
References VAL_REG.
Referenced by execute_alloc, execute_call1, execute_mvintreg, execute_mvfloatreg, execute_mvfieldreg, execute_mvregfield, execute_mvhostreg, execute_mvregreg, execute_not, execute_boolor, execute_boolequal, execute_boolnotequal, execute_addrequal, execute_addrnotequal, execute_intequal, execute_intnotequal, execute_intgreater, execute_intgreaterequal, execute_intlesser, execute_intlesserequal, execute_intmul, execute_intdiv, execute_intmod, execute_intplus, execute_intminus, execute_floatplus, execute_floatminus, execute_floatmul, execute_floatdiv, execute_floatequal, execute_floatnotequal, execute_floatlesser, execute_floatlesserequal, execute_floatgreater, execute_floatgreaterequal, process_bytecode.
void * MeldInterpret::MeldInterpretVM::eval_int(const unsigned char **pc)
Referenced by execute_send_delay, execute_iter, execute_mvintfield, execute_mvintreg.
void * MeldInterpret::MeldInterpretVM::eval_float(const unsigned char **pc)
Referenced by execute_iter, execute_mvfloatreg, execute_mvfloatfield.
void MeldInterpret::MeldInterpretVM::moveTupleToReg(const unsigned char reg_index, tuple_t tuple, Register *reg)
References VAL_REG, getBlockId, tuple_names, TUPLE_TYPE.
Referenced by execute_iter, process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_addtuple(const unsigned char *pc, Register *reg, int isNew)
References FETCH, TUPLE_TYPE, getBlockId, tuple_names, enqueueNewTuple, MELD_CONVERT_REG_TO_PTR.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_send_delay(const unsigned char *pc, Register *reg, int isNew)
References SEND_MSG, SEND_RT, eval_int, getBlockId, tuple_send, MELD_CONVERT_REG_TO_PTR.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_alloc(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, ALLOC_TUPLE, TYPE_SIZE, getBlockId, tuple_names, TUPLE_TYPE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_update(const unsigned char *pc, Register *reg)
References FETCH, TUPLE_TYPE, getBlockId, tuple_names.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_send(const unsigned char *pc, Register *reg, int isNew)
References SEND_MSG, SEND_RT, getBlockId, tuple_send, MELD_CONVERT_REG_TO_PTR.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_call1(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, NODE2INT_FUNC, getBlockId, MELD_NODE_ID.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_run_action0(tuple_t action_tuple, tuple_type type, int isNew)
References TYPE_SETCOLOR, getBlockId, tuple_names, MELD_INT, GET_TUPLE_FIELD, setLEDWrapper, FREE_TUPLE, TYPE_SETCOLOR2, setColorWrapper.
Referenced by execute_run_action, tuple_do_handle.
void MeldInterpret::MeldInterpretVM::execute_remove(const unsigned char *pc, Register *reg, int isNew)
References REMOVE_REG, TUPLE_TYPE, MELD_CONVERT_REG_TO_PTR, TYPE_SIZE, getBlockId, tuple_names, tuple_handle.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvintfield(const unsigned char *pc, Register *reg)
References eval_int, FETCH, TUPLE_TYPE, eval_field, getBlockId, MELD_INT, TYPE_ARG_SIZE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvintreg(const unsigned char *pc, Register *reg)
References eval_int, FETCH, eval_reg, getBlockId, MELD_INT.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvfloatreg(const unsigned char *pc, Register *reg)
References eval_float, FETCH, eval_reg, getBlockId, MELD_FLOAT.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvfloatfield(const unsigned char *pc, Register *reg)
References eval_float, FETCH, TUPLE_TYPE, eval_field, getBlockId, MELD_FLOAT, TYPE_ARG_SIZE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvfieldreg(const unsigned char *pc, Register *reg)
References FETCH, eval_field, eval_reg, getBlockId, TYPE_ARG_SIZE, TUPLE_TYPE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvfieldfield(const unsigned char *pc, Register *reg)
References FETCH, eval_field, TUPLE_TYPE, getBlockId, TYPE_ARG_SIZE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvregfield(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, TUPLE_TYPE, eval_field, getBlockId, TYPE_ARG_SIZE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvhostfield(const unsigned char *pc, Register *reg)
References EVAL_HOST, FETCH, TUPLE_TYPE, eval_field, getBlockId, TYPE_ARG_SIZE.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvhostreg(const unsigned char *pc, Register *reg)
References EVAL_HOST, FETCH, eval_reg, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_mvregreg(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_not(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_BOOL, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_boolor(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_BOOL, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_boolequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_BOOL, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_boolnotequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_BOOL, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_addrequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_NODE_ID, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_addrnotequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_NODE_ID, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intnotequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intgreater(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intgreaterequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intlesser(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intlesserequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intmul(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intdiv(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intmod(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intplus(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_intminus(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_INT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatplus(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatminus(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatmul(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatdiv(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatnotequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatlesser(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatlesserequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatgreater(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
void MeldInterpret::MeldInterpretVM::execute_floatgreaterequal(const unsigned char *pc, Register *reg)
References FETCH, eval_reg, MELD_FLOAT, getBlockId.
Referenced by process_bytecode.
bool MeldInterpret::MeldInterpretVM::aggregate_accumulate(int agg_type, void *acc, void *obj, int count)
References AGG_SET_UNION_INT, AGG_SET_UNION_FLOAT, myassert, AGG_FIRST, AGG_MAX_INT, MELD_INT, AGG_MIN_INT, AGG_SUM_INT, AGG_MAX_FLOAT, MELD_FLOAT, AGG_MIN_FLOAT, AGG_SUM_FLOAT, AGG_SUM_LIST_INT, AGG_SUM_LIST_FLOAT.
Referenced by aggregate_recalc.
bool MeldInterpret::MeldInterpretVM::aggregate_changed(int agg_type, void *v1, void *v2)
References AGG_FIRST, AGG_MIN_INT, AGG_MAX_INT, AGG_SUM_INT, MELD_INT, AGG_MIN_FLOAT, AGG_MAX_FLOAT, AGG_SUM_FLOAT, MELD_FLOAT, AGG_SET_UNION_INT, AGG_SET_UNION_FLOAT, AGG_SUM_LIST_INT, AGG_SUM_LIST_FLOAT, myassert.
Referenced by aggregate_recalc.
void MeldInterpret::MeldInterpretVM::aggregate_seed(int agg_type, void *acc, void *start, int count, size_t size)
References AGG_FIRST, AGG_MIN_INT, AGG_MAX_INT, MELD_INT, AGG_SUM_INT, AGG_MIN_FLOAT, AGG_MAX_FLOAT, MELD_FLOAT, AGG_SUM_FLOAT, AGG_SET_UNION_INT, AGG_SET_UNION_FLOAT, AGG_SUM_LIST_INT, AGG_SUM_LIST_FLOAT, myassert.
Referenced by aggregate_recalc.
void MeldInterpret::MeldInterpretVM::aggregate_free(tuple_t tuple, unsigned char field_aggregate, unsigned char type_aggregate)
References AGG_FIRST, AGG_MIN_INT, AGG_MAX_INT, AGG_SUM_INT, AGG_MIN_FLOAT, AGG_MAX_FLOAT, AGG_SUM_FLOAT, AGG_SET_UNION_INT, AGG_SET_UNION_FLOAT, AGG_SUM_LIST_INT, AGG_SUM_LIST_FLOAT, myassert.
Referenced by aggregate_recalc, tuple_do_handle.
void MeldInterpret::MeldInterpretVM::aggregate_recalc(tuple_entry *agg, Register *reg, bool first_run)
References TUPLE_TYPE, _tuple_entry::tuple, AGG_AGG, TYPE_AGGREGATE, AGG_FIELD, _tuple_entry::records, record_type::agg_queue, _tuple_queue::head, GET_TUPLE_FIELD, TYPE_ARG_SIZE, aggregate_seed, record_type::count, TYPE_FIELD_SIZE, TYPE_ARG_OFFSET, TYPE_SIZE, _tuple_entry::next, aggregate_accumulate, aggregate_changed, process_bytecode, TYPE_START, NOT_LINEAR, PROCESS_TUPLE, aggregate_free.
Referenced by tuple_do_handle.
void MeldInterpret::MeldInterpretVM::databaseConsistencyChecker()
References NUM_TYPES, TUPLES, _tuple_entry::next, TYPE_NEIGHBOR, TYPE_VACANT, TYPE_NEIGHBORCOUNT, getBlockId, tuple_names, TYPE_SIZE.
tuple_entry * MeldInterpret::MeldInterpretVM::queue_enqueue(tuple_queue *queue, tuple_t tuple, record_type isNew)
References _tuple_entry::tuple, _tuple_entry::records, _tuple_entry::next, queue_push_tuple, _tuple_queue::length.
Referenced by enqueueNewTuple, receive_tuple, tuple_do_handle.
bool MeldInterpret::MeldInterpretVM::queue_is_empty(tuple_queue *queue)
References _tuple_queue::head.
Referenced by processOneRule, tuple_do_handle.
tuple_t MeldInterpret::MeldInterpretVM::queue_dequeue(tuple_queue *queue, int *isNew)
References queue_pop_tuple, _tuple_queue::length, _tuple_entry::tuple, _tuple_entry::records, record_type::count.
Referenced by processOneRule.
tuple_t MeldInterpret::MeldInterpretVM::queue_dequeue_pos(tuple_queue *queue, tuple_entry **pos)
References _tuple_entry::next, _tuple_queue::length, _tuple_queue::tail, _tuple_queue::head, _tuple_entry::tuple.
Referenced by receive_tuple, tuple_do_handle.
tuple_t MeldInterpret::MeldInterpretVM::queue_pop_tuple(tuple_queue *queue)
References _tuple_queue::head, _tuple_entry::next, _tuple_queue::tail.
Referenced by queue_dequeue.
void MeldInterpret::MeldInterpretVM::queue_push_tuple(tuple_queue *queue, tuple_entry *entry)
References _tuple_queue::head, _tuple_queue::tail, _tuple_entry::next.
Referenced by queue_enqueue.
tuple_pentry * MeldInterpret::MeldInterpretVM::p_dequeue(tuple_pqueue *q)
References tuple_pqueue::queue, _tuple_pentry::next.
Referenced by processOneRule.
void MeldInterpret::MeldInterpretVM::p_enqueue(tuple_pqueue *q, Time priority, tuple_t tuple, NodeID rt, record_type isNew)
References _tuple_pentry::tuple, _tuple_pentry::records, _tuple_pentry::priority, _tuple_pentry::rt, tuple_pqueue::queue, _tuple_pentry::next.
Referenced by enqueueNewTuple, tuple_send.
int MeldInterpret::MeldInterpretVM::queue_length(tuple_queue *queue)
References _tuple_queue::head, _tuple_entry::next.
Referenced by execute_iter.
bool MeldInterpret::MeldInterpretVM::equilibrium()
References vmMap, host, BaseSimulator::BuildingBlock::getState, hasWork.
static bool MeldInterpret::MeldInterpretVM::isInDebuggingMode()
void MeldInterpret::MeldInterpretVM::setConfiguration(string path, bool d)
References readProgram.
Referenced by BaseSimulator::Simulator::Simulator.
void MeldInterpret::MeldInterpretVM::readProgram(string path)
References characterCount, meld_prog, tuple_names, OUTPUT.
Referenced by setConfiguration.
int MeldInterpret::MeldInterpretVM::characterCount(string in, char character)
Referenced by readProgram.
static void MeldInterpret::MeldInterpretVM::queue_init(tuple_queue *queue)
References _tuple_queue::head, _tuple_queue::tail.
Referenced by tuple_do_handle.
static bool MeldInterpret::MeldInterpretVM::p_empty(tuple_pqueue *q)
References tuple_pqueue::queue.
Referenced by processOneRule.
static tuple_pentry* MeldInterpret::MeldInterpretVM::p_peek(tuple_pqueue *q)
References tuple_pqueue::queue.
Referenced by processOneRule.