Catoms2D::MotionStartEvent
Vecteur Catoms2D::MotionStartEvent::pivot
double Catoms2D::MotionStartEvent::angle
int Catoms2D::MotionStartEvent::sens
Catoms2D::MotionStartEvent::MotionStartEvent(uint64_t, Catoms2DBlock *block, Catoms2DMove &m)
References EVENT_CONSTRUCTOR_INFO, Event::eventType, EVENT_MOTION_START, Vecteur::set, Catoms2D::Catoms2DMove::getPivot, Catoms2D::Catoms2DBlock::ptrGlBlock, GlBlock::position, Catoms2D::Catoms2DMove::getDirection.
Catoms2D::MotionStartEvent::MotionStartEvent(MotionStartEvent *ev)
References EVENT_CONSTRUCTOR_INFO.
Catoms2D::MotionStartEvent::~MotionStartEvent()
References EVENT_DESTRUCTOR_INFO.
void Catoms2D::MotionStartEvent::consumeBlockEvent()
References consume, getEventName.
void Catoms2D::MotionStartEvent::consume()
References EVENT_CONSUME_INFO, Catoms2D::getScheduler, BlockEvent::concernedBlock, Catoms2D::Catoms2DWorld::getWorld, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms2D::Catoms2DBlock::setColor, DARKGREY, BaseSimulator::Scheduler::schedule, BaseSimulator::Scheduler::now, ANIMATION_DELAY.
Referenced by consumeBlockEvent, Catoms2D::MotionStepEvent::consumeBlockEvent, Catoms2D::MotionStopEvent::consumeBlockEvent, Catoms2D::MotionEndEvent::consumeBlockEvent.
const string Catoms2D::MotionStartEvent::getEventName()
Referenced by consumeBlockEvent, Catoms2D::MotionStepEvent::consumeBlockEvent, Catoms2D::MotionStopEvent::consumeBlockEvent, Catoms2D::MotionEndEvent::consumeBlockEvent.