GlutWindow
vector<GlutWindow*> GlutWindow::children
Referenced by ~GlutWindow, addChild, glDraw, keyFunc, mouseFunc, passiveMotionFunc, GlutSlidingDebugWindow::keyFunc, GlutPopupMenuWindow::addButton, GlutPopupMenuWindow::activate.
GLuint GlutWindow::idTexture
Referenced by GlutWindow, bindTexture.
GLuint GlutWindow::id
Referenced by keyFunc, mouseFunc, GlutSlidingDebugWindow::keyFunc, loadTexture, GlutPopupMenuWindow::activate, GlutInputWindow::mouseFunc.
GLint GlutWindow::x
Referenced by glDraw, mouseFunc, passiveMotionFunc, GlutSlidingMainWindow::glDraw, GlutSlidingMainWindow::mouseFunc, GlutSlidingMainWindow::openClose, GlutSlidingDebugWindow::glDraw, GlutSlidingDebugWindow::mouseFunc, GlutButton::glDraw, GlutButton::mouseFunc, GlutButton::passiveMotionFunc, GlutPopupWindow::glDraw, GlutPopupMenuWindow::glDraw, GlutHelpWindow::glDraw, GlutSlider::glDraw, GlutSlider::mouseFunc, GlutInputWindow::glDraw, GlutInputWindow::mouseFunc.
GLint GlutWindow::y
Referenced by glDraw, mouseFunc, passiveMotionFunc, GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, GlutButton::glDraw, GlutButton::mouseFunc, GlutButton::passiveMotionFunc, GlutPopupWindow::glDraw, GlutPopupMenuWindow::glDraw, GlutHelpWindow::glDraw, GlutSlider::glDraw, GlutSlider::mouseFunc, GlutInputWindow::glDraw, GlutInputWindow::mouseFunc.
GLint GlutWindow::w
Referenced by GlutWindow, GlutSlidingMainWindow::glDraw, GlutSlidingMainWindow::mouseFunc, GlutSlidingMainWindow::openClose, GlutSlidingDebugWindow::glDraw, GlutSlidingDebugWindow::mouseFunc, GlutButton::glDraw, GlutPopupWindow::glDraw, GlutPopupMenuWindow::addButton, GlutPopupMenuWindow::glDraw, GlutHelpWindow::glDraw, GlutSlider::glDraw, GlutSlider::mouseFunc, GlutInputWindow::glDraw.
GLint GlutWindow::h
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms3D::Catoms3DWorld::createPopupMenu, GlutWindow, mouseFunc, GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, GlutButton::glDraw, GlutButton::mouseFunc, GlutButton::passiveMotionFunc, GlutPopupWindow::glDraw, GlutPopupMenuWindow::addButton, GlutPopupMenuWindow::glDraw, GlutHelpWindow::glDraw, GlutSlider::update, GlutSlider::glDraw, GlutSlider::mouseFunc, GlutInputWindow::glDraw, GlutInputWindow::mouseFunc, RobotBlocks::RobotBlocksWorld::createPopupMenu.
void GlutWindow::addChild(GlutWindow *child)
References children.
Referenced by GlutWindow.
void GlutWindow::bindTexture()
References idTexture.
Referenced by GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, GlutButton::glDraw, GlutSlider::glDraw.
GlutWindow::GlutWindow(GlutWindow *parent, GLuint pid, GLint px, GLint py, GLint pw, GLint ph, const char *titreTexture)
References addChild, setGeometry, idTexture, loadTexture, w, h.
GlutWindow::~GlutWindow()
References children.
void GlutWindow::setGeometry(GLint px, GLint py, GLint pw, GLint ph)
Referenced by GlutWindow, GlutSlidingMainWindow::reshapeFunc, GlutSlidingDebugWindow::reshapeFunc, GlutPopupMenuWindow::addButton.
void GlutWindow::glDraw()
References children, x, y.
Referenced by GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, GlutPopupMenuWindow::glDraw, GlutHelpWindow::glDraw, GlutInputWindow::glDraw.
int GlutWindow::mouseFunc(int button, int state, int mx, int my)
References x, y, h, children, id.
Referenced by GlutSlidingMainWindow::mouseFunc, GlutSlidingDebugWindow::mouseFunc, GlutPopupMenuWindow::mouseFunc, GlutHelpWindow::mouseFunc.
bool GlutWindow::passiveMotionFunc(int mx, int my)
References children, x, y.
Referenced by GlutContext::reshapeFunc.
int GlutWindow::keyFunc(int charcode)
References children, id.
virtual void GlutWindow::reshapeFunc(int wx, int wy, int mw, int mh)
GLuint GlutWindow::loadTexture(const char *titre, int &tw, int &th)
References OUTPUT, lectureTarga, ERRPUT, id.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::loadTextures, Catoms2D::Catoms2DWorld::loadTextures, Catoms3D::Catoms3DWorld::loadTextures, GlutWindow, ObjLoader::Mtl::glBind, RobotBlocks::RobotBlocksWorld::loadTextures, SmartBlocks::SmartBlocksWorld::loadTextures.
unsigned char * GlutWindow::lectureTarga(const char *titre, int &width, int &height, bool retourner=false)
References DEF_targaHeaderContent, DEF_targaHeaderLength, ERRPUT.
Referenced by loadTexture.
GLfloat GlutWindow::drawString(GLfloat x, GLfloat y, const char *str, void *mode=GLUT_BITMAP_8_BY_13, GLint height=13)
Referenced by GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, GlutPopupWindow::glDraw, GlutInputWindow::glDraw, GlutContext::reshapeFunc.