MeldInterpret::VMSetIdEvent
MeldInterpret::VMSetIdEvent::VMSetIdEvent(uint64_t, BaseSimulator::BuildingBlock *conBlock)
References EVENT_CONSTRUCTOR_INFO, Event::eventType, EVENT_SET_ID.
Referenced by consume.
MeldInterpret::VMSetIdEvent::VMSetIdEvent(VMSetIdEvent *ev)
References EVENT_CONSTRUCTOR_INFO.
MeldInterpret::VMSetIdEvent::~VMSetIdEvent()
References EVENT_DESTRUCTOR_INFO.
void MeldInterpret::VMSetIdEvent::consumeBlockEvent()
References consume, getEventName.
void MeldInterpret::VMSetIdEvent::consume()
References EVENT_CONSUME_INFO, BlockEvent::concernedBlock, BaseSimulator::BuildingBlock::scheduleLocalEvent, VMSetIdEvent.
Referenced by consumeBlockEvent, MeldInterpret::VMStopEvent::consumeBlockEvent.
const string MeldInterpret::VMSetIdEvent::getEventName()
Referenced by consumeBlockEvent, MeldInterpret::VMStopEvent::consumeBlockEvent.