BlinkyBlocks::NeighborDirection
Direction
int BlinkyBlocks::NeighborDirection::getOpposite(int d)
References ERRPUT.
Referenced by BlinkyBlocks::BlinkyBlocksBlock::addNeighbor, BlinkyBlocks::BlinkyBlocksBlock::removeNeighbor.
string BlinkyBlocks::NeighborDirection::getString(int d)
Referenced by BlinkyBlocks::BlinkyBlocksBlock::addNeighbor, BlinkyBlocks::BlinkyBlocksBlock::removeNeighbor.