GlBlock
bool GlBlock::isHighlighted
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDraw, Catoms2D::Catoms2DGlBlock::glDraw, Catoms3D::Catoms3DGlBlock::glDraw, GlBlock, toggleHighlight, RobotBlocks::RobotBlocksGlBlock::glDraw, SmartBlocks::SmartBlocksGlBlock::glDraw.
GLfloat GlBlock::position[3][3]
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDraw, BlinkyBlocks::BlinkyBlocksGlBlock::glDrawId, BlinkyBlocks::BlinkyBlocksGlBlock::glDrawIdByMaterial, Catoms2D::Catoms2DBlock::setColor, Catoms2D::MotionStartEvent::MotionStartEvent, Catoms2D::MotionStepEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::Catoms2DGlBlock::glDraw, Catoms2D::Catoms2DGlBlock::glDrawId, Catoms2D::Catoms2DGlBlock::glDrawIdByMaterial, Catoms2D::Catoms2DGlBlock::getInfo, Catoms3D::Catoms3DGlBlock::glDrawId, Catoms3D::Catoms3DGlBlock::glDrawIdByMaterial, Catoms3D::Catoms3DGlBlock::getInfo, GlBlock, setPosition, getInfo, RobotBlocks::RobotBlocksGlBlock::glDraw, RobotBlocks::RobotBlocksGlBlock::glDrawId, RobotBlocks::RobotBlocksGlBlock::glDrawIdByMaterial, RobotBlocks::RobotBlocksGlBlock::getInfo, SmartBlocks::SmartBlocksGlBlock::glDraw, SmartBlocks::SmartBlocksGlBlock::glDrawId.
GLfloat GlBlock::color[4][4]
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDraw, Catoms2D::Catoms2DGlBlock::glDraw, Catoms2D::Catoms2DGlBlock::getInfo, Catoms3D::Catoms3DGlBlock::glDraw, Catoms3D::Catoms3DGlBlock::getInfo, GlBlock, setColor, setVisible, getInfo, RobotBlocks::RobotBlocksGlBlock::glDraw, RobotBlocks::RobotBlocksGlBlock::getInfo, SmartBlocks::SmartBlocksGlBlock::glDraw.
int GlBlock::blockId
Referenced by Catoms2D::Catoms2DGlBlock::getInfo, Catoms3D::Catoms3DGlBlock::getInfo, getInfo, getPopupInfo, GlutSlidingMainWindow::glDraw, GlutSlidingMainWindow::addTrace, GlutSlidingMainWindow::select, GlutContext::reshapeFunc, RobotBlocks::RobotBlocksGlBlock::getInfo.
GlBlock::GlBlock(int id)
References position, color, isHighlighted.
GlBlock::GlBlock(int id, const Vecteur &pos, const Vecteur &col)
References position, color, isHighlighted.
GlBlock::~GlBlock()
void GlBlock::setPosition(const Vecteur &p)
References position.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::updateGlData, Catoms2D::Catoms2DWorld::updateGlData, Catoms3D::Catoms3DWorld::addBlock, Catoms3D::Catoms3DWorld::updateGlData, RobotBlocks::RobotBlocksWorld::updateGlData, SmartBlocks::SmartBlocksWorld::updateGlData.
void GlBlock::setColor(const Color &c)
References color.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::updateGlData, Catoms2D::Catoms2DWorld::updateGlData, Catoms3D::Catoms3DWorld::updateGlData, RobotBlocks::RobotBlocksWorld::updateGlData, SmartBlocks::SmartBlocksWorld::updateGlData.
void GlBlock::setColor(const Vecteur &c)
References color.
void GlBlock::setVisible(bool visible)
References color.
Referenced by Catoms3D::Catoms3DWorld::updateGlData.
void GlBlock::toggleHighlight()
References isHighlighted.
Referenced by GlutContext::reshapeFunc.
string GlBlock::getInfo()
References blockId, position, color.
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::getInfo, GlutSlidingMainWindow::glDraw, SmartBlocks::SmartBlocksGlBlock::getInfo.
string GlBlock::getPopupInfo()
References blockId.
Referenced by GlutContext::reshapeFunc.
virtual const Vecteur GlBlock::getPosition()
Referenced by GlutContext::reshapeFunc.