SmartBlocks::MotionStartEvent
Vecteur SmartBlocks::MotionStartEvent::finalPosition
SmartBlocks::MotionStartEvent::MotionStartEvent(uint64_t, SmartBlocksBlock *block, const Vecteur &fpos)
References EVENT_CONSTRUCTOR_INFO, Event::eventType, EVENT_MOTION_START.
SmartBlocks::MotionStartEvent::MotionStartEvent(MotionStartEvent *ev)
References EVENT_CONSTRUCTOR_INFO.
SmartBlocks::MotionStartEvent::~MotionStartEvent()
References EVENT_DESTRUCTOR_INFO.
void SmartBlocks::MotionStartEvent::consumeBlockEvent()
References consume, getEventName.
void SmartBlocks::MotionStartEvent::consume()
References EVENT_CONSUME_INFO, SmartBlocks::getScheduler, BlockEvent::concernedBlock, SmartBlocks::SmartBlocksWorld::getWorld, SmartBlocks::SmartBlocksWorld::disconnectBlock, SmartBlocks::SmartBlocksBlock::setColor, DARKGREY, BaseSimulator::Scheduler::now, ANIMATION_DELAY, BaseSimulator::Scheduler::schedule.
Referenced by consumeBlockEvent, SmartBlocks::MotionStepEvent::consumeBlockEvent, SmartBlocks::MotionStopEvent::consumeBlockEvent, SmartBlocks::MotionEndEvent::consumeBlockEvent.
const string SmartBlocks::MotionStartEvent::getEventName()
Referenced by consumeBlockEvent, SmartBlocks::MotionStepEvent::consumeBlockEvent, SmartBlocks::MotionStopEvent::consumeBlockEvent, SmartBlocks::MotionEndEvent::consumeBlockEvent.