BlinkyBlocks::BlinkyBlocksWorld
Grid3D<BuildingBlock*>* BlinkyBlocks::BlinkyBlocksWorld::grid
Referenced by BlinkyBlocksWorld.
int BlinkyBlocks::BlinkyBlocksWorld::gridSize[3][3]
Referenced by BlinkyBlocksWorld, addBlock, linkBlocks, glDraw, createPopupMenu.
BlinkyBlocksBlock** BlinkyBlocks::BlinkyBlocksWorld::gridPtrBlocks
Referenced by BlinkyBlocksWorld, ~BlinkyBlocksWorld.
GLfloat BlinkyBlocks::BlinkyBlocksWorld::blockSize[3][3]
Referenced by BlinkyBlocksWorld, glDraw, glDrawId, glDrawIdByMaterial, updateGlData.
Camera* BlinkyBlocks::BlinkyBlocksWorld::camera
Referenced by BlinkyBlocksWorld, ~BlinkyBlocksWorld, getCamera.
ObjLoader::ObjLoader* BlinkyBlocks::BlinkyBlocksWorld::objBlock
Referenced by BlinkyBlocksWorld, ~BlinkyBlocksWorld, glDraw, glDrawId.
ObjLoader::ObjLoader * BlinkyBlocks::BlinkyBlocksWorld::objBlockForPicking
Referenced by BlinkyBlocksWorld, ~BlinkyBlocksWorld, glDrawIdByMaterial, setSelectedFace.
ObjLoader::ObjLoader * BlinkyBlocks::BlinkyBlocksWorld::objRepere
Referenced by BlinkyBlocksWorld, ~BlinkyBlocksWorld, glDraw.
GLuint BlinkyBlocks::BlinkyBlocksWorld::idTextureWall
Referenced by BlinkyBlocksWorld, glDraw, loadTextures.
GLushort BlinkyBlocks::BlinkyBlocksWorld::numSelectedFace
Referenced by BlinkyBlocksWorld, createPopupMenu, menuChoice, setSelectedFace.
GLuint BlinkyBlocks::BlinkyBlocksWorld::numSelectedBlock
Referenced by BlinkyBlocksWorld, createPopupMenu, menuChoice, setSelectedFace.
GLint BlinkyBlocks::BlinkyBlocksWorld::menuId
Referenced by BlinkyBlocksWorld.
vector<ScenarioEvent*> BlinkyBlocks::BlinkyBlocksWorld::tabEvents
Referenced by ~BlinkyBlocksWorld.
BlinkyBlocks::BlinkyBlocksWorld::BlinkyBlocksWorld(int slx, int sly, int slz, int argc, char *argv[])
References grid, OUTPUT, gridSize, gridPtrBlocks, GlutContext::init, idTextureWall, blockSize, objBlock, objBlockForPicking, objRepere, camera, M_PI, Camera::setLightParameters, Camera::setTarget, menuId, numSelectedFace, numSelectedBlock.
Referenced by createWorld.
BlinkyBlocks::BlinkyBlocksWorld::~BlinkyBlocksWorld()
References OUTPUT, gridPtrBlocks, objBlock, objBlockForPicking, objRepere, camera, tabEvents.
BlinkyBlocksBlock* BlinkyBlocks::BlinkyBlocksWorld::getGridPtr(int ix, int iy, int iz)
Referenced by linkBlocks, createPopupMenu.
void BlinkyBlocks::BlinkyBlocksWorld::setGridPtr(int ix, int iy, int iz, BlinkyBlocksBlock *ptr)
References createWorld, deleteWorld.
Referenced by addBlock, deleteBlock, stopBlock.
void BlinkyBlocks::BlinkyBlocksWorld::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References BaseSimulator::World::world, BlinkyBlocksWorld.
Referenced by setGridPtr, BlinkyBlocks::createWorld.
void BlinkyBlocks::BlinkyBlocksWorld::deleteWorld()
References BaseSimulator::World::world.
Referenced by setGridPtr, BlinkyBlocks::deleteWorld.
static BlinkyBlocksWorld* BlinkyBlocks::BlinkyBlocksWorld::getWorld()
References BaseSimulator::World::world.
Referenced by BlinkyBlocks::getWorld.
void BlinkyBlocks::BlinkyBlocksWorld::printInfo()
References OUTPUT.
virtual BlinkyBlocksBlock* BlinkyBlocks::BlinkyBlocksWorld::getBlockById(int bId)
References addBlock, deleteBlock.
Referenced by createPopupMenu, menuChoice, tapBlock, accelBlock, shakeBlock, stopBlock.
void BlinkyBlocks::BlinkyBlocksWorld::addBlock(int blockId, BlinkyBlocksBlockCode *(*blinkyBlockCodeBuildingFunction)(BlinkyBlocksBlock *), const Vecteur &pos, const Color &col)
References BaseSimulator::World::buildingBlocksMap, BaseSimulator::BuildingBlock::blockId, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::schedule, BaseSimulator::World::tabGlBlocks, BlinkyBlocks::BlinkyBlocksBlock::setGlBlock, BlinkyBlocks::BlinkyBlocksBlock::setPosition, BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::position, Vecteur::pt, gridSize, setGridPtr, ERRPUT.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, menuChoice, getBlockById.
void BlinkyBlocks::BlinkyBlocksWorld::deleteBlock(BlinkyBlocksBlock *bb)
References BaseSimulator::BuildingBlock::getState, BaseSimulator::BuildingBlock::ALIVE, BlinkyBlocks::BlinkyBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::removeNeighbor, BlinkyBlocks::BlinkyBlocksBlock::position, Vecteur::pt, setGridPtr, BlinkyBlocks::BlinkyBlocksBlock::stop, BlinkyBlocks::getScheduler, BaseSimulator::BuildingBlock::REMOVED, linkBlocks, BaseSimulator::World::selectedBlock, BlinkyBlocks::BlinkyBlocksBlock::ptrGlBlock, GlutContext::mainWindow, GlutSlidingMainWindow::select, BaseSimulator::World::tabGlBlocks.
Referenced by menuChoice, getBlockById.
void BlinkyBlocks::BlinkyBlocksWorld::setBlocksSize(float *siz)
References linkBlocks, loadTextures, glDraw, glDrawId, glDrawIdByMaterial, updateGlData, createPopupMenu, createHelpWindow.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator.
void BlinkyBlocks::BlinkyBlocksWorld::linkBlocks()
References gridSize, getGridPtr, BlinkyBlocks::NeighborDirection::Top, BlinkyBlocks::NeighborDirection::Bottom, OUTPUT, BaseSimulator::BuildingBlock::blockId, BlinkyBlocks::NeighborDirection::Right, BlinkyBlocks::NeighborDirection::Left, BlinkyBlocks::NeighborDirection::Front, BlinkyBlocks::NeighborDirection::Back.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, deleteBlock, menuChoice, stopBlock, setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::loadTextures(const string &str)
References idTextureWall, GlutWindow::loadTexture.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::glDraw()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock, enableTexture, idTextureWall, gridSize, objRepere, ObjLoader::ObjLoader::glDraw.
Referenced by setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::glDrawId()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::glDrawIdByMaterial()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlockForPicking, BaseSimulator::World::unlock.
Referenced by setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::updateGlData(BlinkyBlocksBlock *blc)
References BlinkyBlocks::BlinkyBlocksBlock::getGlBlock, BaseSimulator::World::lock, blockSize, BlinkyBlocks::BlinkyBlocksBlock::position, GlBlock::setPosition, GlBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::color, BaseSimulator::World::unlock.
Referenced by BlinkyBlocks::BlinkyBlocksBlock::setPosition, BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::stop, setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu(int ix, int iy)
References GlutContext::popupMenu, GlutPopupMenuWindow::addButton, GlutWindow::h, getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, numSelectedFace, BlinkyBlocks::NeighborDirection::Left, BlinkyBlocks::BlinkyBlocksBlock::position, getGridPtr, BlinkyBlocks::NeighborDirection::Right, gridSize, BlinkyBlocks::NeighborDirection::Front, BlinkyBlocks::NeighborDirection::Back, BlinkyBlocks::NeighborDirection::Bottom, BlinkyBlocks::NeighborDirection::Top, GlutPopupMenuWindow::activate, GlutPopupMenuWindow::setCenterPosition, GlutContext::screenHeight, GlutPopupMenuWindow::show.
Referenced by setBlocksSize.
void BlinkyBlocks::BlinkyBlocksWorld::createHelpWindow()
References GlutContext::helpWindow.
Referenced by setBlocksSize.
virtual Camera* BlinkyBlocks::BlinkyBlocksWorld::getCamera()
References camera, setSelectedFace, menuChoice, tapBlock, accelBlock, shakeBlock, stopBlock.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, GlutContext::reshapeFunc.
void BlinkyBlocks::BlinkyBlocksWorld::setSelectedFace(int n)
References numSelectedBlock, objBlockForPicking, ObjLoader::ObjLoader::getObjMtlName, numSelectedFace, BlinkyBlocks::NeighborDirection::Top, BlinkyBlocks::NeighborDirection::Bottom, BlinkyBlocks::NeighborDirection::Right, BlinkyBlocks::NeighborDirection::Left, BlinkyBlocks::NeighborDirection::Front, BlinkyBlocks::NeighborDirection::Back.
Referenced by getCamera.
void BlinkyBlocks::BlinkyBlocksWorld::menuChoice(int n)
References getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, OUTPUT, BaseSimulator::BuildingBlock::blockId, numSelectedFace, BlinkyBlocks::BlinkyBlocksBlock::position, BlinkyBlocks::NeighborDirection::Left, Vecteur::pt, BlinkyBlocks::NeighborDirection::Right, BlinkyBlocks::NeighborDirection::Front, BlinkyBlocks::NeighborDirection::Back, BlinkyBlocks::NeighborDirection::Bottom, BlinkyBlocks::NeighborDirection::Top, addBlock, BlinkyBlocks::BlinkyBlocksBlock::buildNewBlockCode, BlinkyBlocks::BlinkyBlocksBlock::color, linkBlocks, deleteBlock, stopBlock, BlinkyBlocks::getScheduler.
Referenced by getCamera, GlutContext::reshapeFunc.
void BlinkyBlocks::BlinkyBlocksWorld::tapBlock(uint64_t date, int bId)
References getBlockById, BlinkyBlocks::BlinkyBlocksBlock::tap.
Referenced by getCamera.
void BlinkyBlocks::BlinkyBlocksWorld::accelBlock(uint64_t date, int bId, int x, int y, int z)
References getBlockById, BlinkyBlocks::BlinkyBlocksBlock::accel.
Referenced by getCamera.
void BlinkyBlocks::BlinkyBlocksWorld::shakeBlock(uint64_t date, int bId, int f)
References getBlockById, BlinkyBlocks::BlinkyBlocksBlock::shake.
Referenced by getCamera.
void BlinkyBlocks::BlinkyBlocksWorld::stopBlock(uint64_t date, int bId)
References BaseSimulator::World::buildingBlocksMap, BaseSimulator::BuildingBlock::getState, BaseSimulator::BuildingBlock::ALIVE, BlinkyBlocks::BlinkyBlocksBlock::stop, BaseSimulator::BuildingBlock::STOPPED, getBlockById, BlinkyBlocks::BlinkyBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::removeNeighbor, BlinkyBlocks::BlinkyBlocksBlock::position, Vecteur::pt, setGridPtr, linkBlocks.
Referenced by menuChoice, getCamera.
void BlinkyBlocks::BlinkyBlocksWorld::addScenarioEvent(ScenarioEvent *ev)
References dump.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator.
void BlinkyBlocks::BlinkyBlocksWorld::dump()
References BaseSimulator::World::buildingBlocksMap.
Referenced by addScenarioEvent.