RobotBlocks::MotionStartEvent
Vecteur RobotBlocks::MotionStartEvent::finalPosition
RobotBlocks::MotionStartEvent::MotionStartEvent(uint64_t, RobotBlocksBlock *block, const Vecteur &fpos)
References EVENT_CONSTRUCTOR_INFO, Event::eventType, EVENT_MOTION_START.
RobotBlocks::MotionStartEvent::MotionStartEvent(MotionStartEvent *ev)
References EVENT_CONSTRUCTOR_INFO.
RobotBlocks::MotionStartEvent::~MotionStartEvent()
References EVENT_DESTRUCTOR_INFO.
void RobotBlocks::MotionStartEvent::consumeBlockEvent()
References consume, getEventName.
void RobotBlocks::MotionStartEvent::consume()
References EVENT_CONSUME_INFO, RobotBlocks::getScheduler, BlockEvent::concernedBlock, RobotBlocks::RobotBlocksWorld::getWorld, RobotBlocks::RobotBlocksWorld::disconnectBlock, RobotBlocks::RobotBlocksBlock::setColor, DARKGREY, BaseSimulator::Scheduler::schedule, BaseSimulator::Scheduler::now, ANIMATION_DELAY.
Referenced by consumeBlockEvent, RobotBlocks::MotionStepEvent::consumeBlockEvent, RobotBlocks::MotionStopEvent::consumeBlockEvent, RobotBlocks::MotionEndEvent::consumeBlockEvent.
const string RobotBlocks::MotionStartEvent::getEventName()
Referenced by consumeBlockEvent, RobotBlocks::MotionStepEvent::consumeBlockEvent, RobotBlocks::MotionStopEvent::consumeBlockEvent, RobotBlocks::MotionEndEvent::consumeBlockEvent.