SmartBlocks::PointCel
short SmartBlocks::PointCel::x
Referenced by SmartBlocks::SmartBlocksBlock::getP2PNetworkInterfaceByRelPos, SmartBlocks::SmartBlocksCapabilities::SmartBlocksCapabilities, SmartBlocks::dir, SmartBlocks::SmartBlocksCapabilities::validateToTarget, SmartBlocks::ValidationMatrix::get, SmartBlocks::ValidationMatrix::set, fromString, SmartBlocks::operator<<, rotateZ, set, SmartBlocks::operator!=, SmartBlocks::operator==, SmartBlocks::PresenceMatrix::add, SmartBlocks::PresenceMatrix::get, SmartBlocks::PresenceMatrix::set, SmartBlocks::SmartBlocksWorld::getPresenceMatrix, SmartBlocks::SmartBlocksWorld::getPresenceMatrix0.
short SmartBlocks::PointCel::y
Referenced by SmartBlocks::SmartBlocksBlock::getP2PNetworkInterfaceByRelPos, SmartBlocks::SmartBlocksCapabilities::SmartBlocksCapabilities, SmartBlocks::dir, SmartBlocks::SmartBlocksCapabilities::validateToTarget, SmartBlocks::ValidationMatrix::get, SmartBlocks::ValidationMatrix::set, fromString, SmartBlocks::operator<<, rotateZ, set, SmartBlocks::operator!=, SmartBlocks::operator==, SmartBlocks::PresenceMatrix::add, SmartBlocks::PresenceMatrix::get, SmartBlocks::PresenceMatrix::set, SmartBlocks::SmartBlocksWorld::getPresenceMatrix, SmartBlocks::SmartBlocksWorld::getPresenceMatrix0.
SmartBlocks::PointCel::PointCel()
SmartBlocks::PointCel::PointCel(short vx, short vy)
SmartBlocks::PointCel::PointCel(const char *str)
References fromString.
SmartBlocks::PointCel::PointCel(const char *str, const PointCel &ref)
References fromString.
void SmartBlocks::PointCel::set(short vx, short vy)
References x, y.
Referenced by SmartBlocks::Capability::Capability, SmartBlocks::SmartBlocksCapabilities::SmartBlocksCapabilities.
void SmartBlocks::PointCel::set(const char *str)
References fromString.
void SmartBlocks::PointCel::fromString(const char *str)
References x, y.
Referenced by SmartBlocks::SmartBlocksCapabilities::SmartBlocksCapabilities, PointCel, set.
void SmartBlocks::PointCel::fromString(const string &str, const PointCel &ref)
References x, y.
PointCel SmartBlocks::PointCel::rotateZ(int n) const
References x, y.
Referenced by SmartBlocks::Capability::Capability.
bool SmartBlocks::PointCel::isZero()
Referenced by SmartBlocks::SmartBlocksCapabilities::validateDirection.
bool SmartBlocks::PointCel::isSet() const
void SmartBlocks::PointCel::unSet()
References operator==, operator!=, operator<<.
bool operator==(const PointCel p1, const PointCel p2)
Referenced by unSet.
bool operator!=(const PointCel p1, const PointCel p2)
Referenced by unSet.
ostream& operator<<(ostream &f, const PointCel &pt)
Referenced by unSet.