Catoms2D::Catoms2DBlock
P2PNetworkInterface* Catoms2D::Catoms2DBlock::tabInterfaces[6][6]
boost::interprocess::interprocess_mutex Catoms2D::Catoms2DBlock::mutex_vm
Catoms2DGlBlock* Catoms2D::Catoms2DBlock::ptrGlBlock
Referenced by setColor, getGlBlock, Catoms2D::MotionStartEvent::MotionStartEvent, Catoms2D::MotionStepEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::Catoms2DWorld::deleteBlock.
Color Catoms2D::Catoms2DBlock::color
Referenced by setColor, Catoms2D::operator<<, Catoms2D::Catoms2DWorld::updateGlData, Catoms2D::Catoms2DWorld::menuChoice.
Vecteur Catoms2D::Catoms2DBlock::position
Referenced by setPosition, getPosition, Catoms2D::Catoms2DWorld::addBlock, Catoms2D::Catoms2DWorld::connectBlock, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms2D::Catoms2DWorld::updateGlData, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms2D::Catoms2DWorld::generateRandom, Catoms2D::Catoms2DWorld::extractConfig.
bool Catoms2D::Catoms2DBlock::isMaster
Referenced by Catoms2D::Catoms2DWorld::addBlock.
int Catoms2D::Catoms2DBlock::angle
Referenced by Catoms2DBlock, getInterface, Catoms2D::MotionStepEvent::consume.
Catoms2DBlockCode*(* Catoms2D::Catoms2DBlock::buildNewBlockCode) (Catoms2DBlock *))(Catoms2DBlock *)
Referenced by Catoms2DBlock, Catoms2D::Catoms2DWorld::menuChoice, Catoms2D::Catoms2DWorld::generateRandom.
Catoms2D::Catoms2DBlock::Catoms2DBlock(int bId, Catoms2DBlockCode *(*blinkyBlocksBlockCodeBuildingFunction)(Catoms2DBlock *))
References OUTPUT, MAX_NB_NEIGHBORS, BaseSimulator::BuildingBlock::getP2PNetworkInterfaceList, buildNewBlockCode, BaseSimulator::BuildingBlock::blockCode, angle.
Catoms2D::Catoms2DBlock::~Catoms2DBlock()
References OUTPUT, BaseSimulator::BuildingBlock::blockId.
Catoms2DGlBlock* Catoms2D::Catoms2DBlock::getGlBlock()
References ptrGlBlock.
Referenced by Catoms2D::Catoms2DWorld::updateGlData.
void Catoms2D::Catoms2DBlock::setGlBlock(Catoms2DGlBlock *ptr)
References setColor, setPosition, getInterface.
Referenced by Catoms2D::Catoms2DWorld::addBlock.
void Catoms2D::Catoms2DBlock::setColor(const Color &)
References color, Catoms2D::getWorld, Catoms2D::Catoms2DWorld::updateGlData, ptrGlBlock, GlBlock::position, Catoms2D::Catoms2DGlBlock::angle.
Referenced by setGlBlock, Catoms2D::MotionStartEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::GenericCodeBlock::setColor, Catoms2D::Catoms2DWorld::addBlock.
void Catoms2D::Catoms2DBlock::setPosition(const Vecteur &p)
References position, Catoms2D::getWorld, Catoms2D::Catoms2DWorld::updateGlData.
Referenced by setGlBlock, Catoms2D::MotionStopEvent::consume, Catoms2D::Catoms2DWorld::addBlock.
P2PNetworkInterface * Catoms2D::Catoms2DBlock::getInterface(NeighborDirection::Direction d)
References angle.
Referenced by getDirection, hasANeighbor, getNextInterface, canMove, setGlBlock, Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms2D::Catoms2DWorld::deleteBlock.
P2PNetworkInterface* Catoms2D::Catoms2DBlock::getInterface(int d)
References getP2PNetworkInterfaceByRelPos, getPosition, getDirection, nbNeighbors, nbConsecutiveNeighbors, nbConsecutiveEmptyFaces, hasANeighbor, getNextInterface, SmartBlocks::dir, isBlocked, canMove, startMove, Catoms2D::operator<<.
P2PNetworkInterface* Catoms2D::Catoms2DBlock::getP2PNetworkInterfaceByRelPos(const PointRel3D &pos)
Referenced by getInterface.
Vecteur Catoms2D::Catoms2DBlock::getPosition(NeighborDirection::Direction d)
References position, Catoms2D::NeighborDirection::BottomLeft, Catoms2D::NeighborDirection::Left, Catoms2D::NeighborDirection::TopLeft, Catoms2D::NeighborDirection::TopRight, Catoms2D::NeighborDirection::Right, Catoms2D::NeighborDirection::BottomRight.
Referenced by getPosition, hasANeighbor, canMove, getInterface, Catoms2D::Catoms2DWorld::menuChoice.
Vecteur Catoms2D::Catoms2DBlock::getPosition(P2PNetworkInterface *p2p)
References getPosition, getDirection.
NeighborDirection::Direction Catoms2D::Catoms2DBlock::getDirection(P2PNetworkInterface *p2p)
References MAX_NB_NEIGHBORS, getInterface.
Referenced by getPosition, getNextInterface, canMove, getInterface.
int Catoms2D::Catoms2DBlock::nbNeighbors(bool groundIsNeighbor=false)
References MAX_NB_NEIGHBORS, hasANeighbor.
Referenced by isBlocked, getInterface.
int Catoms2D::Catoms2DBlock::nbConsecutiveNeighbors(bool groundIsNeighbor=false)
References MAX_NB_NEIGHBORS, hasANeighbor.
Referenced by isBlocked, getInterface.
int Catoms2D::Catoms2DBlock::nbConsecutiveEmptyFaces(bool groundIsNeighbor=false)
References MAX_NB_NEIGHBORS, hasANeighbor.
Referenced by getInterface.
bool Catoms2D::Catoms2DBlock::hasANeighbor(NeighborDirection::Direction n, bool groundIsNeighbor=false)
References getInterface.
Referenced by nbNeighbors, nbConsecutiveNeighbors, nbConsecutiveEmptyFaces, getInterface.
bool Catoms2D::Catoms2DBlock::hasANeighbor(P2PNetworkInterface *p2p, bool groundIsNeighbor=false)
References getPosition, P2PNetworkInterface::connectedInterface.
P2PNetworkInterface * Catoms2D::Catoms2DBlock::getNextInterface(RelativeDirection::Direction dir, P2PNetworkInterface *p2p, bool connected=false)
References getDirection, Catoms2D::RelativeDirection::CW, Catoms2D::NeighborDirection::Right, Catoms2D::NeighborDirection::BottomRight, MAX_NB_NEIGHBORS, getInterface, P2PNetworkInterface::connectedInterface.
Referenced by getInterface.
bool Catoms2D::Catoms2DBlock::isBlocked()
References nbNeighbors, nbConsecutiveNeighbors.
Referenced by getInterface.
bool Catoms2D::Catoms2DBlock::canMove(Catoms2DMove &m)
References Catoms2D::Catoms2DMove::getDirection, Catoms2D::Catoms2DMove::getPivot, Catoms2D::RelativeDirection::CW, Catoms2D::RelativeDirection::CCW, BaseSimulator::BuildingBlock::getP2PNetworkInterfaceByBlockRef, getDirection, Catoms2D::NeighborDirection::BottomRight, Catoms2D::NeighborDirection::Right, getInterface, getPosition, P2PNetworkInterface::connectedInterface.
Referenced by getInterface.
void Catoms2D::Catoms2DBlock::startMove(Catoms2DMove &m, uint64_t t)
References Catoms2D::getScheduler, BaseSimulator::Scheduler::schedule.
Referenced by startMove, getInterface.
void Catoms2D::Catoms2DBlock::startMove(Catoms2DMove &m)
References startMove, Catoms2D::getScheduler.