MultiCores::MultiCoresWorld
MultiCores::MultiCoresWorld::MultiCoresWorld()
MultiCores::MultiCoresWorld::~MultiCoresWorld()
void MultiCores::MultiCoresWorld::createWorld()
Referenced by MultiCores::createWorld.
void MultiCores::MultiCoresWorld::deleteWorld()
Referenced by MultiCores::deleteWorld.
static MultiCoresWorld* MultiCores::MultiCoresWorld::getWorld()
References BaseSimulator::World::world.
Referenced by MultiCores::getWorld.
void MultiCores::MultiCoresWorld::printInfo()
virtual MultiCoresBlock* MultiCores::MultiCoresWorld::getBlockById(int bId)
References addBlock.
Referenced by MultiCores::MultiCoresScheduler::waitForVMMessage.
void MultiCores::MultiCoresWorld::addBlock(int blockId, MultiCoresBlockCode *(*multiCoreBlockCodeBuildingFunction)(MultiCoresBlock *), float posX, float posY, float posZ, float colorR, float colorG, float colorB)
References BaseSimulator::BuildingBlock::blockId, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::schedule.
Referenced by MultiCores::MultiCoresScheduler::waitForVMMessage, getBlockById.