SquareMatrix
int SquareMatrix::size
int* SquareMatrix::distances
SquareMatrix::SquareMatrix(int s)
SquareMatrix::~SquareMatrix()
int SquareMatrix::getSize()
Referenced by ConfigStat::compute.
void SquareMatrix::set(int i, int j, int v)
Referenced by ConfigStat::compute.
int SquareMatrix::get(int i, int j)
Referenced by ConfigStat::compute.