BaseSimulator::BlockCode
BuildingBlock* BaseSimulator::BlockCode::hostBlock
Referenced by Catoms2D::GenericCodeBlock::GenericCodeBlock, RobotBlocks::GenericCodeBlock::GenericCodeBlock.
uint64_t BaseSimulator::BlockCode::availabilityDate
BaseSimulator::BlockCode::BlockCode(BuildingBlock *host)
References OUTPUT.
BaseSimulator::BlockCode::~BlockCode()
References OUTPUT.
virtual void BaseSimulator::BlockCode::processLocalEvent(EventPtr pev)=0
Referenced by Catoms2D::MotionEndEvent::consume, Catoms3D::MotionEndEvent::consume, MeldInterpret::VMStopEvent::consume, MeldProcess::VMStopEvent::consume, RobotBlocks::MotionEndEvent::consume, SmartBlocks::MotionEndEvent::consume.
virtual void BaseSimulator::BlockCode::startup()=0
Referenced by CodeStartEvent::consumeBlockEvent.
virtual void BaseSimulator::BlockCode::init()
Referenced by MeldProcess::MeldProcessVM::broadcastDebugCommand, MeldProcess::MeldProcessVM::sendCommand.
virtual void BaseSimulator::BlockCode::addDebugAttributes(Scheduler *scheduler)
Referenced by Catoms2D::GenericCodeBlock::GenericCodeBlock, RobotBlocks::GenericCodeBlock::GenericCodeBlock.