SmartBlocks::SmartBlocksScheduler
SmartBlocks::SmartBlocksScheduler::SmartBlocksScheduler()
References SCHEDULER_MODE_FASTEST, OUTPUT.
SmartBlocks::SmartBlocksScheduler::~SmartBlocksScheduler()
References OUTPUT.
void * SmartBlocks::SmartBlocksScheduler::startPaused()
References OUTPUT, SCHEDULER_MODE_FASTEST, SCHEDULER_MODE_REALTIME, Event::getNextId, Event::getNbLivingEvents, Message::getNbMessages.
void SmartBlocks::SmartBlocksScheduler::createScheduler()
Referenced by SmartBlocks::createScheduler.
void SmartBlocks::SmartBlocksScheduler::deleteScheduler()
Referenced by SmartBlocks::deleteScheduler.
static SmartBlocksScheduler* SmartBlocks::SmartBlocksScheduler::getScheduler()
References BaseSimulator::Scheduler::scheduler.
Referenced by SmartBlocks::getScheduler.
void SmartBlocks::SmartBlocksScheduler::start(int mode)
References BaseSimulator::Scheduler::schedulerMode, BaseSimulator::Scheduler::sem_schedulerStart.
void SmartBlocks::SmartBlocksScheduler::printInfo()