RobotBlocks::RobotBlocksBlock
P2PNetworkInterface* RobotBlocks::RobotBlocksBlock::tabInterfaces[6][6]
boost::interprocess::interprocess_mutex RobotBlocks::RobotBlocksBlock::mutex_vm
RobotBlocksGlBlock* RobotBlocks::RobotBlocksBlock::ptrGlBlock
Referenced by RobotBlocks::RobotBlocksWorld::deleteBlock.
Color RobotBlocks::RobotBlocksBlock::color
Referenced by setColor, RobotBlocks::operator<<, RobotBlocks::RobotBlocksWorld::updateGlData, RobotBlocks::RobotBlocksWorld::menuChoice.
Vecteur RobotBlocks::RobotBlocksBlock::position
Referenced by setPosition, RobotBlocks::MotionStepEvent::consume, RobotBlocks::MotionStopEvent::consume, RobotBlocks::RobotBlocksWorld::addBlock, RobotBlocks::RobotBlocksWorld::connectBlock, RobotBlocks::RobotBlocksWorld::disconnectBlock, RobotBlocks::RobotBlocksWorld::deleteBlock, RobotBlocks::RobotBlocksWorld::updateGlData, RobotBlocks::RobotBlocksWorld::createPopupMenu, RobotBlocks::RobotBlocksWorld::menuChoice.
bool RobotBlocks::RobotBlocksBlock::isMaster
Referenced by RobotBlocks::RobotBlocksWorld::addBlock.
RobotBlocksBlockCode*(* RobotBlocks::RobotBlocksBlock::buildNewBlockCode) (RobotBlocksBlock *))(RobotBlocksBlock *)
Referenced by RobotBlocksBlock, RobotBlocks::RobotBlocksWorld::menuChoice.
RobotBlocks::RobotBlocksBlock::RobotBlocksBlock(int bId, RobotBlocksBlockCode *(*blinkyBlocksBlockCodeBuildingFunction)(RobotBlocksBlock *))
References OUTPUT, buildNewBlockCode, BaseSimulator::BuildingBlock::blockCode.
RobotBlocks::RobotBlocksBlock::~RobotBlocksBlock()
References OUTPUT, BaseSimulator::BuildingBlock::blockId.
RobotBlocksGlBlock* RobotBlocks::RobotBlocksBlock::getGlBlock()
Referenced by RobotBlocks::RobotBlocksWorld::updateGlData.
void RobotBlocks::RobotBlocksBlock::setGlBlock(RobotBlocksGlBlock *ptr)
Referenced by RobotBlocks::RobotBlocksWorld::addBlock.
void RobotBlocks::RobotBlocksBlock::setColor(const Color &)
References color, RobotBlocks::getWorld, RobotBlocks::RobotBlocksWorld::updateGlData.
Referenced by RobotBlocks::MotionStartEvent::consume, RobotBlocks::MotionStopEvent::consume, RobotBlocks::GenericCodeBlock::setColor, RobotBlocks::RobotBlocksWorld::addBlock.
void RobotBlocks::RobotBlocksBlock::setPosition(const Vecteur &p)
References position, RobotBlocks::getWorld, RobotBlocks::RobotBlocksWorld::updateGlData.
Referenced by RobotBlocks::RobotBlocksWorld::addBlock.
void RobotBlocks::RobotBlocksBlock::setPrevNext(int, int)
References RobotBlocks::getWorld, RobotBlocks::RobotBlocksWorld::updateGlData.
void RobotBlocks::RobotBlocksBlock::setPrevNext(const P2PNetworkInterface *prev, const P2PNetworkInterface *next)
References BaseSimulator::BuildingBlock::nextId, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId, RobotBlocks::getWorld, RobotBlocks::RobotBlocksWorld::updateGlData.
P2PNetworkInterface * RobotBlocks::RobotBlocksBlock::getP2PNetworkInterfaceByRelPos(const PointRel3D &pos)
References RobotBlocks::PointRel3D::x, RobotBlocks::NeighborDirection::Back, RobotBlocks::NeighborDirection::Front, RobotBlocks::PointRel3D::y, RobotBlocks::NeighborDirection::Left, RobotBlocks::NeighborDirection::Right, RobotBlocks::PointRel3D::z, RobotBlocks::NeighborDirection::Bottom, RobotBlocks::NeighborDirection::Top.
P2PNetworkInterface* RobotBlocks::RobotBlocksBlock::getInterface(NeighborDirection::Direction d)
References RobotBlocks::operator<<.
Referenced by RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::RobotBlocksWorld::disconnectBlock, RobotBlocks::RobotBlocksWorld::deleteBlock.
NeighborDirection::Direction RobotBlocks::RobotBlocksBlock::getDirection(P2PNetworkInterface *)