GlutPopupWindow
string GlutPopupWindow::info
bool GlutPopupWindow::isVisible
GlutPopupWindow::GlutPopupWindow(GlutWindow *parent, GLint px, GLint py, GLint pw, GLint ph)
virtual GlutPopupWindow::~GlutPopupWindow()
void GlutPopupWindow::show(bool v)
Referenced by GlutContext::reshapeFunc.
bool GlutPopupWindow::isShown()
Referenced by GlutContext::reshapeFunc.
void GlutPopupWindow::setCenterPosition(int ix, int iy)
Referenced by GlutContext::reshapeFunc.
void GlutPopupWindow::setInfo(const string &str)
Referenced by GlutContext::reshapeFunc.
void GlutPopupWindow::glDraw()
References GlutWindow::x, GlutWindow::y, GlutWindow::w, GlutWindow::h, GlutWindow::drawString.
Referenced by GlutContext::reshapeFunc.