Camera
double Camera::phi
double Camera::theta
double Camera::distance
Vecteur Camera::position
Vecteur Camera::target
Vecteur Camera::Xcam
Vecteur Camera::Ycam
int Camera::mouse[2][2]
double Camera::sensibilityX
double Camera::sensibilityY
double Camera::w_h
double Camera::near_plane
double Camera::far_plane
double Camera::angle
bool Camera::targetMotion
LightSource Camera::ls
Referenced by setLightParameters, mouseLightUp, mouseLightMove, mouseLightZoom, shadowedRenderingStep1, shadowedRenderingStep3.
Camera::Camera(double t, double p, double d, double SX=0.02, double SY=0.02)
References updatePositionFromAngles.
void Camera::mouseDown(int x, int y, bool tm=false)
Referenced by GlutContext::reshapeFunc.
void Camera::mouseUp(int x, int y)
References M_PI, updatePositionFromAngles.
Referenced by GlutContext::reshapeFunc.
void Camera::mouseMove(int x, int y)
References M_PI, updatePositionFromAngles.
Referenced by GlutContext::reshapeFunc.
void Camera::mouseZoom(double pas)
References updatePositionFromAngles.
Referenced by GlutContext::reshapeFunc.
void Camera::mouseLightDown(int x, int y)
void Camera::mouseLightUp(int x, int y)
References ls, LightSource::theta, LightSource::phi, M_PI, LightSource::calcMatrices.
void Camera::mouseLightMove(int x, int y)
References ls, LightSource::theta, LightSource::phi, M_PI, LightSource::calcMatrices.
void Camera::mouseLightZoom(double pas)
References ls, LightSource::distance, LightSource::calcMatrices.
void Camera::updateIntrinsics(double a, double rwh, double np, double fp)
void Camera::setW_H(double r)
Referenced by GlutContext::reshapeFunc.
void Camera::setNearFar(double n, double f)
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void Camera::setAngle(double a)
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void Camera::setTarget(const Vecteur &p)
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, BlinkyBlocks::BlinkyBlocksWorld::BlinkyBlocksWorld, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms2D::Catoms2DWorld::Catoms2DWorld, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Catoms3D::Catoms3DWorld::Catoms3DWorld, GlutContext::reshapeFunc, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, RobotBlocks::RobotBlocksWorld::RobotBlocksWorld, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, SmartBlocks::SmartBlocksWorld::SmartBlocksWorld.
void Camera::setDirection(double az, double ele)
References M_PI.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void Camera::setDistance(double d)
References BlinkyBlocks::operator<<.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void Camera::glLookAt()
Referenced by GlutContext::reshapeFunc, shadowedRenderingStep3.
void Camera::setLightParameters(const Vecteur &t, double th, double ph, double d, double angle, double nearplane, double farplane)
References ls, LightSource::target, LightSource::theta, M_PI, LightSource::phi, LightSource::distance, LightSource::falloffAngle, LightSource::near_plane, LightSource::far_plane, LightSource::calcMatrices.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, BlinkyBlocks::BlinkyBlocksWorld::BlinkyBlocksWorld, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms2D::Catoms2DWorld::Catoms2DWorld, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Catoms3D::Catoms3DWorld::Catoms3DWorld, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, RobotBlocks::RobotBlocksWorld::RobotBlocksWorld, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, SmartBlocks::SmartBlocksWorld::SmartBlocksWorld.
void Camera::glProjection()
Referenced by GlutContext::reshapeFunc, shadowedRenderingStep3.
ostream& operator<<(ostream &f, const Camera &c)
void Camera::updatePositionFromAngles()
References Vecteur::pt, Vecteur::set, Vecteur::normer_interne.
Referenced by Camera, mouseUp, mouseMove, mouseZoom.