CommandLine
int CommandLine::topology
int CommandLine::topologyParameter
bool CommandLine::terminalOnly
int CommandLine::schedulerMode
bool CommandLine::meldDebugger
string CommandLine::programPath
string CommandLine::configFile
bool CommandLine::stats
bool CommandLine::fullScreen
int CommandLine::gridSize
void CommandLine::help()
void CommandLine::read(int argc, char *argv[])
CommandLine::CommandLine(int argc, char *argv[])
References CMD_LINE_UNDEFINED, GlutContext::setFullScreenMode.
CommandLine::~CommandLine()
void CommandLine::print()
bool CommandLine::randomWorldRequested()
References CMD_LINE_UNDEFINED.
int CommandLine::getRandomTopology()
int CommandLine::getRandomTopologyParameter()
bool CommandLine::getTerminalOnly()
int CommandLine::getSchedulerMode()
bool CommandLine::getMeldDebugger()
Referenced by BaseSimulator::Simulator::Simulator.
string CommandLine::getProgramPath()
Referenced by BaseSimulator::Simulator::Simulator.
string CommandLine::getConfigFile()
Referenced by BaseSimulator::Simulator::Simulator.
bool CommandLine::getStats()
bool CommandLine::getFullScreen()
int CommandLine::getGridSize()