Skeleton
double Skeleton::radius2
Referenced by potentiel.
double Skeleton::blobbiness
Referenced by potentiel.
vector<Skeleton*> Skeleton::children
Referenced by ~Skeleton, add, potentiel.
Skeleton::Skeleton()
Skeleton::Skeleton(double r, double b)
References ~Skeleton, add, potentiel.
Skeleton::~Skeleton()
References children.
Referenced by Skeleton.
void Skeleton::add(Skeleton *)
References children.
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Skeleton.
double Skeleton::potentiel(const Vecteur &pos)
References distance2, blobbiness, radius2, children.
Referenced by Catoms3D::Catoms3DWorld::getSkeletonPotentiel, Skeleton.
virtual double Skeleton::distance2(const Vecteur &pos)
Referenced by potentiel, SkelPoint::~SkelPoint.