MeldProcess::MeldProcessScheduler
boost::thread* MeldProcess::MeldProcessScheduler::schedulerThread
int MeldProcess::MeldProcessScheduler::schedulerMode
Referenced by start.
boost::interprocess::interprocess_semaphore* MeldProcess::MeldProcessScheduler::sem_schedulerStart
Referenced by start, unPause.
MeldProcess::MeldProcessScheduler::MeldProcessScheduler()
References OUTPUT, SCHEDULER_MODE_REALTIME.
MeldProcess::MeldProcessScheduler::~MeldProcessScheduler()
References OUTPUT.
void * MeldProcess::MeldProcessScheduler::startPaused()
References OUTPUT, SCHEDULER_MODE_FASTEST, MeldProcess::checkForReceivedVMCommands, MeldProcess::waitForOneVMCommand, MeldProcess::getDebugger, MeldProcess::MeldProcessDebugger::handleBreakAtTimeReached, MeldProcess::MeldProcessDebugger::handlePauseRequest, BlinkyBlocks::getWorld, SCHEDULER_MODE_REALTIME, Event::getNextId, Event::getNbLivingEvents, Message::getNbMessages.
void MeldProcess::MeldProcessScheduler::createScheduler()
Referenced by BlinkyBlocks::createScheduler.
void MeldProcess::MeldProcessScheduler::deleteScheduler()
Referenced by BlinkyBlocks::deleteScheduler.
static MeldProcessScheduler* MeldProcess::MeldProcessScheduler::getScheduler()
void MeldProcess::MeldProcessScheduler::printInfo()
References OUTPUT.
void MeldProcess::MeldProcessScheduler::start(int mode)
References schedulerMode, sem_schedulerStart.
void MeldProcess::MeldProcessScheduler::waitForSchedulerEnd()
void MeldProcess::MeldProcessScheduler::stop(uint64_t date)
void MeldProcess::MeldProcessScheduler::pause(uint64_t date)
References BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock.
Referenced by MeldProcess::MeldProcessDebugger::pauseSim.
void MeldProcess::MeldProcessScheduler::unPause()
References sem_schedulerStart, OUTPUT.
Referenced by MeldProcess::MeldProcessDebugger::unPauseSim.
bool MeldProcess::MeldProcessScheduler::isPaused()
bool MeldProcess::MeldProcessScheduler::schedule(Event *ev)
References OUTPUT, Event::id, SCHEDULER_MODE_REALTIME, SCHEDULER_MODE_FASTEST, ERRPUT.
bool MeldProcess::MeldProcessScheduler::scheduleLock(Event *ev)
void MeldProcess::MeldProcessScheduler::SemWaitOrReadDebugMessage()
References MeldProcess::checkForReceivedVMCommands.
int MeldProcess::MeldProcessScheduler::getMode()