Catoms3D::Catoms3DWorld
int Catoms3D::Catoms3DWorld::gridSize[3][3]
Referenced by Catoms3DWorld, linkBlocks, getGridSize.
Catoms3DBlock** Catoms3D::Catoms3DWorld::gridPtrBlocks
Referenced by Catoms3DWorld, ~Catoms3DWorld.
GLfloat Catoms3D::Catoms3DWorld::blockSize[3][3]
Referenced by Catoms3DWorld, worldToGridPosition, gridToWorldPosition, getBlocksSize.
Camera* Catoms3D::Catoms3DWorld::camera
Referenced by Catoms3DWorld, ~Catoms3DWorld, getCamera.
ObjLoader::ObjLoader* Catoms3D::Catoms3DWorld::objBlock
Referenced by Catoms3DWorld, ~Catoms3DWorld, glDraw, glDrawId.
ObjLoader::ObjLoader * Catoms3D::Catoms3DWorld::objBlockForPicking
Referenced by Catoms3DWorld, ~Catoms3DWorld, glDrawIdByMaterial, setSelectedFace.
ObjLoader::ObjLoader * Catoms3D::Catoms3DWorld::objRepere
Referenced by Catoms3DWorld, ~Catoms3DWorld.
GLuint Catoms3D::Catoms3DWorld::idTextureHexa
Referenced by Catoms3DWorld, loadTextures.
GLuint Catoms3D::Catoms3DWorld::idTextureGrid
Referenced by Catoms3DWorld, loadTextures.
GLushort Catoms3D::Catoms3DWorld::numSelectedFace
Referenced by Catoms3DWorld, menuChoice, setSelectedFace.
GLuint Catoms3D::Catoms3DWorld::numSelectedBlock
Referenced by Catoms3DWorld, menuChoice, setSelectedFace.
GLint Catoms3D::Catoms3DWorld::menuId
Referenced by Catoms3DWorld.
Skeleton* Catoms3D::Catoms3DWorld::skeleton
Referenced by Catoms3DWorld.
Catoms3D::Catoms3DWorld::Catoms3DWorld(int slx, int sly, int slz, int argc, char *argv[])
Constructor.
slx : grid size along x axis sly : grid size along x axis slz : grid size along x axis argc : number of execution parameters argv : string array of parameters
References OUTPUT, gridSize, gridPtrBlocks, GlutContext::init, idTextureHexa, idTextureGrid, blockSize, objBlock, objBlockForPicking, objRepere, camera, M_PI, Camera::setLightParameters, Camera::setTarget, menuId, numSelectedFace, numSelectedBlock, skeleton.
Referenced by createWorld.
Catoms3D::Catoms3DWorld::~Catoms3DWorld()
References OUTPUT, gridPtrBlocks, objBlock, objBlockForPicking, objRepere, camera.
void Catoms3D::Catoms3DWorld::linkBlock(const Cell3DPosition &pos)
Connect the block placed on the cell at position pos.
References getGridPtr, OUTPUT, BaseSimulator::BuildingBlock::blockId, Catoms3D::Catoms3DBlock::getNeighborPos, Catoms3D::Catoms3DBlock::getInterface, P2PNetworkInterface::connect.
Referenced by connectBlock, linkBlocks.
void Catoms3D::Catoms3DWorld::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References BaseSimulator::World::world, Catoms3DWorld.
Referenced by Catoms3D::createWorld.
void Catoms3D::Catoms3DWorld::deleteWorld()
References BaseSimulator::World::world.
Referenced by Catoms3D::deleteWorld.
static Catoms3DWorld* Catoms3D::Catoms3DWorld::getWorld()
References BaseSimulator::World::world.
Referenced by Catoms3D::MotionStartEvent::consume, Catoms3D::MotionStopEvent::consume, Catoms3D::getWorld.
void Catoms3D::Catoms3DWorld::printInfo()
References OUTPUT.
virtual Catoms3DBlock* Catoms3D::Catoms3DWorld::getBlockById(int bId)
References addBlock, deleteBlock.
Referenced by menuChoice.
void Catoms3D::Catoms3DWorld::addBlock(int blockId, Catoms3DBlockCode *(*robotBlockCodeBuildingFunction)(Catoms3DBlock *), const Cell3DPosition &pos, short orientation, const Color &col, bool master=false)
References BaseSimulator::World::buildingBlocksMap, BaseSimulator::BuildingBlock::blockId, Catoms3D::getScheduler, BaseSimulator::Scheduler::schedule, BaseSimulator::World::tabGlBlocks, Catoms3D::Catoms3DBlock::setGlBlock, Catoms3D::Catoms3DBlock::setPositionAndOrientation, Catoms3D::Catoms3DBlock::setColor, setGridPtr, GlBlock::setPosition, gridToWorldPosition.
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator, getBlockById.
void Catoms3D::Catoms3DWorld::deleteBlock(Catoms3DBlock *bb)
References BaseSimulator::BuildingBlock::getState, BaseSimulator::BuildingBlock::ALIVE, Catoms3D::Catoms3DBlock::getInterface, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::removeNeighbor, setGridPtr, Catoms3D::Catoms3DBlock::position, disconnectBlock, BaseSimulator::World::selectedBlock, Catoms3D::Catoms3DBlock::ptrGlBlock, GlutContext::mainWindow, GlutSlidingMainWindow::select, BaseSimulator::World::tabGlBlocks.
Referenced by menuChoice, getBlockById.
void Catoms3D::Catoms3DWorld::setBlocksSize(float *siz)
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator.
const float* Catoms3D::Catoms3DWorld::getBlocksSize()
References blockSize.
Referenced by Catoms3D::Catoms3DBlock::getNeighborPos, Catoms3D::Catoms3DBlock::getInterface.
void Catoms3D::Catoms3DWorld::setGridPtr(const Cell3DPosition &pos, Catoms3DBlock *ptr)
associate a block to a cell of the grid
References Cell3DPosition::pt.
Referenced by Catoms3D::MotionStopEvent::consume, addBlock, connectBlock, disconnectBlock, deleteBlock.
Catoms3DBlock* Catoms3D::Catoms3DWorld::getGridPtr(const Cell3DPosition &pos)
return the block placed on the cell of position pos
References Cell3DPosition::pt.
Referenced by linkBlock.
int* Catoms3D::Catoms3DWorld::getGridSize()
References gridSize.
Referenced by Catoms3D::Catoms3DBlock::getNeighborPos.
void Catoms3D::Catoms3DWorld::setSkeleton(Skeleton *s)
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator.
double Catoms3D::Catoms3DWorld::getSkeletonPotentiel(const Vecteur &pos)
References Skeleton::potentiel, linkBlocks, worldToGridPosition, gridToWorldPosition, glDraw, glDrawId, glDrawIdByMaterial, updateGlData, createPopupMenu, createHelpWindow.
void Catoms3D::Catoms3DWorld::linkBlocks()
update the list of connected blocks
Connect all blocks of the grid.
References OUTPUT, Cell3DPosition::pt, gridSize, linkBlock.
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator, getSkeletonPotentiel.
Cell3DPosition Catoms3D::Catoms3DWorld::worldToGridPosition(Vecteur &pos)
References Cell3DPosition::pt, Catoms3D::M_SQRT2_2, blockSize.
Referenced by Catoms3D::Catoms3DBlock::getNeighborPos, Catoms3D::Rotations::getFinalPositionAndOrientation, getSkeletonPotentiel.
Vecteur Catoms3D::Catoms3DWorld::gridToWorldPosition(const Cell3DPosition &pos)
References Vecteur::pt, Catoms3D::M_SQRT2_2, blockSize.
Referenced by Catoms3D::Catoms3DBlock::getInterface, addBlock, updateGlData, getSkeletonPotentiel.
void Catoms3D::Catoms3DWorld::glDraw()
Draw catoms and axes.
References BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by getSkeletonPotentiel.
void Catoms3D::Catoms3DWorld::glDrawId()
References BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by getSkeletonPotentiel.
void Catoms3D::Catoms3DWorld::glDrawIdByMaterial()
References BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlockForPicking, BaseSimulator::World::unlock.
Referenced by getSkeletonPotentiel.
void Catoms3D::Catoms3DWorld::updateGlData(Catoms3DBlock *blc, const Color &color)
References Catoms3D::Catoms3DBlock::getGlBlock, BaseSimulator::World::lock, GlBlock::setColor, BaseSimulator::World::unlock.
Referenced by Catoms3D::Catoms3DBlock::setColor, Catoms3D::Catoms3DBlock::setVisible, Catoms3D::Catoms3DBlock::setPositionAndOrientation, Catoms3D::MotionStepEvent::consume, getSkeletonPotentiel.
void Catoms3D::Catoms3DWorld::updateGlData(Catoms3DBlock *blc, bool visible)
References Catoms3D::Catoms3DBlock::getGlBlock, BaseSimulator::World::lock, GlBlock::setVisible, BaseSimulator::World::unlock.
void Catoms3D::Catoms3DWorld::updateGlData(Catoms3DBlock *blc, const Cell3DPosition &position)
References Catoms3D::Catoms3DBlock::getGlBlock, BaseSimulator::World::lock, GlBlock::setPosition, gridToWorldPosition, BaseSimulator::World::unlock.
void Catoms3D::Catoms3DWorld::updateGlData(Catoms3DBlock *blc, const Vecteur &position)
References Catoms3D::Catoms3DBlock::getGlBlock, BaseSimulator::World::lock, GlBlock::setPosition, BaseSimulator::World::unlock.
void Catoms3D::Catoms3DWorld::updateGlData(Catoms3DBlock *blc, const Matrice &mat)
References Catoms3D::Catoms3DBlock::getGlBlock, BaseSimulator::World::lock, Catoms3D::Catoms3DGlBlock::mat, BaseSimulator::World::unlock.
void Catoms3D::Catoms3DWorld::createPopupMenu(int ix, int iy)
References GlutContext::popupMenu, GlutPopupMenuWindow::addButton, GlutWindow::h, GlutPopupMenuWindow::setCenterPosition, GlutContext::screenHeight, GlutPopupMenuWindow::show.
Referenced by getSkeletonPotentiel.
void Catoms3D::Catoms3DWorld::createHelpWindow()
References GlutContext::helpWindow.
Referenced by getSkeletonPotentiel.
virtual Camera* Catoms3D::Catoms3DWorld::getCamera()
References camera, setSelectedFace, menuChoice, disconnectBlock, connectBlock, loadTextures.
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator.
void Catoms3D::Catoms3DWorld::setSelectedFace(int n)
References numSelectedBlock, objBlockForPicking, ObjLoader::ObjLoader::getObjMtlName, numSelectedFace.
Referenced by getCamera.
void Catoms3D::Catoms3DWorld::menuChoice(int n)
References getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, OUTPUT, BaseSimulator::BuildingBlock::blockId, numSelectedFace, deleteBlock.
Referenced by getCamera.
void Catoms3D::Catoms3DWorld::disconnectBlock(Catoms3DBlock *block)
References Catoms3D::Catoms3DBlock::getInterface, P2PNetworkInterface::connectedInterface, setGridPtr, Catoms3D::Catoms3DBlock::position, OUTPUT, Catoms3D::getScheduler, BaseSimulator::Scheduler::now, BaseSimulator::BuildingBlock::blockId.
Referenced by Catoms3D::MotionStartEvent::consume, deleteBlock, getCamera.
void Catoms3D::Catoms3DWorld::connectBlock(Catoms3DBlock *block)
Connect a block to its neighbors after a motion.
References setGridPtr, Catoms3D::Catoms3DBlock::position, OUTPUT, BaseSimulator::BuildingBlock::blockId, linkBlock.
Referenced by Catoms3D::MotionStopEvent::consume, getCamera.
void Catoms3D::Catoms3DWorld::loadTextures(const string &str)
load the background textures (internal)
References idTextureHexa, GlutWindow::loadTexture, idTextureGrid.
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator, getCamera.