Catoms3D::Rotations
bool Catoms3D::Rotations::firstRotation
Referenced by nextStep, init.
short Catoms3D::Rotations::step
Referenced by nextStep, init.
Matrice Catoms3D::Rotations::initialMatrix
Referenced by nextStep, getFinalPositionAndOrientation, init.
Matrice Catoms3D::Rotations::firstStepMatrix
Referenced by Rotations, nextStep, getFinalPositionAndOrientation, init.
Vecteur Catoms3D::Rotations::AB
Referenced by Rotations, nextStep, getFinalPositionAndOrientation.
Vecteur Catoms3D::Rotations::AD
Referenced by Rotations.
Vecteur Catoms3D::Rotations::CB
Referenced by Rotations, nextStep, getFinalPositionAndOrientation.
Vecteur Catoms3D::Rotations::axe1
Referenced by Rotations, nextStep, getFinalPositionAndOrientation.
Vecteur Catoms3D::Rotations::axe2
Referenced by Rotations, nextStep, getFinalPositionAndOrientation.
double Catoms3D::Rotations::angle1
Referenced by Rotations, nextStep, getFinalPositionAndOrientation.
double Catoms3D::Rotations::angle2
Referenced by nextStep, getFinalPositionAndOrientation.
constexpr double Catoms3D::Rotations::angleArticulation
constexpr double Catoms3D::Rotations::coefRayonCourbure
Referenced by nextStep.
Catoms3D::Rotations::Rotations(Catoms3DBlock *mobile, Catoms3DBlock *fixe, const Vecteur &ax1, double ang1, const Vecteur &ax2, double ang2)
Create a couple of rotations.
p : fixed pivot catom ax1 : rotation axe for the first rotation ang1 : rotation angle for the first rotation ax2 : rotation axe for the second rotation ang2 : rotation angle for the second rotation
References Catoms3D::Catoms3DBlock::getGlBlock, Catoms3D::Catoms3DGlBlock::mat, Matrice::inverse, AB, Matrice::setTranslation, axe1, Vecteur::normer, AD, axe2, Matrice::setRotation, angle1, firstStepMatrix, CB.
Catoms3D::Rotations::Rotations()
void Catoms3D::Rotations::init(const Matrice &m)
References firstRotation, step, initialMatrix, firstStepMatrix, Matrice::identity, nextStep, getFinalPositionAndOrientation.
Referenced by Catoms3D::MotionStartEvent::consume.
bool Catoms3D::Rotations::nextStep(Matrice &m)
Return current transformation matrix in m.
m : result matrix Calculate transformation matrix for one more step of rotations m : result matrix true at the end of the animation.
References firstRotation, step, angle1, Catoms3D::nbRotationSteps, OUTPUT, Matrice::setRotation, axe1, coefRayonCourbure, Matrice::setTranslation, AB, initialMatrix, firstStepMatrix, angle2, axe2, CB.
Referenced by Catoms3D::MotionStepEvent::consume, init.
void Catoms3D::Rotations::getFinalPositionAndOrientation(Cell3DPosition &position, short &orientation)
References Matrice::setRotation, angle1, axe1, Matrice::setTranslation, AB, firstStepMatrix, initialMatrix, angle2, axe2, CB, OUTPUT, Catoms3D::getWorld, Catoms3D::Catoms3DWorld::worldToGridPosition, Catoms3D::Catoms3DBlock::getOrientationFromMatrix.
Referenced by Catoms3D::MotionStopEvent::consume, init.