RobotBlocks::RobotBlocksWorld
int RobotBlocks::RobotBlocksWorld::gridSize[3][3]
Referenced by RobotBlocksWorld, addBlock, connectBlock, linkBlock, linkBlocks, glDraw, createPopupMenu, getPresenceMatrix, initTargetGrid.
RobotBlocksBlock** RobotBlocks::RobotBlocksWorld::gridPtrBlocks
Referenced by RobotBlocksWorld, ~RobotBlocksWorld, getPresenceMatrix.
GLfloat RobotBlocks::RobotBlocksWorld::blockSize[3][3]
Referenced by RobotBlocksWorld, glDraw, glDrawId, glDrawIdByMaterial, updateGlData, getBlocksSize.
Camera* RobotBlocks::RobotBlocksWorld::camera
Referenced by RobotBlocksWorld, ~RobotBlocksWorld, getCamera.
ObjLoader::ObjLoader* RobotBlocks::RobotBlocksWorld::objBlock
Referenced by RobotBlocksWorld, ~RobotBlocksWorld, glDraw, glDrawId.
ObjLoader::ObjLoader * RobotBlocks::RobotBlocksWorld::objBlockForPicking
Referenced by RobotBlocksWorld, ~RobotBlocksWorld, glDrawIdByMaterial, setSelectedFace.
ObjLoader::ObjLoader * RobotBlocks::RobotBlocksWorld::objRepere
Referenced by RobotBlocksWorld, ~RobotBlocksWorld, glDraw.
GLuint RobotBlocks::RobotBlocksWorld::idTextureWall
Referenced by RobotBlocksWorld, glDraw, loadTextures.
GLushort RobotBlocks::RobotBlocksWorld::numSelectedFace
Referenced by RobotBlocksWorld, createPopupMenu, menuChoice, setSelectedFace.
GLuint RobotBlocks::RobotBlocksWorld::numSelectedBlock
Referenced by RobotBlocksWorld, createPopupMenu, menuChoice, setSelectedFace.
GLint RobotBlocks::RobotBlocksWorld::menuId
Referenced by RobotBlocksWorld.
presence* RobotBlocks::RobotBlocksWorld::targetGrid
Referenced by RobotBlocksWorld, ~RobotBlocksWorld, initTargetGrid, getTargetGridPtr.
RobotBlocksCapabilities* RobotBlocks::RobotBlocksWorld::capabilities
Referenced by getCapabilities.
RobotBlocks::RobotBlocksWorld::RobotBlocksWorld(int slx, int sly, int slz, int argc, char *argv[])
References OUTPUT, gridSize, gridPtrBlocks, targetGrid, GlutContext::init, idTextureWall, blockSize, objBlock, objBlockForPicking, objRepere, camera, M_PI, Camera::setLightParameters, Camera::setTarget, menuId, numSelectedFace, numSelectedBlock.
Referenced by createWorld.
RobotBlocks::RobotBlocksWorld::~RobotBlocksWorld()
References OUTPUT, gridPtrBlocks, targetGrid, objBlock, objBlockForPicking, objRepere, camera.
void RobotBlocks::RobotBlocksWorld::linkBlock(int ix, int iy, int iz)
References getGridPtr, gridSize, RobotBlocks::NeighborDirection::Top, RobotBlocks::NeighborDirection::Bottom, OUTPUT, BaseSimulator::BuildingBlock::blockId, RobotBlocks::NeighborDirection::Right, RobotBlocks::NeighborDirection::Left, RobotBlocks::NeighborDirection::Front, RobotBlocks::NeighborDirection::Back.
Referenced by connectBlock, linkBlocks.
void RobotBlocks::RobotBlocksWorld::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References BaseSimulator::World::world, RobotBlocksWorld.
Referenced by RobotBlocks::createWorld.
void RobotBlocks::RobotBlocksWorld::deleteWorld()
References BaseSimulator::World::world.
Referenced by RobotBlocks::deleteWorld.
static RobotBlocksWorld* RobotBlocks::RobotBlocksWorld::getWorld()
References BaseSimulator::World::world.
Referenced by RobotBlocks::MotionStartEvent::consume, RobotBlocks::MotionStepEvent::consume, RobotBlocks::MotionStopEvent::consume, RobotBlocks::getWorld.
void RobotBlocks::RobotBlocksWorld::printInfo()
References OUTPUT.
virtual RobotBlocksBlock* RobotBlocks::RobotBlocksWorld::getBlockById(int bId)
References addBlock, deleteBlock.
Referenced by createPopupMenu, menuChoice.
void RobotBlocks::RobotBlocksWorld::addBlock(int blockId, RobotBlocksBlockCode *(*robotBlockCodeBuildingFunction)(RobotBlocksBlock *), const Vecteur &pos, const Color &col, bool master=false)
References BaseSimulator::World::buildingBlocksMap, BaseSimulator::BuildingBlock::blockId, RobotBlocks::getScheduler, BaseSimulator::Scheduler::schedule, BaseSimulator::World::tabGlBlocks, RobotBlocks::RobotBlocksBlock::setGlBlock, RobotBlocks::RobotBlocksBlock::setPosition, RobotBlocks::RobotBlocksBlock::setColor, RobotBlocks::RobotBlocksBlock::isMaster, RobotBlocks::RobotBlocksBlock::position, Vecteur::pt, gridSize, setGridPtr, ERRPUT.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, menuChoice, getBlockById.
void RobotBlocks::RobotBlocksWorld::deleteBlock(RobotBlocksBlock *bb)
References BaseSimulator::BuildingBlock::getState, BaseSimulator::BuildingBlock::ALIVE, RobotBlocks::RobotBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::removeNeighbor, RobotBlocks::RobotBlocksBlock::position, Vecteur::pt, setGridPtr, disconnectBlock, BaseSimulator::World::selectedBlock, RobotBlocks::RobotBlocksBlock::ptrGlBlock, GlutContext::mainWindow, GlutSlidingMainWindow::select, BaseSimulator::World::tabGlBlocks.
Referenced by menuChoice, getBlockById.
void RobotBlocks::RobotBlocksWorld::setBlocksSize(float *siz)
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.
const float* RobotBlocks::RobotBlocksWorld::getBlocksSize()
References blockSize.
void RobotBlocks::RobotBlocksWorld::setGridPtr(int ix, int iy, int iz, RobotBlocksBlock *ptr)
Referenced by RobotBlocks::MotionStopEvent::consume, addBlock, connectBlock, disconnectBlock, deleteBlock.
RobotBlocksBlock* RobotBlocks::RobotBlocksWorld::getGridPtr(int ix, int iy, int iz)
Referenced by linkBlock, createPopupMenu.
presence* RobotBlocks::RobotBlocksWorld::getTargetGridPtr(int *gs)
References targetGrid.
presence RobotBlocks::RobotBlocksWorld::getTargetGrid(int ix, int iy, int iz)
void RobotBlocks::RobotBlocksWorld::setTargetGrid(presence value, int ix, int iy, int iz)
References initTargetGrid.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.
void RobotBlocks::RobotBlocksWorld::initTargetGrid()
References targetGrid, gridSize.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, setTargetGrid.
void RobotBlocks::RobotBlocksWorld::setCapabilities(RobotBlocksCapabilities *capa)
References getPresenceMatrix.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.
void RobotBlocks::RobotBlocksWorld::getPresenceMatrix(const PointRel3D &pos, PresenceMatrix &pm)
References RobotBlocks::PresenceMatrix::grid, RobotBlocks::wallCell, RobotBlocks::PointRel3D::x, gridSize, RobotBlocks::PointRel3D::y, RobotBlocks::PointRel3D::z, gridPtrBlocks, RobotBlocks::fullCell, RobotBlocks::emptyCell.
Referenced by setCapabilities.
RobotBlocksCapabilities* RobotBlocks::RobotBlocksWorld::getCapabilities()
References capabilities, linkBlocks, loadTextures, glDraw, glDrawId, glDrawIdByMaterial, updateGlData, createPopupMenu, createHelpWindow.
void RobotBlocks::RobotBlocksWorld::linkBlocks()
References gridSize, linkBlock.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, menuChoice, getCapabilities.
void RobotBlocks::RobotBlocksWorld::loadTextures(const string &str)
References idTextureWall, GlutWindow::loadTexture.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, getCapabilities.
void RobotBlocks::RobotBlocksWorld::glDraw()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock, enableTexture, idTextureWall, gridSize, objRepere, ObjLoader::ObjLoader::glDraw.
Referenced by getCapabilities.
void RobotBlocks::RobotBlocksWorld::glDrawId()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by getCapabilities.
void RobotBlocks::RobotBlocksWorld::glDrawIdByMaterial()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlockForPicking, BaseSimulator::World::unlock.
Referenced by getCapabilities.
void RobotBlocks::RobotBlocksWorld::updateGlData(RobotBlocksBlock *blc)
References RobotBlocks::RobotBlocksBlock::getGlBlock, BaseSimulator::World::lock, blockSize, RobotBlocks::RobotBlocksBlock::position, Vecteur::pt, GlBlock::setPosition, GlBlock::setColor, RobotBlocks::RobotBlocksBlock::color, BaseSimulator::World::unlock.
Referenced by RobotBlocks::RobotBlocksBlock::setPosition, RobotBlocks::RobotBlocksBlock::setColor, RobotBlocks::RobotBlocksBlock::setPrevNext, RobotBlocks::MotionStepEvent::consume, RobotBlocks::MotionStopEvent::consume, getCapabilities.
void RobotBlocks::RobotBlocksWorld::updateGlData(RobotBlocksBlock *blc, int prev, int next)
References RobotBlocks::RobotBlocksBlock::getGlBlock, BaseSimulator::World::lock, RobotBlocks::RobotBlocksGlBlock::setPrevNext, BaseSimulator::World::unlock.
void RobotBlocks::RobotBlocksWorld::createPopupMenu(int ix, int iy)
References GlutContext::popupMenu, GlutPopupMenuWindow::addButton, GlutWindow::h, getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, numSelectedFace, RobotBlocks::NeighborDirection::Left, RobotBlocks::RobotBlocksBlock::position, getGridPtr, RobotBlocks::NeighborDirection::Right, gridSize, RobotBlocks::NeighborDirection::Front, RobotBlocks::NeighborDirection::Back, RobotBlocks::NeighborDirection::Bottom, RobotBlocks::NeighborDirection::Top, GlutPopupMenuWindow::activate, GlutPopupMenuWindow::setCenterPosition, GlutContext::screenHeight, GlutPopupMenuWindow::show.
Referenced by getCapabilities.
void RobotBlocks::RobotBlocksWorld::createHelpWindow()
References GlutContext::helpWindow.
Referenced by getCapabilities.
virtual Camera* RobotBlocks::RobotBlocksWorld::getCamera()
References camera, setSelectedFace, menuChoice, disconnectBlock, connectBlock.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.
void RobotBlocks::RobotBlocksWorld::setSelectedFace(int n)
References numSelectedBlock, objBlockForPicking, ObjLoader::ObjLoader::getObjMtlName, numSelectedFace, RobotBlocks::NeighborDirection::Top, RobotBlocks::NeighborDirection::Bottom, RobotBlocks::NeighborDirection::Right, RobotBlocks::NeighborDirection::Left, RobotBlocks::NeighborDirection::Front, RobotBlocks::NeighborDirection::Back.
Referenced by getCamera.
void RobotBlocks::RobotBlocksWorld::menuChoice(int n)
References getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, OUTPUT, BaseSimulator::BuildingBlock::blockId, numSelectedFace, RobotBlocks::RobotBlocksBlock::position, RobotBlocks::NeighborDirection::Left, Vecteur::pt, RobotBlocks::NeighborDirection::Right, RobotBlocks::NeighborDirection::Front, RobotBlocks::NeighborDirection::Back, RobotBlocks::NeighborDirection::Bottom, RobotBlocks::NeighborDirection::Top, addBlock, RobotBlocks::RobotBlocksBlock::buildNewBlockCode, RobotBlocks::RobotBlocksBlock::color, linkBlocks, deleteBlock.
Referenced by getCamera.
void RobotBlocks::RobotBlocksWorld::disconnectBlock(RobotBlocksBlock *block)
References RobotBlocks::RobotBlocksBlock::getInterface, P2PNetworkInterface::connectedInterface, RobotBlocks::RobotBlocksBlock::position, Vecteur::pt, setGridPtr, OUTPUT, RobotBlocks::getScheduler, BaseSimulator::Scheduler::now, BaseSimulator::BuildingBlock::blockId.
Referenced by RobotBlocks::MotionStartEvent::consume, deleteBlock, getCamera.
void RobotBlocks::RobotBlocksWorld::connectBlock(RobotBlocksBlock *block)
References RobotBlocks::RobotBlocksBlock::position, Vecteur::pt, setGridPtr, OUTPUT, BaseSimulator::BuildingBlock::blockId, linkBlock, gridSize.
Referenced by RobotBlocks::MotionStopEvent::consume, getCamera.