ObjLoader::ObjLoader
std::vector<ObjData*> ObjLoader::ObjLoader::tabObj
MtlLib* ObjLoader::ObjLoader::mtls
Mtl* ObjLoader::ObjLoader::ptrMtlLighted
void ObjLoader::ObjLoader::numeroPoint(char *str, int &vert, int &norm, int &tex)
ObjLoader::ObjLoader::ObjLoader(const char *rep, const char *titre)
References OUTPUT, ObjLoader::extraire, ObjLoader::Point3::scan, ObjLoader::Point2::scan, ObjLoader::ObjData::objMtl, ERRPUT, ObjLoader::ObjData::nomOriginal, ObjLoader::Sommet::set, ObjLoader::ObjData::addFace, ObjLoader::ObjData::nom, ObjLoader::Mtl::name.
ObjLoader::ObjLoader::~ObjLoader(void)
void ObjLoader::ObjLoader::createVertexArrays()
void ObjLoader::ObjLoader::glDraw(void)
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDraw, BlinkyBlocks::BlinkyBlocksWorld::glDraw, Catoms2D::Catoms2DGlBlock::glDraw, Catoms2D::Catoms2DWorld::glDraw, Catoms3D::Catoms3DGlBlock::glDraw, RobotBlocks::RobotBlocksGlBlock::glDraw, RobotBlocks::RobotBlocksWorld::glDraw, SmartBlocks::SmartBlocksGlBlock::glDraw, SmartBlocks::SmartBlocksGlBlock::glDrawId, SmartBlocks::SmartBlocksWorld::glDraw.
void ObjLoader::ObjLoader::glDrawIdByMaterial(int &i)
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDrawIdByMaterial, Catoms2D::Catoms2DGlBlock::glDrawIdByMaterial, Catoms3D::Catoms3DGlBlock::glDrawIdByMaterial, RobotBlocks::RobotBlocksGlBlock::glDrawIdByMaterial.
void ObjLoader::ObjLoader::glDrawId(int &i)
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDrawId, Catoms2D::Catoms2DGlBlock::glDrawId, Catoms3D::Catoms3DGlBlock::glDrawId, RobotBlocks::RobotBlocksGlBlock::glDrawId.
void ObjLoader::ObjLoader::setLightedColor(GLfloat *color)
Referenced by BlinkyBlocks::BlinkyBlocksGlBlock::glDraw, Catoms2D::Catoms2DGlBlock::glDraw, Catoms3D::Catoms3DGlBlock::glDraw, RobotBlocks::RobotBlocksGlBlock::glDraw, SmartBlocks::SmartBlocksGlBlock::glDraw.
string ObjLoader::ObjLoader::getObjMtlName(int pos)
Referenced by BlinkyBlocks::BlinkyBlocksWorld::setSelectedFace, Catoms2D::Catoms2DWorld::setSelectedFace, Catoms3D::Catoms3DWorld::setSelectedFace, RobotBlocks::RobotBlocksWorld::setSelectedFace.