GlutSlidingDebugWindow
int GlutSlidingDebugWindow::openingLevel
int GlutSlidingDebugWindow::debugId
GlutButton* GlutSlidingDebugWindow::buttonOpen
GlutButton * GlutSlidingDebugWindow::buttonClose
GlutSlider* GlutSlidingDebugWindow::slider
GlutInputWindow* GlutSlidingDebugWindow::input
vector<BlockDebugData*> GlutSlidingDebugWindow::tabDebug
GlutSlidingDebugWindow::GlutSlidingDebugWindow(GLint px, GLint py, GLint pw, GLint ph, const char *titreTexture)
References ID_SD_BUTTON_OPEN, ID_SD_BUTTON_CLOSE, ID_SD_SLD, ID_SD_INPUT.
GlutSlidingDebugWindow::~GlutSlidingDebugWindow()
int GlutSlidingDebugWindow::mouseFunc(int button, int state, int mx, int my)
References GlutWindow::mouseFunc, ID_SD_BUTTON_OPEN, GlutWindow::x, GlutWindow::w, GlutButton::activate, ID_SD_BUTTON_CLOSE, ID_SD_INPUT, GlutInputWindow::hasFocus, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::getMode, SCHEDULER_MODE_DEBUG.
Referenced by GlutContext::reshapeFunc.
int GlutSlidingDebugWindow::keyFunc(int charcode)
References GlutWindow::children, GlutWindow::id, GlutInputWindow::getTextAndClear, GlutInputWindow::hasFocus, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::debug, LIGHTBLUE, YELLOW.
Referenced by GlutContext::reshapeFunc.
void GlutSlidingDebugWindow::reshapeFunc(int wx, int wy, int mw, int mh)
References GlutWindow::setGeometry, GlutSlider::update.
Referenced by GlutContext::reshapeFunc.
void GlutSlidingDebugWindow::glDraw()
References GlutWindow::bindTexture, GlutWindow::x, GlutWindow::y, GlutWindow::w, GlutWindow::h, BaseSimulator::getScheduler, BaseSimulator::Scheduler::now, GlutWindow::drawString, GlutInputWindow::hasFocus, GlutWindow::glDraw.
Referenced by GlutContext::reshapeFunc.
bool GlutSlidingDebugWindow::isOpened()