MeldProcess::MeldProcessVM
BaseSimulator::BuildingBlock* MeldProcess::MeldProcessVM::hostBlock
Referenced by dateHasBeenReachedByAll, equilibrium, broadcastDebugCommand.
uint64_t MeldProcess::MeldProcessVM::currentLocalDate
Referenced by dateHasBeenReachedByAll.
bool MeldProcess::MeldProcessVM::hasWork
Referenced by dateHasBeenReachedByAll, equilibrium.
bool MeldProcess::MeldProcessVM::polling
Referenced by dateHasBeenReachedByAll.
boost::interprocess::interprocess_mutex MeldProcess::MeldProcessVM::mutex_ios
boost::asio::io_service * MeldProcess::MeldProcessVM::ios
tcp::acceptor * MeldProcess::MeldProcessVM::acceptor
string MeldProcess::MeldProcessVM::vmPath
string MeldProcess::MeldProcessVM::programPath
bool MeldProcess::MeldProcessVM::debugging
map< int, MeldProcessVM * > MeldProcess::MeldProcessVM::vmMap
boost::shared_ptr<tcp::socket> MeldProcess::MeldProcessVM::socket
pid_t MeldProcess::MeldProcessVM::pid
commandType MeldProcess::MeldProcessVM::inBuffer[VM_COMMAND_MAX_LENGHT][VM_COMMAND_MAX_LENGHT]
commandType MeldProcess::MeldProcessVM::nbSentCommands
bool MeldProcess::MeldProcessVM::idSent
bool MeldProcess::MeldProcessVM::deterministicSet
tcp::socket& MeldProcess::MeldProcessVM::getSocket()
void MeldProcess::MeldProcessVM::terminate()
MeldProcess::MeldProcessVM::MeldProcessVM(BaseSimulator::BuildingBlock *bb)
References BaseSimulator::BuildingBlock::blockId, OUTPUT, VM_COMMAND_MAX_LENGHT, ERRPUT, log_file, MeldProcess::checkForReceivedVMCommands.
MeldProcess::MeldProcessVM::~MeldProcessVM()
void MeldProcess::MeldProcessVM::asyncAcceptHandler(boost::system::error_code &error, bool *connected)
int MeldProcess::MeldProcessVM::sendCommand(VMCommand &command)
References ERRPUT, MeldProcess::VMCommand::getType, VM_COMMAND_DEBUG, MeldProcess::VMCommand::getData, MeldProcess::VMCommand::getSize.
Referenced by MeldProcess::MeldProcessDebugger::sendCmd, broadcastDebugCommand, sendCommand.
void MeldProcess::MeldProcessVM::asyncReadCommand()
References ERRPUT.
void MeldProcess::MeldProcessVM::asyncReadCommandHandler(const boost::system::error_code &error, std::size_t bytes_transferred)
References ERRPUT.
void MeldProcess::MeldProcessVM::handleInBuffer()
void MeldProcess::MeldProcessVM::handle_write(const boost::system::error_code &error)
void MeldProcess::MeldProcessVM::killProcess()
void MeldProcess::MeldProcessVM::closeSocket()
void MeldProcess::MeldProcessVM::handleDeterministicMode(VMCommand &command)
References BlinkyBlocks::getScheduler, MeldProcess::VMCommand::getType, VM_COMMAND_STOP.
void MeldProcess::MeldProcessVM::handleCommand(VMCommand &command)
References BlinkyBlocks::getScheduler, MeldProcess::VMCommand::getTimestamp, BaseSimulator::Scheduler::getMode, SCHEDULER_MODE_FASTEST, BaseSimulator::Scheduler::now, MeldProcess::VMCommand::getType, VM_COMMAND_SET_COLOR, MeldProcess::VMCommand::getData, BaseSimulator::Scheduler::scheduleLock, VM_COMMAND_SEND_MESSAGE, MeldProcess::SendMessageVMCommand::getDestId, BaseSimulator::Scheduler::trace, ERRPUT, VM_COMMAND_DEBUG, MeldProcess::VMCommand::copyData, MeldProcess::handleDebugCommand, VM_COMMAND_WORK_END, VM_COMMAND_TIME_INFO, VM_COMMAND_POLL_START.
void MeldProcess::MeldProcessVM::setCurrentLocalDate(uint64_t t)
void MeldProcess::MeldProcessVM::setPolling(bool b)
static bool MeldProcess::MeldProcessVM::isInDebuggingMode()
References MeldProcess::sendCommand.
Referenced by MeldProcess::MeldProcessDebugger::print, BaseSimulator::Simulator::~Simulator.
void MeldProcess::MeldProcessVM::setConfiguration(string v, string p, bool d)
void MeldProcess::MeldProcessVM::createServer(int p)
void MeldProcess::MeldProcessVM::deleteServer()
void MeldProcess::MeldProcessVM::checkForReceivedCommands()
void MeldProcess::MeldProcessVM::waitForOneCommand()
bool MeldProcess::MeldProcessVM::dateHasBeenReachedByAll(uint64_t date)
References hostBlock, BaseSimulator::BuildingBlock::getState, hasWork, polling, currentLocalDate.
bool MeldProcess::MeldProcessVM::equilibrium()
References hostBlock, BaseSimulator::BuildingBlock::getState, hasWork.
int MeldProcess::MeldProcessVM::broadcastDebugCommand(DebbuggerVMCommand &c)
References hostBlock, BaseSimulator::BuildingBlock::blockCode, BaseSimulator::BlockCode::init, sendCommand.
Referenced by MeldProcess::MeldProcessDebugger::sendCmd.
int MeldProcess::MeldProcessVM::sendCommand(int id, VMCommand &c)
References BaseSimulator::getWorld, BaseSimulator::World::getBlockById, BaseSimulator::BuildingBlock::blockCode, BaseSimulator::BlockCode::init, sendCommand.
void MeldProcess::MeldProcessVM::closeAllSockets()
MeldProcessVM * MeldProcess::MeldProcessVM::getMeldProcessVMById(int id)