BaseSimulator::Simulator
Type
Simulator::Type BaseSimulator::Simulator::type
Simulator * BaseSimulator::Simulator::simulator
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::createSimulator, BlinkyBlocks::BlinkyBlocksSimulator::deleteSimulator, Catoms2D::Catoms2DSimulator::createSimulator, Catoms2D::Catoms2DSimulator::deleteSimulator, Catoms3D::Catoms3DSimulator::createSimulator, Catoms3D::Catoms3DSimulator::deleteSimulator, MultiCores::MultiCoresSimulator::createSimulator, MultiCores::MultiCoresSimulator::deleteSimulator, RobotBlocks::RobotBlocksSimulator::createSimulator, RobotBlocks::RobotBlocksSimulator::deleteSimulator, Simulator, SmartBlocks::SmartBlocksSimulator::createSimulator, SmartBlocks::SmartBlocksSimulator::deleteSimulator.
Scheduler* BaseSimulator::Simulator::scheduler
TiXmlDocument* BaseSimulator::Simulator::xmlDoc
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, Simulator, ~Simulator, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
TiXmlNode* BaseSimulator::Simulator::xmlWorldNode
Referenced by Simulator.
CommandLine BaseSimulator::Simulator::cmdLine
Referenced by Simulator.
static Simulator* BaseSimulator::Simulator::getSimulator()
static void BaseSimulator::Simulator::setType(Type t)
static Type BaseSimulator::Simulator::getType()
Referenced by BlinkyBlocks::BlinkyBlocksBlock::stop, BlinkyBlocks::createScheduler, BlinkyBlocks::deleteScheduler, Simulator, ~Simulator.
CommandLine& BaseSimulator::Simulator::getCmdLine()
virtual void BaseSimulator::Simulator::printInfo()
BaseSimulator::Simulator::Simulator(int argc, char *argv[])
References BaseSimulator::simulator, simulator, ERRPUT, xmlWorldNode, OUTPUT, cmdLine, CommandLine::getConfigFile, xmlDoc, getType, MELDPROCESS, CommandLine::getProgramPath, CommandLine::getMeldDebugger, MeldProcess::setVMConfiguration, MeldProcess::createVMServer, MeldProcess::createDebugger, MELDINTERPRET, MeldInterpret::MeldInterpretVM::setConfiguration.
BaseSimulator::Simulator::~Simulator()
References OUTPUT, xmlDoc, getType, MELDPROCESS, MeldProcess::MeldProcessVM::isInDebuggingMode, MeldProcess::deleteDebugger, MeldProcess::deleteVMServer, MELDINTERPRET, BaseSimulator::deleteScheduler, BaseSimulator::deleteWorld.