Catoms2D::Catoms2DWorld
int Catoms2D::Catoms2DWorld::gridSize[3][3]
Referenced by Catoms2DWorld, addBlock, connectBlock, linkBlock, linkBlocks, glDraw, createPopupMenu, getPresenceMatrix, initTargetGrid, generateRandom, getGridSize.
Catoms2DBlock** Catoms2D::Catoms2DWorld::gridPtrBlocks
Referenced by Catoms2DWorld, ~Catoms2DWorld, getPresenceMatrix.
GLfloat Catoms2D::Catoms2DWorld::blockSize[3][3]
Referenced by Catoms2DWorld, glDraw, glDrawId, glDrawIdByMaterial, worldToGridPosition, gridToWorldPosition, areNeighborsWorldPos, getBlocksSize.
Camera* Catoms2D::Catoms2DWorld::camera
Referenced by Catoms2DWorld, ~Catoms2DWorld, getCamera.
ObjLoader::ObjLoader* Catoms2D::Catoms2DWorld::objBlock
Referenced by Catoms2DWorld, ~Catoms2DWorld, glDraw, glDrawId.
ObjLoader::ObjLoader * Catoms2D::Catoms2DWorld::objBlockForPicking
Referenced by Catoms2DWorld, ~Catoms2DWorld, glDrawIdByMaterial, setSelectedFace.
ObjLoader::ObjLoader * Catoms2D::Catoms2DWorld::objRepere
Referenced by Catoms2DWorld, ~Catoms2DWorld, glDraw.
GLuint Catoms2D::Catoms2DWorld::idTextureHexa
Referenced by Catoms2DWorld, glDraw, loadTextures.
GLuint Catoms2D::Catoms2DWorld::idTextureLines
Referenced by Catoms2DWorld, glDraw, loadTextures.
GLushort Catoms2D::Catoms2DWorld::numSelectedFace
Referenced by Catoms2DWorld, createPopupMenu, menuChoice, setSelectedFace.
GLuint Catoms2D::Catoms2DWorld::numSelectedBlock
Referenced by Catoms2DWorld, createPopupMenu, menuChoice, setSelectedFace.
GLint Catoms2D::Catoms2DWorld::menuId
Referenced by Catoms2DWorld.
presence* Catoms2D::Catoms2DWorld::targetGrid
Referenced by Catoms2DWorld, ~Catoms2DWorld, initTargetGrid, getTargetGridPtr.
Catoms2DCapabilities* Catoms2D::Catoms2DWorld::capabilities
Referenced by getCapabilities.
Catoms2D::Catoms2DWorld::Catoms2DWorld(int slx, int sly, int slz, int argc, char *argv[])
References OUTPUT, gridSize, gridPtrBlocks, targetGrid, GlutContext::init, idTextureHexa, idTextureLines, blockSize, objBlock, objBlockForPicking, objRepere, camera, M_PI, Camera::setLightParameters, Camera::setTarget, menuId, numSelectedFace, numSelectedBlock.
Referenced by createWorld.
Catoms2D::Catoms2DWorld::~Catoms2DWorld()
References OUTPUT, gridPtrBlocks, targetGrid, objBlock, objBlockForPicking, objRepere, camera.
void Catoms2D::Catoms2DWorld::linkBlock(int ix, int iy, int iz)
References getGridPtr, OUTPUT, BaseSimulator::BuildingBlock::blockId, gridSize, Catoms2D::NeighborDirection::Right, Catoms2D::NeighborDirection::Left, Catoms2D::NeighborDirection::TopLeft, Catoms2D::NeighborDirection::BottomRight, Catoms2D::NeighborDirection::BottomLeft, Catoms2D::NeighborDirection::TopRight.
Referenced by connectBlock, linkBlocks.
void Catoms2D::Catoms2DWorld::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References BaseSimulator::World::world, Catoms2DWorld.
Referenced by Catoms2D::createWorld.
void Catoms2D::Catoms2DWorld::deleteWorld()
References BaseSimulator::World::world.
Referenced by Catoms2D::deleteWorld.
static Catoms2DWorld* Catoms2D::Catoms2DWorld::getWorld()
References BaseSimulator::World::world.
Referenced by Catoms2D::MotionStartEvent::consume, Catoms2D::MotionStepEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::getWorld.
void Catoms2D::Catoms2DWorld::printInfo()
References OUTPUT.
virtual Catoms2DBlock* Catoms2D::Catoms2DWorld::getBlockById(int bId)
References addBlock, deleteBlock.
Referenced by createPopupMenu, menuChoice.
void Catoms2D::Catoms2DWorld::addBlock(int blockId, Catoms2DBlockCode *(*robotBlockCodeBuildingFunction)(Catoms2DBlock *), const Vecteur &pos, const Color &col, bool master=false)
References BaseSimulator::World::buildingBlocksMap, BaseSimulator::BuildingBlock::blockId, Catoms2D::getScheduler, BaseSimulator::Scheduler::schedule, BaseSimulator::World::tabGlBlocks, Catoms2D::Catoms2DBlock::setGlBlock, Catoms2D::Catoms2DBlock::setPosition, Catoms2D::Catoms2DBlock::setColor, Catoms2D::Catoms2DBlock::isMaster, Catoms2D::Catoms2DBlock::position, Vecteur::pt, gridSize, setGridPtr, ERRPUT.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator, menuChoice, generateRandom, getBlockById.
void Catoms2D::Catoms2DWorld::deleteBlock(Catoms2DBlock *bb)
References BaseSimulator::BuildingBlock::getState, BaseSimulator::BuildingBlock::ALIVE, Catoms2D::Catoms2DBlock::getInterface, P2PNetworkInterface::connectedInterface, P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::removeNeighbor, Catoms2D::Catoms2DBlock::position, Vecteur::pt, setGridPtr, disconnectBlock, BaseSimulator::World::selectedBlock, Catoms2D::Catoms2DBlock::ptrGlBlock, GlutContext::mainWindow, GlutSlidingMainWindow::select, BaseSimulator::World::tabGlBlocks.
Referenced by menuChoice, getBlockById.
void Catoms2D::Catoms2DWorld::setBlocksSize(float *siz)
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator.
const float* Catoms2D::Catoms2DWorld::getBlocksSize()
References blockSize.
void Catoms2D::Catoms2DWorld::setGridPtr(int ix, int iy, int iz, Catoms2DBlock *ptr)
Referenced by Catoms2D::MotionStopEvent::consume, addBlock, connectBlock, disconnectBlock, deleteBlock.
Catoms2DBlock* Catoms2D::Catoms2DWorld::getGridPtr(int ix, int iy, int iz)
Referenced by linkBlock, createPopupMenu, generateRandom.
int* Catoms2D::Catoms2DWorld::getGridSize()
References gridSize.
presence* Catoms2D::Catoms2DWorld::getTargetGridPtr(int *gs)
References targetGrid.
presence Catoms2D::Catoms2DWorld::getTargetGrid(int ix, int iy, int iz)
void Catoms2D::Catoms2DWorld::setTargetGrid(presence value, int ix, int iy, int iz)
References initTargetGrid.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator.
void Catoms2D::Catoms2DWorld::initTargetGrid()
References targetGrid, gridSize, Catoms2D::emptyCell.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator, setTargetGrid.
void Catoms2D::Catoms2DWorld::setCapabilities(Catoms2DCapabilities *capa)
References getPresenceMatrix.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator.
void Catoms2D::Catoms2DWorld::getPresenceMatrix(const PointRel3D &pos, PresenceMatrix &pm)
References Catoms2D::PresenceMatrix::grid, Catoms2D::wallCell, Catoms2D::PointRel3D::x, gridSize, Catoms2D::PointRel3D::y, Catoms2D::PointRel3D::z, gridPtrBlocks, Catoms2D::fullCell, Catoms2D::emptyCell.
Referenced by setCapabilities.
Catoms2DCapabilities* Catoms2D::Catoms2DWorld::getCapabilities()
References capabilities, linkBlocks, loadTextures, worldToGridPosition, gridToWorldPosition, areNeighborsWorldPos, areNeighborsGridPos, glDraw, glDrawId, glDrawIdByMaterial, updateGlData, createPopupMenu, createHelpWindow.
void Catoms2D::Catoms2DWorld::linkBlocks()
References gridSize, linkBlock.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator, menuChoice, getCapabilities.
void Catoms2D::Catoms2DWorld::loadTextures(const string &str)
References idTextureHexa, GlutWindow::loadTexture, idTextureLines.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator, getCapabilities.
Vecteur Catoms2D::Catoms2DWorld::worldToGridPosition(Vecteur &pos)
References Vecteur::pt, blockSize.
Referenced by Catoms2D::MotionStopEvent::consume, getCapabilities.
Vecteur Catoms2D::Catoms2DWorld::gridToWorldPosition(Vecteur &pos)
References Vecteur::pt, blockSize.
Referenced by updateGlData, areNeighborsGridPos, getCapabilities.
bool Catoms2D::Catoms2DWorld::areNeighborsWorldPos(Vecteur &pos1, Vecteur &pos2)
References blockSize.
Referenced by areNeighborsGridPos, getCapabilities.
bool Catoms2D::Catoms2DWorld::areNeighborsGridPos(Vecteur &pos1, Vecteur &pos2)
References gridToWorldPosition, areNeighborsWorldPos.
Referenced by getCapabilities.
void Catoms2D::Catoms2DWorld::glDraw()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock, enableTexture, idTextureLines, gridSize, idTextureHexa, objRepere, ObjLoader::ObjLoader::glDraw.
Referenced by getCapabilities.
void Catoms2D::Catoms2DWorld::glDrawId()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlock, BaseSimulator::World::unlock.
Referenced by getCapabilities.
void Catoms2D::Catoms2DWorld::glDrawIdByMaterial()
References blockSize, BaseSimulator::World::tabGlBlocks, BaseSimulator::World::lock, objBlockForPicking, BaseSimulator::World::unlock.
Referenced by getCapabilities.
void Catoms2D::Catoms2DWorld::updateGlData(Catoms2DBlock *blc)
References gridToWorldPosition, Catoms2D::Catoms2DBlock::position.
Referenced by Catoms2D::Catoms2DBlock::setPosition, Catoms2D::Catoms2DBlock::setColor, Catoms2D::MotionStepEvent::consume, getCapabilities.
void Catoms2D::Catoms2DWorld::updateGlData(Catoms2DBlock *blc, const Vecteur &position)
References Catoms2D::Catoms2DBlock::getGlBlock, BaseSimulator::World::lock, GlBlock::setPosition, GlBlock::setColor, Catoms2D::Catoms2DBlock::color, BaseSimulator::World::unlock.
void Catoms2D::Catoms2DWorld::updateGlData(Catoms2DBlock *blc, const Vecteur &position, double angle)
References Catoms2D::Catoms2DBlock::getGlBlock, BaseSimulator::World::lock, Catoms2D::Catoms2DGlBlock::setAngle, GlBlock::setPosition, GlBlock::setColor, Catoms2D::Catoms2DBlock::color, BaseSimulator::World::unlock.
void Catoms2D::Catoms2DWorld::createPopupMenu(int ix, int iy)
References GlutContext::popupMenu, GlutPopupMenuWindow::addButton, GlutWindow::h, getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, numSelectedFace, Catoms2D::NeighborDirection::Left, Catoms2D::Catoms2DBlock::position, getGridPtr, Catoms2D::NeighborDirection::Right, gridSize, Catoms2D::NeighborDirection::BottomLeft, Catoms2D::NeighborDirection::TopLeft, Catoms2D::NeighborDirection::BottomRight, Catoms2D::NeighborDirection::TopRight, GlutPopupMenuWindow::activate, GlutPopupMenuWindow::setCenterPosition, GlutContext::screenHeight, GlutPopupMenuWindow::show.
Referenced by getCapabilities.
void Catoms2D::Catoms2DWorld::createHelpWindow()
References GlutContext::helpWindow.
Referenced by getCapabilities.
virtual Camera* Catoms2D::Catoms2DWorld::getCamera()
References camera, setSelectedFace, menuChoice, disconnectBlock, connectBlock, generateRandom, extractConfig.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator.
void Catoms2D::Catoms2DWorld::setSelectedFace(int n)
References numSelectedBlock, objBlockForPicking, ObjLoader::ObjLoader::getObjMtlName, numSelectedFace.
Referenced by getCamera.
void Catoms2D::Catoms2DWorld::menuChoice(int n)
References getBlockById, BaseSimulator::World::tabGlBlocks, numSelectedBlock, OUTPUT, BaseSimulator::BuildingBlock::blockId, numSelectedFace, Catoms2D::Catoms2DBlock::getPosition, addBlock, Catoms2D::Catoms2DBlock::buildNewBlockCode, Catoms2D::Catoms2DBlock::color, linkBlocks, deleteBlock.
Referenced by getCamera.
void Catoms2D::Catoms2DWorld::disconnectBlock(Catoms2DBlock *block)
References Catoms2D::Catoms2DBlock::getInterface, P2PNetworkInterface::connectedInterface, Catoms2D::Catoms2DBlock::position, Vecteur::pt, setGridPtr, OUTPUT, Catoms2D::getScheduler, BaseSimulator::Scheduler::now, BaseSimulator::BuildingBlock::blockId.
Referenced by Catoms2D::MotionStartEvent::consume, deleteBlock, getCamera.
void Catoms2D::Catoms2DWorld::connectBlock(Catoms2DBlock *block)
References Catoms2D::Catoms2DBlock::position, Vecteur::pt, setGridPtr, OUTPUT, BaseSimulator::BuildingBlock::blockId, linkBlock, gridSize.
Referenced by Catoms2D::MotionStopEvent::consume, getCamera.
void Catoms2D::Catoms2DWorld::generateRandom(int n)
References BaseSimulator::World::generateIds, Vecteur::pt, gridSize, addBlock, Catoms2D::Catoms2DSimulator::buildNewBlockCode, DARKGREY, BaseSimulator::World::world, BaseSimulator::World::getBlockById, Catoms2D::Catoms2DBlock::position, Catoms2D::NeighborDirection::Right, Catoms2D::NeighborDirection::Left, Catoms2D::NeighborDirection::BottomLeft, Catoms2D::NeighborDirection::BottomRight, Catoms2D::NeighborDirection::TopLeft, Catoms2D::NeighborDirection::TopRight, getGridPtr, Catoms2D::Catoms2DBlock::buildNewBlockCode.
Referenced by getCamera.
void Catoms2D::Catoms2DWorld::extractConfig()
References BaseSimulator::World::buildingBlocksMap, Catoms2D::Catoms2DBlock::position.
Referenced by getCamera.