Catoms2D::Catoms2DGlBlock
double Catoms2D::Catoms2DGlBlock::angle
orientation angle in degree around Y axis
Referenced by Catoms2D::Catoms2DBlock::setColor, Catoms2D::MotionStepEvent::consume, Catoms2DGlBlock, glDraw.
Catoms2D::Catoms2DGlBlock::Catoms2DGlBlock(int id)
References angle.
Catoms2D::Catoms2DGlBlock::~Catoms2DGlBlock()
string Catoms2D::Catoms2DGlBlock::getInfo()
References GlBlock::blockId, GlBlock::position, GlBlock::color.
void Catoms2D::Catoms2DGlBlock::setAngle(double a)
References glDraw, glDrawId, glDrawIdByMaterial.
Referenced by Catoms2D::Catoms2DWorld::updateGlData.
void Catoms2D::Catoms2DGlBlock::glDraw(ObjLoader::ObjLoader *ptrObj)
References GlBlock::position, angle, GlBlock::isHighlighted, GlBlock::color, ObjLoader::ObjLoader::setLightedColor, ObjLoader::ObjLoader::glDraw.
Referenced by setAngle.
void Catoms2D::Catoms2DGlBlock::glDrawId(ObjLoader::ObjLoader *ptrObj, int &n)
References GlBlock::position, ObjLoader::ObjLoader::glDrawId.
Referenced by setAngle.
void Catoms2D::Catoms2DGlBlock::glDrawIdByMaterial(ObjLoader::ObjLoader *ptrObj, int &n)
References GlBlock::position, ObjLoader::ObjLoader::glDrawIdByMaterial.
Referenced by setAngle.