BaseSimulator::Scheduler
State
Scheduler * BaseSimulator::Scheduler::scheduler
Referenced by MultiCores::MultiCoresScheduler::createScheduler, MultiCores::MultiCoresScheduler::deleteScheduler, SmartBlocks::SmartBlocksScheduler::getScheduler.
int BaseSimulator::Scheduler::schedulerMode
Referenced by Catoms2D::Catoms2DScheduler::start, Catoms3D::Catoms3DScheduler::start, MultiCores::MultiCoresScheduler::startPaused, RobotBlocks::RobotBlocksScheduler::start, SmartBlocks::SmartBlocksScheduler::start.
boost::interprocess::interprocess_semaphore* BaseSimulator::Scheduler::sem_schedulerStart
Referenced by SmartBlocks::SmartBlocksScheduler::start.
boost::thread* BaseSimulator::Scheduler::schedulerThread
vector<Keyword*> BaseSimulator::Scheduler::tabKeywords
uint64_t BaseSimulator::Scheduler::currentDate
Referenced by MultiCores::MultiCoresScheduler::startPaused.
uint64_t BaseSimulator::Scheduler::maximumDate
Referenced by MultiCores::MultiCoresScheduler::startPaused.
multimap<uint64_t,EventPtr> BaseSimulator::Scheduler::eventsMap
Referenced by MultiCores::MultiCoresScheduler::startPaused.
int BaseSimulator::Scheduler::eventsMapSize
Referenced by MultiCores::MultiCoresScheduler::startPaused.
int BaseSimulator::Scheduler::largestEventsMapSize
Referenced by MultiCores::MultiCoresScheduler::startPaused.
boost::interprocess::interprocess_mutex BaseSimulator::Scheduler::mutex_schedule
boost::interprocess::interprocess_mutex BaseSimulator::Scheduler::mutex_trace
uint64_t BaseSimulator::Scheduler::debugDate
State BaseSimulator::Scheduler::state
Referenced by GlutContext::reshapeFunc.
BaseSimulator::Scheduler::Scheduler()
References OUTPUT, ERRPUT.
BaseSimulator::Scheduler::~Scheduler()
References OUTPUT.
static Scheduler* BaseSimulator::Scheduler::getScheduler()
static void BaseSimulator::Scheduler::deleteScheduler()
void BaseSimulator::Scheduler::setMaximumDate(uint64_t tmax)
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void BaseSimulator::Scheduler::printInfo()
int BaseSimulator::Scheduler::getMode()
References WHITE.
Referenced by GlutSlidingDebugWindow::mouseFunc, MeldProcess::MeldProcessVM::handleCommand.
bool BaseSimulator::Scheduler::schedule(Event *ev)
References Event::id, OUTPUT.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::addBlock, BaseSimulator::BuildingBlock::scheduleLocalEvent, BaseSimulator::BuildingBlock::processLocalEvent, Catoms2D::Catoms2DBlock::startMove, Catoms2D::MotionStartEvent::consume, Catoms2D::MotionStepEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::GenericCodeBlock::sendMessage, Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors, Catoms2D::Catoms2DWorld::addBlock, Catoms3D::MotionStartEvent::consume, Catoms3D::MotionStepEvent::consume, Catoms3D::MotionStopEvent::consume, Catoms3D::Catoms3DWorld::addBlock, MeldInterpret::MeldInterpretVM::setLED, MultiCores::MultiCoresScheduler::waitForVMMessage, MultiCores::MultiCoresWorld::addBlock, P2PNetworkInterface::send, P2PNetworkInterface::addToOutgoingBuffer, RobotBlocks::MotionStartEvent::consume, RobotBlocks::MotionStepEvent::consume, RobotBlocks::MotionStopEvent::consume, RobotBlocks::GenericCodeBlock::sendMessage, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::RobotBlocksWorld::addBlock, SmartBlocks::MotionStartEvent::consume, SmartBlocks::MotionStepEvent::consume, SmartBlocks::MotionStopEvent::consume, SmartBlocks::SmartBlocksWorld::addBlock.
bool BaseSimulator::Scheduler::scheduleLock(Event *ev)
Referenced by BlinkyBlocks::BlinkyBlocksBlock::tap, BlinkyBlocks::BlinkyBlocksBlock::accel, BlinkyBlocks::BlinkyBlocksBlock::shake, BlinkyBlocks::BlinkyBlocksBlock::addNeighbor, BlinkyBlocks::BlinkyBlocksBlock::removeNeighbor, BlinkyBlocks::BlinkyBlocksBlock::stop, MeldProcess::MeldProcessScheduler::pause, MeldProcess::MeldProcessVM::handleCommand.
uint64_t BaseSimulator::Scheduler::now()
Referenced by BaseSimulator::BuildingBlock::scheduleLocalEvent, BaseSimulator::BuildingBlock::processLocalEvent, Catoms2D::MotionStartEvent::consume, Catoms2D::MotionStepEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::GenericCodeBlock::sendMessage, Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms3D::MotionStartEvent::consume, Catoms3D::MotionStepEvent::consume, Catoms3D::MotionStopEvent::consume, Catoms3D::Catoms3DWorld::disconnectBlock, BaseSimulator::Clock::Clock, BaseSimulator::Clock::cleanReferencePoints, NetworkInterfaceStopTransmittingEvent::consume, GlutSlidingMainWindow::glDraw, GlutSlidingDebugWindow::glDraw, MeldProcess::MeldProcessVM::handleCommand, MeldProcess::VMCommand::VMCommand, MultiCores::MultiCoresScheduler::waitForVMMessage, P2PNetworkInterface::addToOutgoingBuffer, P2PNetworkInterface::send, GlutContext::addTrace, RobotBlocks::MotionStartEvent::consume, RobotBlocks::MotionStepEvent::consume, RobotBlocks::MotionStopEvent::consume, RobotBlocks::GenericCodeBlock::sendMessage, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::RobotBlocksWorld::disconnectBlock, SmartBlocks::MotionStartEvent::consume, SmartBlocks::MotionStepEvent::consume, SmartBlocks::MotionStopEvent::consume.
void BaseSimulator::Scheduler::trace(string message, int id=-1, const Color &color=WHITE)
References GlutContext::addTrace, OUTPUT.
Referenced by BaseSimulator::BuildingBlock::processLocalEvent, Catoms2D::MotionStopEvent::consume, Catoms3D::MotionStopEvent::consume, MeldProcess::MeldProcessVM::handleCommand, MultiCores::MultiCoresScheduler::startPaused, MultiCores::MultiCoresScheduler::waitForVMMessage, P2PNetworkInterface::addToOutgoingBuffer, P2PNetworkInterface::send, RobotBlocks::MotionStopEvent::consume, ConsoleStream::flush.
void BaseSimulator::Scheduler::removeEventsToBlock(BuildingBlock *bb)
References OUTPUT.
void BaseSimulator::Scheduler::lock()
void BaseSimulator::Scheduler::unlock()
virtual void BaseSimulator::Scheduler::start(int)
Referenced by GlutContext::deleteContext, GlutContext::reshapeFunc, GlutContext::mainLoop.
void BaseSimulator::Scheduler::stop(uint64_t date)
References SCHEDULER_MODE_DEBUG.
Referenced by GlutContext::reshapeFunc, GlutContext::mainLoop.
void BaseSimulator::Scheduler::restart()
References SCHEDULER_MODE_REALTIME.
bool BaseSimulator::Scheduler::debug(const string &command, int &id, string &result)
Referenced by GlutSlidingDebugWindow::keyFunc.
void BaseSimulator::Scheduler::setState(State s)
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, CodeEndSimulationEvent::consume, MeldInterpret::VMDebugPauseSimEvent::consume, MeldProcess::VMDebugPauseSimEvent::consume.
State BaseSimulator::Scheduler::getState()
int BaseSimulator::Scheduler::getNbreMessages()
References Event::getNextId.
Referenced by SmartBlocks::SmartBlocksWorld::printStats.
void BaseSimulator::Scheduler::waitForSchedulerEnd()
Referenced by GlutContext::mainLoop.
void BaseSimulator::Scheduler::addKeyword(Keyword *kw)
void BaseSimulator::Scheduler::removeKeywords()