GlutHelpWindow
bool GlutHelpWindow::isVisible
unsigned char* GlutHelpWindow::text
GlutHelpWindow::GlutHelpWindow(GlutWindow *parent, GLint px, GLint py, GLint pw, GLint ph, const char *textFile)
GlutHelpWindow::~GlutHelpWindow()
void GlutHelpWindow::show(bool v)
void GlutHelpWindow::showHide()
Referenced by GlutContext::reshapeFunc.
int GlutHelpWindow::mouseFunc(int button, int state, int x, int y)
References GlutWindow::mouseFunc.
Referenced by GlutContext::reshapeFunc.
void GlutHelpWindow::glDraw()
References GlutWindow::x, GlutWindow::y, GlutWindow::h, GlutWindow::w, GlutWindow::glDraw.
Referenced by GlutContext::reshapeFunc.