P2PNetworkInterface
unsigned int P2PNetworkInterface::nextId
double P2PNetworkInterface::defaultDataRate
double P2PNetworkInterface::defaultDataRateVariability
double P2PNetworkInterface::dataRate
double P2PNetworkInterface::dataRateVariability
boost::rand48 P2PNetworkInterface::generator
unsigned int P2PNetworkInterface::globalId
unsigned int P2PNetworkInterface::localId
deque<MessagePtr> P2PNetworkInterface::outgoingQueue
Referenced by NetworkInterfaceStopTransmittingEvent::consume.
P2PNetworkInterface* P2PNetworkInterface::connectedInterface
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, Catoms2D::Catoms2DBlock::hasANeighbor, Catoms2D::Catoms2DBlock::getNextInterface, Catoms2D::Catoms2DBlock::canMove, Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::disconnectBlock, Catoms3D::Catoms3DWorld::deleteBlock, NetworkInterfaceStopTransmittingEvent::consume, MeldInterpret::MeldInterpretVM::tuple_send, MeldInterpret::MeldInterpretVM::down, MeldInterpret::MeldInterpretVM::up, MeldInterpret::MeldInterpretVM::north, MeldInterpret::MeldInterpretVM::south, MeldInterpret::MeldInterpretVM::east, MeldInterpret::MeldInterpretVM::west, connect, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::RobotBlocksWorld::disconnectBlock, RobotBlocks::RobotBlocksWorld::deleteBlock, SmartBlocks::SmartBlocksWorld::disconnectBlock.
BaseSimulator::BuildingBlock* P2PNetworkInterface::hostBlock
Referenced by BlinkyBlocks::BlinkyBlocksBlock::getInterfaceDestId, BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::deleteBlock, NetworkInterfaceStopTransmittingEvent::consume, MeldInterpret::MeldInterpretVM::down, MeldInterpret::MeldInterpretVM::up, MeldInterpret::MeldInterpretVM::north, MeldInterpret::MeldInterpretVM::south, MeldInterpret::MeldInterpretVM::east, MeldInterpret::MeldInterpretVM::west, connect, getConnectedBlockId, RobotBlocks::RobotBlocksBlock::setPrevNext, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::RobotBlocksWorld::deleteBlock, SmartBlocks::SmartBlocksBlock::getP2PNetworkInterfaceByDestBlockId.
uint64_t P2PNetworkInterface::availabilityDate
Referenced by BaseSimulator::BuildingBlock::scheduleLocalEvent, NetworkInterfaceStopTransmittingEvent::consume.
MessagePtr P2PNetworkInterface::messageBeingTransmitted
Referenced by NetworkInterfaceStopTransmittingEvent::consume.
P2PNetworkInterface::P2PNetworkInterface(BaseSimulator::BuildingBlock *b)
References OUTPUT.
P2PNetworkInterface::~P2PNetworkInterface()
References OUTPUT.
void P2PNetworkInterface::send(Message *m)
References BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::schedule.
Referenced by NetworkInterfaceStartTransmittingEvent::consume, NetworkInterfaceStopTransmittingEvent::consume.
bool P2PNetworkInterface::addToOutgoingBuffer(MessagePtr msg)
References BaseSimulator::getScheduler, BaseSimulator::Scheduler::now, BaseSimulator::Scheduler::schedule, BaseSimulator::Scheduler::trace.
Referenced by NetworkInterfaceEnqueueOutgoingEvent::consume.
void P2PNetworkInterface::send()
References BaseSimulator::getScheduler, BaseSimulator::Scheduler::trace, BaseSimulator::Scheduler::now, BaseSimulator::Scheduler::schedule.
void P2PNetworkInterface::connect(P2PNetworkInterface *ni)
References connectedInterface, OUTPUT, hostBlock, BaseSimulator::BuildingBlock::removeNeighbor, BaseSimulator::BuildingBlock::addNeighbor.
Referenced by BaseSimulator::BuildingBlock::addP2PNetworkInterfaceAndConnectTo, Catoms3D::Catoms3DWorld::linkBlock.
int P2PNetworkInterface::getConnectedBlockId()
References hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by Catoms2D::GenericCodeBlock::sendMessage, Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors, RobotBlocks::GenericCodeBlock::sendMessage, RobotBlocks::GenericCodeBlock::sendMessageToAllNeighbors.
void P2PNetworkInterface::setDataRate(unsigned int rate)
Referenced by BlinkyBlocks::BlinkyBlocksBlock::BlinkyBlocksBlock.
void P2PNetworkInterface::setDataRateVariability(unsigned int variability)
Referenced by BlinkyBlocks::BlinkyBlocksBlock::BlinkyBlocksBlock.