GlutButton
bool GlutButton::isActive
bool GlutButton::isDown
bool GlutButton::isHighlighted
GlutButton::GlutButton(GlutWindow *parent, GLuint pid, GLint px, GLint py, GLint pw, GLint ph, const char *titreTexture, bool pia=true)
virtual GlutButton::~GlutButton()
void GlutButton::activate(bool v)
Referenced by GlutSlidingMainWindow::mouseFunc, GlutSlidingMainWindow::openClose, GlutSlidingDebugWindow::mouseFunc.
bool GlutButton::isActivated()
Referenced by GlutSlidingMainWindow::openClose.
int GlutButton::mouseFunc(int button, int state, int x, int y)
References GlutWindow::x, GlutWindow::y, GlutWindow::h.
bool GlutButton::passiveMotionFunc(int mx, int my)
References GlutWindow::x, GlutWindow::y, GlutWindow::h.
void GlutButton::glDraw()
References GlutWindow::bindTexture, GlutWindow::x, GlutWindow::y, GlutWindow::w, GlutWindow::h.