SmartBlocks::SmartBlocksBlock
P2PNetworkInterface* SmartBlocks::SmartBlocksBlock::tabInterfaces[4][4]
SmartBlocksGlBlock* SmartBlocks::SmartBlocksBlock::ptrGlBlock
Color SmartBlocks::SmartBlocksBlock::color
Referenced by setColor, SmartBlocks::SmartBlocksWorld::updateGlData.
Vecteur SmartBlocks::SmartBlocksBlock::position
Referenced by setPosition, SmartBlocks::MotionStepEvent::consume, SmartBlocks::MotionStopEvent::consume, SmartBlocks::SmartBlocksWorld::updateGlData, SmartBlocks::SmartBlocksWorld::connectBlock, SmartBlocks::SmartBlocksWorld::disconnectBlock.
bool SmartBlocks::SmartBlocksBlock::wellPlaced
Referenced by SmartBlocks::SmartBlocksWorld::nbreWellPlacedBlock.
bool SmartBlocks::SmartBlocksBlock::_isBorder
bool SmartBlocks::SmartBlocksBlock::_isTrain
bool SmartBlocks::SmartBlocksBlock::_isSingle
SmartBlocksBlockCode*(* SmartBlocks::SmartBlocksBlock::buildNewBlockCode) (SmartBlocksBlock *))(SmartBlocksBlock *)
Referenced by SmartBlocksBlock.
SmartBlocks::SmartBlocksBlock::SmartBlocksBlock(int bId, SmartBlocksBlockCode *(*SmartBlocksBlockCodeBuildingFunction)(SmartBlocksBlock *))
References OUTPUT, buildNewBlockCode, BaseSimulator::BuildingBlock::blockCode, SmartBlocks::North, SmartBlocks::West.
SmartBlocks::SmartBlocksBlock::~SmartBlocksBlock()
References SmartBlocks::North, SmartBlocks::West, OUTPUT, BaseSimulator::BuildingBlock::blockId.
SmartBlocksGlBlock* SmartBlocks::SmartBlocksBlock::getGlBlock()
Referenced by SmartBlocks::SmartBlocksWorld::updateGlData.
void SmartBlocks::SmartBlocksBlock::setGlBlock(SmartBlocksGlBlock *ptr)
References setColor, setPosition.
Referenced by SmartBlocks::SmartBlocksWorld::addBlock.
void SmartBlocks::SmartBlocksBlock::setColor(const Color &)
References color, SmartBlocks::getWorld, SmartBlocks::SmartBlocksWorld::updateGlData.
Referenced by setGlBlock, SmartBlocks::MotionStartEvent::consume, SmartBlocks::MotionStopEvent::consume, SmartBlocks::SmartBlocksWorld::addBlock.
void SmartBlocks::SmartBlocksBlock::setColor(int num)
References color, Color::set, SmartBlocks::getWorld, SmartBlocks::SmartBlocksWorld::updateGlData.
void SmartBlocks::SmartBlocksBlock::setPosition(const Vecteur &p)
References position, SmartBlocks::getWorld, SmartBlocks::SmartBlocksWorld::updateGlData.
Referenced by setGlBlock, SmartBlocks::SmartBlocksWorld::addBlock.
void SmartBlocks::SmartBlocksBlock::setDisplayedValue(int n)
References SmartBlocks::SmartBlocksGlBlock::setDisplayedValue.
P2PNetworkInterface* SmartBlocks::SmartBlocksBlock::getInterface(NeighborDirection d)
References getP2PNetworkInterfaceByRelPos, getP2PNetworkInterfaceByDestBlockId, getDirection.
Referenced by SmartBlocks::SmartBlocksWorld::disconnectBlock.
P2PNetworkInterface * SmartBlocks::SmartBlocksBlock::getP2PNetworkInterfaceByRelPos(const PointCel &pos)
References SmartBlocks::PointCel::x, SmartBlocks::West, SmartBlocks::East, SmartBlocks::PointCel::y, SmartBlocks::South, SmartBlocks::North.
Referenced by getInterface.
P2PNetworkInterface * SmartBlocks::SmartBlocksBlock::getP2PNetworkInterfaceByDestBlockId(int id)
References P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
Referenced by getInterface.
NeighborDirection SmartBlocks::SmartBlocksBlock::getDirection(P2PNetworkInterface *)
References SmartBlocks::North, SmartBlocks::West.
Referenced by getInterface.
void SmartBlocks::SmartBlocksBlock::getGridPosition(int &x, int &y)
Referenced by SmartBlocks::SmartBlocksWorld::addBlock.