MeldProcess::VMSetIdEvent
MeldProcess::VMSetIdEvent::VMSetIdEvent(uint64_t, BuildingBlock *conBlock)
References EVENT_CONSTRUCTOR_INFO, Event::eventType, EVENT_SET_ID.
Referenced by consume.
MeldProcess::VMSetIdEvent::VMSetIdEvent(VMSetIdEvent *ev)
References EVENT_CONSTRUCTOR_INFO.
MeldProcess::VMSetIdEvent::~VMSetIdEvent()
References EVENT_DESTRUCTOR_INFO.
void MeldProcess::VMSetIdEvent::consumeBlockEvent()
References consume, getEventName.
void MeldProcess::VMSetIdEvent::consume()
References EVENT_CONSUME_INFO, BlockEvent::concernedBlock, BaseSimulator::BuildingBlock::scheduleLocalEvent, VMSetIdEvent.
Referenced by consumeBlockEvent, MeldProcess::VMStopEvent::consumeBlockEvent.
const string MeldProcess::VMSetIdEvent::getEventName()
Referenced by consumeBlockEvent, MeldProcess::VMStopEvent::consumeBlockEvent.