Vecteur
double Vecteur::pt[4][4]
x,y,z,w in a table (w=0 for a vector, w=1 for a point)
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, BlinkyBlocks::BlinkyBlocksWorld::addBlock, BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::menuChoice, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, Camera::updatePositionFromAngles, Catoms2D::MotionStopEvent::consume, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms2D::Catoms2DWorld::addBlock, Catoms2D::Catoms2DWorld::connectBlock, Catoms2D::Catoms2DWorld::disconnectBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms2D::Catoms2DWorld::worldToGridPosition, Catoms2D::Catoms2DWorld::gridToWorldPosition, Catoms2D::Catoms2DWorld::generateRandom, Catoms3D::Catoms3DBlock::getNeighborPos, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Catoms3D::Catoms3DWorld::gridToWorldPosition, operator*, Matrice::setGLmat, Matrice::setRotation, RobotBlocks::MotionStopEvent::consume, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, RobotBlocks::RobotBlocksWorld::addBlock, RobotBlocks::RobotBlocksWorld::connectBlock, RobotBlocks::RobotBlocksWorld::disconnectBlock, RobotBlocks::RobotBlocksWorld::deleteBlock, RobotBlocks::RobotBlocksWorld::updateGlData, RobotBlocks::RobotBlocksWorld::menuChoice, SmartBlocks::MotionStopEvent::consume, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, SmartBlocks::SmartBlocksWorld::connectBlock, SmartBlocks::SmartBlocksWorld::disconnectBlock, operator>>, operator<<, operator+=, operator+, operator-, operator^, normer, norme, norme2, normer_interne, setLength, set, operator==.
Vecteur::Vecteur()
Constructor, initialize the vector to 0.
Vecteur::Vecteur(double x, double y, double z, double w=0.0)
Constructor, initialize the vector to (x,y,z,w)
x : x coordinate of the vector y : y coordinate of the vector z : z coordinate of the vector w : w=0 for a vector (default), w=1 for a point
void Vecteur::set(double x, double y, double z, double w=0.0)
Set method, initialize the vector to (x,y,z,w)
x : x coordinate of the vector y : y coordinate of the vector z : z coordinate of the vector w : w=0 for a vector (default), w=1 for a point
Referenced by Camera::updatePositionFromAngles, Catoms2D::MotionStartEvent::MotionStartEvent, Catoms3D::Catoms3DBlock::getOrientationFromMatrix, Catoms3D::Catoms3DBlock::getNeighborPos.
void Vecteur::set(const float *tab, short s, float extra=0.0f)
Set method, initialize the vector from an array of float.
tab : tab of coordinates s : size of tab
References pt.
void Vecteur::setMin(double x, double y, double z)
void Vecteur::setMax(double x, double y, double z)
const Vecteur Vecteur::normer() const
Return a normalized copy of the vector.
References pt.
Referenced by Catoms3D::Rotations::Rotations.
void Vecteur::normer_interne()
Normalize the current vector.
References pt.
Referenced by Camera::updatePositionFromAngles.
void Vecteur::setLength(double l)
Normalize the current vector with a lenght l.
l : length of the vector
References pt.
Referenced by RobotBlocks::MotionStepEvent::MotionStepEvent, SmartBlocks::MotionStepEvent::MotionStepEvent.
double Vecteur::norme() const
Return the length of the vector.
References pt.
double Vecteur::norme2() const
Return the square of the length of the vector.
References pt.
Referenced by SkelLine::distance2, SkelLine::SkelLine.
void Vecteur::operator+=(const Vecteur &p)
Incrementation of the vecteur by p.
p : vector to add to the current vector
References pt.
bool Vecteur::operator==(const Vecteur &V1)
Comparison of two vectors, return true if equal.
p : vector to compare to the current vector
References pt, operator>>, BlinkyBlocks::operator<<, operator*, operator+, operator-, operator^.
const double Vecteur::operator[](const int i) const
void Vecteur::setPoint(bool v)
References operator*, operator+, operator-, operator^.
istream& operator>>(istream &f, Vecteur &p)
ostream& operator<<(ostream &f, const Vecteur &p)
const Vecteur operator*(double, const Vecteur)
const double operator*(const Vecteur v1, const Vecteur v2)
Return the scalar product of two vectors.
v1 : first vector v2 : second vector
const Vecteur operator+(const Vecteur, const Vecteur)
const Vecteur operator-(const Vecteur, const Vecteur)
const Vecteur operator-(const Vecteur)
const Vecteur operator^(const Vecteur, const Vecteur)
Return the cross product of two vectors.
v1 : first vector v2 : second vector