Color
GLfloat Color::rgba[4][4]
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Color, set, operator<<, glColor, operator[], RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, shadowedRenderingStep3, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
Color::Color()
References rgba.
Color::Color(float r, float g, float b, float a=1.0)
References rgba.
void Color::set(float r, float g, float b, float a=1.0)
References rgba.
Referenced by BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::SmartBlocksBlock::setColor.
void Color::glColor()
References rgba.
const GLfloat Color::operator[](const int i) const
References rgba, operator<<, WHITE, RED, GREEN, LIGHTGREEN, BLUE, YELLOW, CYAN, MAGENTA, LIGHTBLUE, GOLD, PINK, GREY, LIGHTGREY, DARKGREY, ORANGE, DARKORANGE.
ostream& operator<<(ostream &f, const Color &c)
Referenced by operator[].