Catoms2D::PointRel3D
short Catoms2D::PointRel3D::x
Referenced by Catoms2D::Capability::getCenter, Catoms2D::ValidationMatrix::get, Catoms2D::ValidationMatrix::set, fromString, Catoms2D::operator<<, rotateY, rotateZ, set, isInBoundingBox, Catoms2D::operator!=, Catoms2D::operator==, Catoms2D::PresenceMatrix::add, Catoms2D::PresenceMatrix::get, Catoms2D::PresenceMatrix::set, Catoms2D::Catoms2DWorld::getPresenceMatrix.
short Catoms2D::PointRel3D::y
Referenced by Catoms2D::Capability::getCenter, Catoms2D::ValidationMatrix::get, Catoms2D::ValidationMatrix::set, fromString, Catoms2D::operator<<, rotateY, rotateZ, set, Catoms2D::operator!=, Catoms2D::operator==, Catoms2D::PresenceMatrix::add, Catoms2D::PresenceMatrix::get, Catoms2D::PresenceMatrix::set, Catoms2D::Catoms2DWorld::getPresenceMatrix.
short Catoms2D::PointRel3D::z
Referenced by Catoms2D::Capability::getCenter, Catoms2D::ValidationMatrix::get, Catoms2D::ValidationMatrix::set, fromString, Catoms2D::operator<<, rotateY, rotateZ, set, isInBoundingBox, Catoms2D::operator!=, Catoms2D::operator==, Catoms2D::PresenceMatrix::add, Catoms2D::PresenceMatrix::get, Catoms2D::PresenceMatrix::set, Catoms2D::Catoms2DWorld::getPresenceMatrix.
PointRel3D::PointRel3D()
PointRel3D::PointRel3D(short vx, short vy, short vz)
PointRel3D::PointRel3D(const string &str)
References fromString.
void PointRel3D::set(short vx, short vy, short vz)
References x, y, z.
Referenced by Catoms2D::Capability::getMotionVector.
bool PointRel3D::isInBoundingBox(short x0, short x1, short y0, short y1, short z0, short z1)
References x, z.
void PointRel3D::fromString(const string &str)
References x, y, z.
Referenced by Catoms2D::Catoms2DCapabilities::Catoms2DCapabilities, PointRel3D.
void PointRel3D::fromString(const string &str, const PointRel3D &ref)
References x, y, z.
PointRel3D PointRel3D::rotateY(int n) const
References x, z, y.
PointRel3D PointRel3D::rotateZ(int n) const
References x, y, z.
Referenced by Catoms2D::Capability::Capability.
bool Catoms2D::PointRel3D::isZero()
bool Catoms2D::PointRel3D::isSet() const
References operator==, operator!=, operator<<.
bool operator==(const PointRel3D p1, const PointRel3D p2)
Referenced by isSet.
bool operator!=(const PointRel3D p1, const PointRel3D p2)
Referenced by isSet.
ostream& operator<<(ostream &f, const PointRel3D &pt)
Referenced by isSet.