BaseSimulator::World
boost::interprocess::interprocess_mutex BaseSimulator::World::mutex_gl
World * BaseSimulator::World::world
Referenced by BlinkyBlocks::BlinkyBlocksWorld::createWorld, BlinkyBlocks::BlinkyBlocksWorld::deleteWorld, BlinkyBlocks::BlinkyBlocksWorld::getWorld, Catoms2D::Catoms2DWorld::createWorld, Catoms2D::Catoms2DWorld::deleteWorld, Catoms2D::Catoms2DWorld::generateRandom, Catoms2D::Catoms2DWorld::getWorld, Catoms3D::Catoms3DWorld::createWorld, Catoms3D::Catoms3DWorld::deleteWorld, Catoms3D::Catoms3DWorld::getWorld, MultiCores::MultiCoresWorld::getWorld, RobotBlocks::RobotBlocksWorld::createWorld, RobotBlocks::RobotBlocksWorld::deleteWorld, RobotBlocks::RobotBlocksWorld::getWorld, SmartBlocks::SmartBlocksWorld::createWorld, SmartBlocks::SmartBlocksWorld::deleteWorld, SmartBlocks::SmartBlocksWorld::getWorld.
vector< GlBlock * > BaseSimulator::World::tabGlBlocks
Referenced by BlinkyBlocks::BlinkyBlocksWorld::addBlock, BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::glDraw, BlinkyBlocks::BlinkyBlocksWorld::glDrawId, BlinkyBlocks::BlinkyBlocksWorld::glDrawIdByMaterial, BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, BlinkyBlocks::BlinkyBlocksWorld::menuChoice, Catoms2D::Catoms2DWorld::addBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms2D::Catoms2DWorld::glDraw, Catoms2D::Catoms2DWorld::glDrawId, Catoms2D::Catoms2DWorld::glDrawIdByMaterial, Catoms2D::Catoms2DWorld::createPopupMenu, Catoms2D::Catoms2DWorld::menuChoice, Catoms3D::Catoms3DWorld::addBlock, Catoms3D::Catoms3DWorld::deleteBlock, Catoms3D::Catoms3DWorld::glDraw, Catoms3D::Catoms3DWorld::glDrawId, Catoms3D::Catoms3DWorld::glDrawIdByMaterial, Catoms3D::Catoms3DWorld::menuChoice, RobotBlocks::RobotBlocksWorld::addBlock, RobotBlocks::RobotBlocksWorld::deleteBlock, RobotBlocks::RobotBlocksWorld::glDraw, RobotBlocks::RobotBlocksWorld::glDrawId, RobotBlocks::RobotBlocksWorld::glDrawIdByMaterial, RobotBlocks::RobotBlocksWorld::createPopupMenu, RobotBlocks::RobotBlocksWorld::menuChoice, SmartBlocks::SmartBlocksWorld::addBlock, SmartBlocks::SmartBlocksWorld::glDraw, SmartBlocks::SmartBlocksWorld::glDrawId.
map< int, BuildingBlock * > BaseSimulator::World::buildingBlocksMap
Referenced by BlinkyBlocks::BlinkyBlocksWorld::addBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, BlinkyBlocks::BlinkyBlocksWorld::dump, Catoms2D::Catoms2DWorld::addBlock, Catoms2D::Catoms2DWorld::extractConfig, Catoms3D::Catoms3DWorld::addBlock, RobotBlocks::RobotBlocksWorld::addBlock, SmartBlocks::SmartBlocksWorld::addBlock, SmartBlocks::SmartBlocksWorld::nbreWellPlacedBlock.
GlBlock* BaseSimulator::World::selectedBlock
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, Catoms2D::Catoms2DWorld::deleteBlock, Catoms3D::Catoms3DWorld::deleteBlock, RobotBlocks::RobotBlocksWorld::deleteBlock.
BaseSimulator::World::World()
References OUTPUT, ERRPUT.
BaseSimulator::World::~World()
References OUTPUT.
static World* BaseSimulator::World::getWorld()
static void BaseSimulator::World::deleteWorld()
map<int, BuildingBlock*>& BaseSimulator::World::getMap()
Referenced by ConfigStat::ConfigStat, ConfigStat::compute.
int BaseSimulator::World::getSize()
void BaseSimulator::World::printInfo()
References OUTPUT.
BuildingBlock * BaseSimulator::World::getBlockById(int bId)
Referenced by BaseSimulator::BuildingBlock::addP2PNetworkInterfaceAndConnectTo, Catoms2D::Catoms2DWorld::generateRandom, ConfigStat::compute, MeldProcess::MeldProcessVM::sendCommand.
GlBlock* BaseSimulator::World::getSelectedBlock()
Referenced by GlutContext::reshapeFunc.
GlBlock* BaseSimulator::World::setSelectedBlock(int n)
Referenced by GlutContext::reshapeFunc.
virtual void BaseSimulator::World::setSelectedFace(int n)
Referenced by GlutContext::reshapeFunc.
GlBlock* BaseSimulator::World::getBlockByNum(int n)
Referenced by GlutContext::reshapeFunc.
int BaseSimulator::World::getNbBlocks()
void BaseSimulator::World::lock()
References BaseSimulator::BuildingBlock::lock.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::glDraw, BlinkyBlocks::BlinkyBlocksWorld::glDrawId, BlinkyBlocks::BlinkyBlocksWorld::glDrawIdByMaterial, BlinkyBlocks::BlinkyBlocksWorld::updateGlData, Catoms2D::Catoms2DWorld::glDraw, Catoms2D::Catoms2DWorld::glDrawId, Catoms2D::Catoms2DWorld::glDrawIdByMaterial, Catoms2D::Catoms2DWorld::updateGlData, Catoms3D::Catoms3DWorld::glDraw, Catoms3D::Catoms3DWorld::glDrawId, Catoms3D::Catoms3DWorld::glDrawIdByMaterial, Catoms3D::Catoms3DWorld::updateGlData, RobotBlocks::RobotBlocksWorld::glDraw, RobotBlocks::RobotBlocksWorld::glDrawId, RobotBlocks::RobotBlocksWorld::glDrawIdByMaterial, RobotBlocks::RobotBlocksWorld::updateGlData, SmartBlocks::SmartBlocksWorld::glDraw, SmartBlocks::SmartBlocksWorld::glDrawId, SmartBlocks::SmartBlocksWorld::updateGlData.
void BaseSimulator::World::unlock()
Referenced by BlinkyBlocks::BlinkyBlocksWorld::glDraw, BlinkyBlocks::BlinkyBlocksWorld::glDrawId, BlinkyBlocks::BlinkyBlocksWorld::glDrawIdByMaterial, BlinkyBlocks::BlinkyBlocksWorld::updateGlData, Catoms2D::Catoms2DWorld::glDraw, Catoms2D::Catoms2DWorld::glDrawId, Catoms2D::Catoms2DWorld::glDrawIdByMaterial, Catoms2D::Catoms2DWorld::updateGlData, Catoms3D::Catoms3DWorld::glDraw, Catoms3D::Catoms3DWorld::glDrawId, Catoms3D::Catoms3DWorld::glDrawIdByMaterial, Catoms3D::Catoms3DWorld::updateGlData, RobotBlocks::RobotBlocksWorld::glDraw, RobotBlocks::RobotBlocksWorld::glDrawId, RobotBlocks::RobotBlocksWorld::glDrawIdByMaterial, RobotBlocks::RobotBlocksWorld::updateGlData, SmartBlocks::SmartBlocksWorld::glDraw, SmartBlocks::SmartBlocksWorld::glDrawId, SmartBlocks::SmartBlocksWorld::updateGlData.
virtual void BaseSimulator::World::glDraw()
Referenced by GlutContext::reshapeFunc.
virtual void BaseSimulator::World::glDrawId()
Referenced by GlutContext::reshapeFunc.
virtual void BaseSimulator::World::glDrawIdByMaterial()
Referenced by GlutContext::reshapeFunc.
virtual void BaseSimulator::World::createPopupMenu(int ix, int iy)
Referenced by GlutContext::reshapeFunc.
virtual void BaseSimulator::World::createHelpWindow()
Referenced by GlutContext::reshapeFunc.
virtual Camera* BaseSimulator::World::getCamera()
Referenced by GlutContext::reshapeFunc.
virtual void BaseSimulator::World::menuChoice(int)
virtual void BaseSimulator::World::tapBlock(uint64_t date, int bId)
Referenced by ScenarioTappEvent::exportEventToScheduler, GlutContext::reshapeFunc.
virtual void BaseSimulator::World::accelBlock(uint64_t date, int bId, int x, int y, int z)
virtual void BaseSimulator::World::shakeBlock(uint64_t date, int bId, int f)
void BaseSimulator::World::stopSimulation()
void BaseSimulator::World::generateIds(int n, int *ids)
Referenced by Catoms2D::Catoms2DWorld::generateRandom.