GlutSlider
int GlutSlider::buttonHeight
int GlutSlider::buttonY
int GlutSlider::dataTextLines
int GlutSlider::nbreTextLines
int GlutSlider::dataPosition
bool GlutSlider::mouseDown
int GlutSlider::currentMousePos
GlutSlider::GlutSlider(GlutWindow *parent, GLuint pid, GLint px, GLint py, GLint ph, const char *titreTexture, int ntl)
References update.
GlutSlider::~GlutSlider()
void GlutSlider::setDataTextLines(int dtl)
Referenced by GlutSlidingMainWindow::select.
void GlutSlider::incDataTextLines()
Referenced by GlutSlidingMainWindow::addTrace.
int GlutSlider::getPosition()
Referenced by GlutSlidingMainWindow::glDraw.
void GlutSlider::setPosition(int pos)
void GlutSlider::glDraw()
References GlutWindow::x, GlutWindow::y, GlutWindow::w, GlutWindow::h, GlutWindow::bindTexture.
int GlutSlider::mouseFunc(int button, int state, int x, int y)
References GlutWindow::h, GlutWindow::x, GlutWindow::w, GlutWindow::y, update.
void GlutSlider::update()
References GlutWindow::h.
Referenced by GlutSlidingMainWindow::reshapeFunc, GlutSlidingDebugWindow::reshapeFunc, GlutSlider, mouseFunc.