Catoms2D::GenericCodeBlock
multimap<int,eventFunc> Catoms2D::GenericCodeBlock::eventFuncMap
Referenced by addMessageEventFunc, processLocalEvent.
Catoms2DScheduler* Catoms2D::GenericCodeBlock::scheduler
Referenced by sendMessage, sendMessageToAllNeighbors.
Catoms2DBlock* Catoms2D::GenericCodeBlock::module
Referenced by sendMessageToAllNeighbors.
ConsoleStream Catoms2D::GenericCodeBlock::console
Referenced by sendMessage, sendMessageToAllNeighbors.
Catoms2D::GenericCodeBlock::GenericCodeBlock(Catoms2DBlock *host)
References Catoms2D::getScheduler, BaseSimulator::BlockCode::hostBlock, ConsoleStream::setInfo, BaseSimulator::BuildingBlock::blockId, BaseSimulator::BlockCode::addDebugAttributes.
Catoms2D::GenericCodeBlock::~GenericCodeBlock()
References processLocalEvent, addMessageEventFunc, sendMessageToAllNeighbors, sendMessage.
void Catoms2D::GenericCodeBlock::processLocalEvent(EventPtr pev)
References EVENT_NI_RECEIVE, eventFuncMap, OUTPUT.
Referenced by ~GenericCodeBlock.
void Catoms2D::GenericCodeBlock::addMessageEventFunc(int type, eventFunc)
References eventFuncMap.
Referenced by ~GenericCodeBlock.
int Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors(Message *, int t0, int dt, int nexcept,...)
References module, Catoms2D::Catoms2DBlock::getInterface, P2PNetworkInterface::connectedInterface, scheduler, BaseSimulator::Scheduler::now, Message::clone, BaseSimulator::Scheduler::schedule.
Referenced by ~GenericCodeBlock.
int Catoms2D::GenericCodeBlock::sendMessage(Message *, P2PNetworkInterface *, int t0, int dt)
References scheduler, BaseSimulator::Scheduler::now, BaseSimulator::Scheduler::schedule.
Referenced by ~GenericCodeBlock.
int Catoms2D::GenericCodeBlock::sendMessageToAllNeighbors(const char *, Message *, int t0, int dt, int nexcept,...)
References module, Catoms2D::Catoms2DBlock::getInterface, P2PNetworkInterface::connectedInterface, scheduler, BaseSimulator::Scheduler::now, console, P2PNetworkInterface::getConnectedBlockId, Message::clone, BaseSimulator::Scheduler::schedule.
int Catoms2D::GenericCodeBlock::sendMessage(const char *, Message *, P2PNetworkInterface *, int t0, int dt)
References scheduler, BaseSimulator::Scheduler::now, console, P2PNetworkInterface::getConnectedBlockId, BaseSimulator::Scheduler::schedule.
void Catoms2D::GenericCodeBlock::setColor(const Color &c)
References Catoms2D::Catoms2DBlock::setColor.