Catoms2D::Catoms2DMove
Catoms2DBlock* Catoms2D::Catoms2DMove::pivot
Referenced by Catoms2DMove, getPivot.
RelativeDirection::Direction Catoms2D::Catoms2DMove::direction
Referenced by Catoms2DMove, getDirection.
Catoms2D::Catoms2DMove::Catoms2DMove(Catoms2DBlock *p, RelativeDirection::Direction d)
References pivot, direction.
Catoms2D::Catoms2DMove::Catoms2DMove(const Catoms2DMove &m)
References pivot, direction.
Catoms2D::Catoms2DMove::~Catoms2DMove()
RelativeDirection::Direction Catoms2D::Catoms2DMove::getDirection()
References direction.
Referenced by Catoms2D::Catoms2DBlock::canMove, Catoms2D::MotionStartEvent::MotionStartEvent.
Catoms2DBlock * Catoms2D::Catoms2DMove::getPivot()
References pivot.
Referenced by Catoms2D::Catoms2DBlock::canMove, Catoms2D::MotionStartEvent::MotionStartEvent.