BlinkyBlocks::BlinkyBlocksBlock
P2PNetworkInterface* BlinkyBlocks::BlinkyBlocksBlock::tabInterfaces[6][6]
BlinkyBlocksGlBlock* BlinkyBlocks::BlinkyBlocksBlock::ptrGlBlock
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock.
Color BlinkyBlocks::BlinkyBlocksBlock::color
Referenced by setColor, stop, BlinkyBlocks::operator<<, BlinkyBlocks::BlinkyBlocksWorld::updateGlData, BlinkyBlocks::BlinkyBlocksWorld::menuChoice.
Vecteur BlinkyBlocks::BlinkyBlocksBlock::position
Referenced by setPosition, BlinkyBlocks::BlinkyBlocksWorld::addBlock, BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::updateGlData, BlinkyBlocks::BlinkyBlocksWorld::createPopupMenu, BlinkyBlocks::BlinkyBlocksWorld::menuChoice, BlinkyBlocks::BlinkyBlocksWorld::stopBlock.
BlinkyBlocksBlockCode*(* BlinkyBlocks::BlinkyBlocksBlock::buildNewBlockCode) (BlinkyBlocksBlock *))(BlinkyBlocksBlock *)
Referenced by BlinkyBlocksBlock, BlinkyBlocks::BlinkyBlocksWorld::menuChoice.
BlinkyBlocks::BlinkyBlocksBlock::BlinkyBlocksBlock(int bId, BlinkyBlocksBlockCode *(*blinkyBlocksBlockCodeBuildingFunction)(BlinkyBlocksBlock *))
References OUTPUT, BLINKYBLOCKS_PACKET_DATASIZE, BLINKYBLOCKS_TRANSMISSION_MAX_TIME, BLINKYBLOCKS_TRANSMISSION_MIN_TIME, BaseSimulator::BuildingBlock::getP2PNetworkInterfaceList, P2PNetworkInterface::setDataRate, P2PNetworkInterface::setDataRateVariability, BaseSimulator::BuildingBlock::clock, buildNewBlockCode, BaseSimulator::BuildingBlock::blockCode.
BlinkyBlocks::BlinkyBlocksBlock::~BlinkyBlocksBlock()
References OUTPUT, BaseSimulator::BuildingBlock::blockId.
BlinkyBlocksGlBlock* BlinkyBlocks::BlinkyBlocksBlock::getGlBlock()
Referenced by BlinkyBlocks::BlinkyBlocksWorld::updateGlData.
void BlinkyBlocks::BlinkyBlocksBlock::setGlBlock(BlinkyBlocksGlBlock *ptr)
Referenced by BlinkyBlocks::BlinkyBlocksWorld::addBlock.
void BlinkyBlocks::BlinkyBlocksBlock::setColor(const Color &)
References BaseSimulator::BuildingBlock::lock, BaseSimulator::BuildingBlock::state, BaseSimulator::BuildingBlock::ALIVE, color, BaseSimulator::BuildingBlock::unlock, BlinkyBlocks::getWorld, BlinkyBlocks::BlinkyBlocksWorld::updateGlData.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::addBlock.
void BlinkyBlocks::BlinkyBlocksBlock::setColor(int num)
References color, Color::set, BlinkyBlocks::getWorld, BlinkyBlocks::BlinkyBlocksWorld::updateGlData.
void BlinkyBlocks::BlinkyBlocksBlock::setPosition(const Vecteur &p)
References position, BlinkyBlocks::getWorld, BlinkyBlocks::BlinkyBlocksWorld::updateGlData.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::addBlock.
P2PNetworkInterface* BlinkyBlocks::BlinkyBlocksBlock::getInterface(NeighborDirection::Direction d)
References BlinkyBlocks::operator<<.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock, MeldInterpret::MeldInterpretVM::down, MeldInterpret::MeldInterpretVM::up, MeldInterpret::MeldInterpretVM::north, MeldInterpret::MeldInterpretVM::south, MeldInterpret::MeldInterpretVM::east, MeldInterpret::MeldInterpretVM::west.
P2PNetworkInterface * BlinkyBlocks::BlinkyBlocksBlock::getInterfaceDestId(int id)
References P2PNetworkInterface::hostBlock, BaseSimulator::BuildingBlock::blockId.
NeighborDirection::Direction BlinkyBlocks::BlinkyBlocksBlock::getDirection(P2PNetworkInterface *)
Referenced by addNeighbor, removeNeighbor.
void BlinkyBlocks::BlinkyBlocksBlock::tap(uint64_t date)
References OUTPUT, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::tapBlock.
void BlinkyBlocks::BlinkyBlocksBlock::accel(uint64_t date, int x, int y, int z)
References BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::accelBlock.
void BlinkyBlocks::BlinkyBlocksBlock::shake(uint64_t date, int f)
References BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::shakeBlock.
void BlinkyBlocks::BlinkyBlocksBlock::addNeighbor(P2PNetworkInterface *ni, BuildingBlock *target)
References OUTPUT, BaseSimulator::BuildingBlock::blockId, BlinkyBlocks::NeighborDirection::getString, getDirection, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock, BlinkyBlocks::NeighborDirection::getOpposite.
void BlinkyBlocks::BlinkyBlocksBlock::removeNeighbor(P2PNetworkInterface *ni)
References OUTPUT, BaseSimulator::BuildingBlock::blockId, BlinkyBlocks::NeighborDirection::getString, getDirection, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock, BlinkyBlocks::NeighborDirection::getOpposite.
void BlinkyBlocks::BlinkyBlocksBlock::stop(uint64_t date, State s)
References OUTPUT, BaseSimulator::BuildingBlock::lock, BaseSimulator::BuildingBlock::state, BaseSimulator::BuildingBlock::STOPPED, color, BaseSimulator::BuildingBlock::unlock, BlinkyBlocks::getWorld, BlinkyBlocks::BlinkyBlocksWorld::updateGlData, BaseSimulator::Simulator::getType, BaseSimulator::Simulator::MELDPROCESS, BlinkyBlocks::getScheduler, BaseSimulator::Scheduler::scheduleLock, BaseSimulator::Simulator::MELDINTERPRET.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::stopBlock.
void BlinkyBlocks::BlinkyBlocksBlock::pauseClock(uint64_t delay, uint64_t start)