MultiCores::MultiCoresScheduler
set<int> MultiCores::MultiCoresScheduler::undefinedBlocksSet
boost::thread* MultiCores::MultiCoresScheduler::schedulerThread
Referenced by MultiCoresScheduler.
boost::asio::io_service* MultiCores::MultiCoresScheduler::ios
Referenced by MultiCoresScheduler.
boost::asio::io_service MultiCores::MultiCoresScheduler::ios2
Referenced by MultiCoresScheduler.
udp::socket* MultiCores::MultiCoresScheduler::socket
udp::endpoint MultiCores::MultiCoresScheduler::VMEndpoint
tcp::socket MultiCores::MultiCoresScheduler::socket2
Referenced by startPaused, waitForVMMessage, sendMessageToVM.
tcp::acceptor* MultiCores::MultiCoresScheduler::acceptor
Referenced by MultiCoresScheduler, startPaused.
MultiCores::MultiCoresScheduler::MultiCoresScheduler()
References ios, acceptor, ios2, schedulerThread, startPaused.
Referenced by createScheduler.
MultiCores::MultiCoresScheduler::~MultiCoresScheduler()
void * MultiCores::MultiCoresScheduler::startPaused()
References BaseSimulator::Scheduler::trace, acceptor, socket2, waitForVMMessage, BaseSimulator::Scheduler::schedulerMode, SCHEDULER_MODE_FASTEST, BaseSimulator::Scheduler::eventsMap, undefinedBlocksSetIsEmpty, BaseSimulator::Scheduler::currentDate, BaseSimulator::Scheduler::maximumDate, BaseSimulator::Scheduler::eventsMapSize, SCHEDULER_MODE_REALTIME, BaseSimulator::Scheduler::largestEventsMapSize, Event::getNextId, Event::getNbLivingEvents, Message::getNbMessages.
Referenced by MultiCoresScheduler.
void MultiCores::MultiCoresScheduler::createScheduler()
References BaseSimulator::Scheduler::scheduler, MultiCoresScheduler.
void MultiCores::MultiCoresScheduler::deleteScheduler()
References BaseSimulator::Scheduler::scheduler.
static MultiCoresScheduler* MultiCores::MultiCoresScheduler::getScheduler()
Referenced by waitForVMMessage.
void MultiCores::MultiCoresScheduler::printInfo()
void MultiCores::MultiCoresScheduler::waitForSchedulerEnd()
void MultiCores::MultiCoresScheduler::addUndefinedBlock(int id)
Referenced by waitForVMMessage.
void MultiCores::MultiCoresScheduler::removeUndefinedBlock(int id)
Referenced by waitForVMMessage.
bool MultiCores::MultiCoresScheduler::undefinedBlocksSetIsEmpty()
Referenced by startPaused, waitForVMMessage.
bool MultiCores::MultiCoresScheduler::isBlockUndefined(int id)
Referenced by waitForVMMessage.
void MultiCores::MultiCoresScheduler::printUndefinedBlocksSet()
void MultiCores::MultiCoresScheduler::waitForVMMessage()
References socket2, VM_TRACE_MESSAGE, MultiCores::VMMessage::messageType, VM_MESSAGE_TYPE_START_SIMULATION, MultiCores::VMMessage::param1, getScheduler, addUndefinedBlock, MultiCores::getWorld, MultiCores::MultiCoresWorld::addBlock, MultiCores::MultiCoresSimulator::buildNewBlockCode, VM_MESSAGE_TYPE_CREATE_LINK, MultiCores::VMMessage::param2, MultiCores::MultiCoresWorld::getBlockById, BaseSimulator::BuildingBlock::addP2PNetworkInterfaceAndConnectTo, VM_MESSAGE_TYPE_COMPUTATION_LOCK, isBlockUndefined, BaseSimulator::Scheduler::trace, BaseSimulator::Scheduler::schedule, BaseSimulator::Scheduler::now, removeUndefinedBlock, VM_MESSAGE_TYPE_END_SIMULATION, undefinedBlocksSetIsEmpty, VM_MESSAGE_TYPE_SEND_MESSAGE, MultiCores::VMMessage::param3, VM_MESSAGE_TYPE_WAIT_FOR_MESSAGE.
Referenced by startPaused.
void MultiCores::MultiCoresScheduler::sendMessageToVM(VMMessage message)
References socket2.