SmartBlocks::SmartBlocksGlBlock
int SmartBlocks::SmartBlocksGlBlock::displayedValue
Referenced by SmartBlocksGlBlock, glDraw.
SmartBlocks::SmartBlocksGlBlock::SmartBlocksGlBlock(int id)
References displayedValue.
SmartBlocks::SmartBlocksGlBlock::~SmartBlocksGlBlock()
string SmartBlocks::SmartBlocksGlBlock::getInfo()
References GlBlock::getInfo.
void SmartBlocks::SmartBlocksGlBlock::setDisplayedValue(int n)
References glDraw, glDrawId.
Referenced by SmartBlocks::SmartBlocksBlock::setDisplayedValue.
void SmartBlocks::SmartBlocksGlBlock::glDraw(ObjLoader::ObjLoader *ptrObj)
References GlBlock::position, GlBlock::isHighlighted, GlBlock::color, ObjLoader::ObjLoader::setLightedColor, ObjLoader::ObjLoader::glDraw, displayedValue, SmartBlocks::getWorld, SmartBlocks::SmartBlocksWorld::idTextureDigits.
Referenced by setDisplayedValue.
void SmartBlocks::SmartBlocksGlBlock::glDrawId(ObjLoader::ObjLoader *ptrObj)
References GlBlock::position, ObjLoader::ObjLoader::glDraw.
Referenced by setDisplayedValue.