color.h
const Color Colors[9][9]
Referenced by MeldInterpret::MeldInterpretVM::setColor.
const Color WHITE(1.0f, 1.0f, 1.0f)
Referenced by Color::operator[], BaseSimulator::Scheduler::getMode, shadowedRenderingStep3.
const Color RED(1.0f, 0.0f, 0.0f)
Referenced by Color::operator[].
const Color GREEN(0.0f, 1.0f, 0.0f)
Referenced by Color::operator[].
const Color LIGHTGREEN(0.75f, 1.0f, 0.25f)
Referenced by Color::operator[].
const Color BLUE(0.0f, 0.0f, 1.0f)
Referenced by Color::operator[].
const Color YELLOW(1.0f, 1.0f, 0.0f)
Referenced by Catoms2D::MotionStopEvent::consume, Catoms3D::MotionStopEvent::consume, Color::operator[], GlutSlidingDebugWindow::keyFunc, RobotBlocks::MotionStopEvent::consume, SmartBlocks::MotionStopEvent::consume.
const Color CYAN(0.0f, 1.0f, 1.0f)
Referenced by Color::operator[].
const Color MAGENTA(1.0f, 0.0f, 1.0f)
Referenced by Color::operator[].
const Color LIGHTBLUE(173/255.0, 216/255.0, 230/255.0)
Referenced by Catoms2D::MotionStopEvent::consume, Catoms3D::MotionStopEvent::consume, Color::operator[], GlutSlidingDebugWindow::keyFunc, RobotBlocks::MotionStopEvent::consume.
const Color GOLD(1.0, 215/255.0, 0)
Referenced by Color::operator[].
const Color PINK(1.0, 192/255.0, 203/255.0)
Referenced by Color::operator[].
const Color GREY(0.5, 0.5, 0.5)
Referenced by Color::operator[].
const Color LIGHTGREY(0.75, 0.75, 0.75)
Referenced by Color::operator[].
const Color DARKGREY(0.25, 0.25, 0.25)
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, Catoms2D::MotionStartEvent::consume, Catoms2D::Catoms2DSimulator::Catoms2DSimulator, Catoms2D::Catoms2DWorld::generateRandom, Catoms3D::MotionStartEvent::consume, Catoms3D::Catoms3DSimulator::Catoms3DSimulator, Color::operator[], RobotBlocks::MotionStartEvent::consume, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator, SmartBlocks::MotionStartEvent::consume.
const Color ORANGE(1.0, 0.64706, 0.0)
Referenced by Color::operator[].
const Color DARKORANGE(1.0, 0.549, 0.0)
Referenced by Color::operator[].