matrice44.h
const Matrice operator*(const Matrice, const Matrice)
References Matrice::m.
Referenced by Matrice::identity, Matrice::setHomothetie.
const Vecteur operator*(const Matrice, const Vecteur)
References Vecteur::pt, Matrice::m.
const Vecteur operator*(const Vecteur, const Matrice)
References Vecteur::pt, Matrice::m.
double det33(double, double, double, double, double, double, double, double, double)
Referenced by Matrice::determinant, Matrice::inverse, Matrice::setHomothetie.