matrice44.cpp
istream& operator>>(istream &f, Matrice &p)
References Matrice::m.
Referenced by Matrice::identity, Vecteur::operator==.
ostream& operator<<(ostream &f, Matrice &p)
References Matrice::m.
const Vecteur operator*(const Matrice p1, const Vecteur p2)
References Vecteur::pt, Matrice::m.
const Vecteur operator*(const Vecteur p1, const Matrice p2)
References Vecteur::pt, Matrice::m.
const Matrice operator*(const Matrice p1, const Matrice p2)
References Matrice::m.
Referenced by Matrice::identity, Matrice::setHomothetie.
double det33(double a, double b, double c, double d, double e, double f, double g, double h, double i)
Referenced by Matrice::determinant, Matrice::inverse, Matrice::setHomothetie.