BaseSimulator
Simulator * BaseSimulator::simulator
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::getSimulator, Catoms2D::Catoms2DSimulator::getSimulator, Catoms3D::Catoms3DSimulator::getSimulator, MultiCores::MultiCoresSimulator::getSimulator, RobotBlocks::RobotBlocksSimulator::getSimulator, BaseSimulator::Simulator::Simulator, SmartBlocks::SmartBlocksSimulator::getSimulator.
void BaseSimulator::deleteScheduler()
Referenced by BaseSimulator::Simulator::~Simulator.
Scheduler* BaseSimulator::getScheduler()
Referenced by ScenarioTappEvent::exportEventToScheduler, BlinkyBlocks::getScheduler, BaseSimulator::Clock::Clock, BaseSimulator::Clock::getTime, BaseSimulator::Clock::cleanReferencePoints, CodeEndSimulationEvent::consume, NetworkInterfaceStopTransmittingEvent::consume, GlutSlidingMainWindow::glDraw, GlutSlidingMainWindow::addTrace, GlutSlidingDebugWindow::glDraw, MeldInterpret::MeldInterpretVM::setLED, MeldProcess::VMCommand::VMCommand, P2PNetworkInterface::addToOutgoingBuffer, P2PNetworkInterface::send, GlutContext::deleteContext, GlutContext::reshapeFunc, GlutContext::mainLoop, GlutContext::addTrace.
static void BaseSimulator::swap(int *a, int *b)
void BaseSimulator::deleteWorld()
Referenced by BaseSimulator::Simulator::~Simulator.
World* BaseSimulator::getWorld()
Referenced by ScenarioTappEvent::exportEventToScheduler, BaseSimulator::BuildingBlock::addP2PNetworkInterfaceAndConnectTo, MeldProcess::MeldProcessVM::sendCommand, GlutContext::reshapeFunc.