Catoms2D
states
presence
typedef boost::function<void (GenericCodeBlock*,MessagePtr,P2PNetworkInterface*)> Catoms2D::eventFunc
const int Catoms2D::nbreNeighborsMax
const double Catoms2D::M_SQRT3_2
std::ostream & Catoms2D::operator<<(std::ostream &stream, Catoms2DBlock const &bb)
References BaseSimulator::BuildingBlock::blockId, Catoms2D::Catoms2DBlock::color.
Referenced by Catoms2D::Catoms2DBlock::getInterface.
ostream& Catoms2D::operator<<(ostream &f, const Capability &c)
References Catoms2D::Capability::name, Catoms2D::Capability::refPos, Catoms2D::Capability::validationMatrix.
bool Catoms2D::compare(Validation *a, Validation *b)
References Catoms2D::Validation::nbreConditions, Catoms2D::Validation::gain.
Referenced by Catoms2D::Catoms2DCapabilities::validateMulti.
ostream& Catoms2D::operator<<(ostream &f, const ValidationMatrix &sm)
References Catoms2D::ValidationMatrix::grid.
ostream& Catoms2D::operator<<(ostream &f, const PointRel3D &pt)
References Catoms2D::PointRel3D::x, Catoms2D::PointRel3D::y, Catoms2D::PointRel3D::z.
bool Catoms2D::operator!=(const PointRel3D p1, const PointRel3D p2)
References Catoms2D::PointRel3D::x, Catoms2D::PointRel3D::y, Catoms2D::PointRel3D::z.
bool Catoms2D::operator==(const PointRel3D p1, const PointRel3D p2)
References Catoms2D::PointRel3D::x, Catoms2D::PointRel3D::y, Catoms2D::PointRel3D::z.
Referenced by ObjLoader::Sommet::Sommet.
ostream& Catoms2D::operator<<(ostream &f, const PresenceMatrix &sm)
References Catoms2D::PresenceMatrix::grid.
void Catoms2D::createScheduler()
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator.
void Catoms2D::deleteScheduler()
Catoms2DScheduler* Catoms2D::getScheduler()
Referenced by Catoms2D::Catoms2DBlock::startMove, Catoms2D::MotionStartEvent::consume, Catoms2D::MotionStepEvent::consume, Catoms2D::MotionStopEvent::consume, Catoms2D::GenericCodeBlock::GenericCodeBlock, Catoms2D::Catoms2DWorld::addBlock, Catoms2D::Catoms2DWorld::disconnectBlock.
void Catoms2D::createSimulator(int argc, char *argv[], Catoms2DBlockCode *(*catoms2DBlockCodeBuildingFunction)(Catoms2DBlock *))
void Catoms2D::deleteSimulator()
Catoms2DSimulator* Catoms2D::getSimulator()
void Catoms2D::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References Catoms2D::Catoms2DWorld::createWorld.
Referenced by Catoms2D::Catoms2DSimulator::Catoms2DSimulator.
void Catoms2D::deleteWorld()
References Catoms2D::Catoms2DWorld::deleteWorld.
Catoms2DWorld* Catoms2D::getWorld()
References Catoms2D::Catoms2DWorld::getWorld.
Referenced by Catoms2D::Catoms2DBlock::setPosition, Catoms2D::Catoms2DBlock::setColor, Catoms2D::Catoms2DSimulator::Catoms2DSimulator.