MultiCores
typedef void*(MultiCoresScheduler::* MultiCores::startPaused) (void *))(void *)
typedef struct MultiCores::VMMessage_tt MultiCores::VMMessage_t_old
void MultiCores::createScheduler()
Referenced by MultiCores::MultiCoresSimulator::MultiCoresSimulator.
void MultiCores::deleteScheduler()
MultiCoresScheduler* MultiCores::getScheduler()
void MultiCores::createSimulator(int argc, char *argv[], MultiCoresBlockCode *(*multiCoreBlockCodeBuildingFunction)(MultiCoresBlock *))
void MultiCores::deleteSimulator()
MultiCoresSimulator* MultiCores::getSimulator()
void MultiCores::createWorld()
References MultiCores::MultiCoresWorld::createWorld.
Referenced by MultiCores::MultiCoresSimulator::MultiCoresSimulator.
void MultiCores::deleteWorld()
References MultiCores::MultiCoresWorld::deleteWorld.
MultiCoresWorld* MultiCores::getWorld()
References MultiCores::MultiCoresWorld::getWorld.
Referenced by MultiCores::MultiCoresScheduler::waitForVMMessage.