BlinkyBlocks
const GLfloat BlinkyBlocks::tabColors[12][4][12][4]
std::ostream & BlinkyBlocks::operator<<(std::ostream &stream, BlinkyBlocksBlock const &bb)
References BaseSimulator::BuildingBlock::blockId, BlinkyBlocks::BlinkyBlocksBlock::color.
Referenced by BlinkyBlocks::BlinkyBlocksBlock::getInterface, Camera::setDistance, Cell3DPosition::operator[], Matrice::identity, Vecteur::operator==.
void BlinkyBlocks::createScheduler()
References BaseSimulator::Simulator::getType, BaseSimulator::Simulator::MELDINTERPRET, MeldInterpret::MeldInterpretScheduler::createScheduler, BaseSimulator::Simulator::MELDPROCESS, MeldProcess::MeldProcessScheduler::createScheduler, BaseSimulator::Simulator::CPP, cppScheduler::CppScheduler::createScheduler.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator.
void BlinkyBlocks::deleteScheduler()
References BaseSimulator::Simulator::getType, BaseSimulator::Simulator::MELDINTERPRET, MeldInterpret::MeldInterpretScheduler::deleteScheduler, BaseSimulator::Simulator::MELDPROCESS, MeldProcess::MeldProcessScheduler::deleteScheduler, BaseSimulator::Simulator::CPP, cppScheduler::CppScheduler::deleteScheduler.
BaseSimulator::Scheduler* BlinkyBlocks::getScheduler()
References BaseSimulator::getScheduler.
Referenced by BlinkyBlocks::BlinkyBlocksBlock::tap, BlinkyBlocks::BlinkyBlocksBlock::accel, BlinkyBlocks::BlinkyBlocksBlock::shake, BlinkyBlocks::BlinkyBlocksBlock::addNeighbor, BlinkyBlocks::BlinkyBlocksBlock::removeNeighbor, BlinkyBlocks::BlinkyBlocksBlock::stop, BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, BlinkyBlocks::BlinkyBlocksWorld::addBlock, BlinkyBlocks::BlinkyBlocksWorld::deleteBlock, BlinkyBlocks::BlinkyBlocksWorld::menuChoice, BaseSimulator::BuildingBlock::scheduleLocalEvent, BaseSimulator::BuildingBlock::processLocalEvent, GlutSlidingDebugWindow::mouseFunc, GlutSlidingDebugWindow::keyFunc, MeldProcess::quit, MeldProcess::MeldProcessScheduler::pause, MeldProcess::MeldProcessVM::handleDeterministicMode, MeldProcess::MeldProcessVM::handleCommand, MultiCores::MultiCoresWorld::addBlock, P2PNetworkInterface::send, GlutContext::reshapeFunc, GlutContext::mainLoop.
void BlinkyBlocks::createSimulator(int argc, char *argv[], BlinkyBlocksBlockCode *(*blinkyBlocksBlockCodeBuildingFunction)(BlinkyBlocksBlock *))
void BlinkyBlocks::deleteSimulator()
BlinkyBlocksSimulator* BlinkyBlocks::getSimulator()
void BlinkyBlocks::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References BlinkyBlocks::BlinkyBlocksWorld::createWorld.
Referenced by BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator.
void BlinkyBlocks::deleteWorld()
References BlinkyBlocks::BlinkyBlocksWorld::deleteWorld.
BlinkyBlocksWorld* BlinkyBlocks::getWorld()
References BlinkyBlocks::BlinkyBlocksWorld::getWorld.
Referenced by BlinkyBlocks::BlinkyBlocksBlock::setPosition, BlinkyBlocks::BlinkyBlocksBlock::setColor, BlinkyBlocks::BlinkyBlocksBlock::stop, BlinkyBlocks::BlinkyBlocksSimulator::BlinkyBlocksSimulator, MeldInterpret::MeldInterpretScheduler::startPaused, MeldProcess::MeldProcessScheduler::startPaused, GlutContext::reshapeFunc.