Catoms3D
states
presence
const float Catoms3D::M_SQRT2_2
Referenced by Catoms3D::Catoms3DWorld::worldToGridPosition, Catoms3D::Catoms3DWorld::gridToWorldPosition.
const float Catoms3D::tabOrientationAngles[12][3][12][3]
Referenced by Catoms3D::Catoms3DBlock::setPositionAndOrientation.
const float Catoms3D::tabConnectorPositions[12][3][12][3]
Referenced by Catoms3D::Catoms3DBlock::getOrientationFromMatrix, Catoms3D::Catoms3DBlock::getNeighborPos, Catoms3D::Catoms3DBlock::getInterface.
const int Catoms3D::nbRotationSteps
Referenced by Catoms3D::Rotations::nextStep.
const double Catoms3D::M_SQRT3_2
std::ostream & Catoms3D::operator<<(std::ostream &stream, Catoms3DBlock const &bb)
References BaseSimulator::BuildingBlock::blockId, Catoms3D::Catoms3DBlock::color.
Referenced by Catoms3D::Catoms3DBlock::getInterface.
ostream& Catoms3D::operator<<(ostream &f, const Capability &c)
References Catoms3D::Capability::name, Catoms3D::Capability::refPos, Catoms3D::Capability::validationMatrix.
bool Catoms3D::compare(Validation *a, Validation *b)
References Catoms3D::Validation::nbreConditions, Catoms3D::Validation::gain.
Referenced by Catoms3D::Catoms3DCapabilities::validateMulti.
ostream& Catoms3D::operator<<(ostream &f, const ValidationMatrix &sm)
References Catoms3D::ValidationMatrix::grid.
ostream& Catoms3D::operator<<(ostream &f, const PointRel3D &pt)
References Catoms3D::PointRel3D::x, Catoms3D::PointRel3D::y, Catoms3D::PointRel3D::z.
bool Catoms3D::operator!=(const PointRel3D p1, const PointRel3D p2)
References Catoms3D::PointRel3D::x, Catoms3D::PointRel3D::y, Catoms3D::PointRel3D::z.
bool Catoms3D::operator==(const PointRel3D p1, const PointRel3D p2)
References Catoms3D::PointRel3D::x, Catoms3D::PointRel3D::y, Catoms3D::PointRel3D::z.
ostream& Catoms3D::operator<<(ostream &f, const PresenceMatrix &sm)
References Catoms3D::PresenceMatrix::grid.
void Catoms3D::createScheduler()
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator.
void Catoms3D::deleteScheduler()
Catoms3DScheduler* Catoms3D::getScheduler()
Referenced by Catoms3D::MotionStartEvent::consume, Catoms3D::MotionStepEvent::consume, Catoms3D::MotionStopEvent::consume, Catoms3D::Catoms3DWorld::addBlock, Catoms3D::Catoms3DWorld::disconnectBlock.
void Catoms3D::createSimulator(int argc, char *argv[], Catoms3DBlockCode *(*catoms3DBlockCodeBuildingFunction)(Catoms3DBlock *))
void Catoms3D::deleteSimulator()
Catoms3DSimulator* Catoms3D::getSimulator()
void Catoms3D::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References Catoms3D::Catoms3DWorld::createWorld.
Referenced by Catoms3D::Catoms3DSimulator::Catoms3DSimulator.
void Catoms3D::deleteWorld()
References Catoms3D::Catoms3DWorld::deleteWorld.
Catoms3DWorld* Catoms3D::getWorld()
References Catoms3D::Catoms3DWorld::getWorld.
Referenced by Catoms3D::Catoms3DBlock::setColor, Catoms3D::Catoms3DBlock::setVisible, Catoms3D::Catoms3DBlock::setPositionAndOrientation, Catoms3D::Catoms3DBlock::getNeighborPos, Catoms3D::Catoms3DBlock::getInterface, Catoms3D::MotionStepEvent::consume, Catoms3D::Rotations::getFinalPositionAndOrientation, Catoms3D::Catoms3DSimulator::Catoms3DSimulator.