MeldProcess
void MeldProcess::createDebugger()
Referenced by BaseSimulator::Simulator::Simulator.
void MeldProcess::deleteDebugger()
Referenced by BaseSimulator::Simulator::~Simulator.
MeldProcessDebugger* MeldProcess::getDebugger()
Referenced by sendCommand, pauseSimulation, unPauseSimulation, handleDebugCommand, MeldProcess::MeldProcessScheduler::startPaused.
int MeldProcess::sendCommand(int id, uint64_t *data, int size)
References getDebugger, MeldProcess::MeldProcessDebugger::sendCmd.
Referenced by MeldProcess::MeldProcessDebugger::MeldProcessDebugger, MeldProcess::MeldProcessVM::isInDebuggingMode.
void MeldProcess::pauseSimulation(int t)
References getDebugger, MeldProcess::MeldProcessDebugger::pauseSim.
Referenced by MeldProcess::MeldProcessDebugger::MeldProcessDebugger.
void MeldProcess::unPauseSimulation()
References getDebugger, MeldProcess::MeldProcessDebugger::unPauseSim.
Referenced by MeldProcess::MeldProcessDebugger::MeldProcessDebugger.
void MeldProcess::handleDebugCommand(DebbuggerVMCommand *c)
References getDebugger, MeldProcess::MeldProcessDebugger::handleDebugCommand.
Referenced by MeldProcess::MeldProcessDebugger::deleteDebugger, MeldProcess::MeldProcessVM::handleCommand.
void MeldProcess::quit()
References BlinkyBlocks::getScheduler.
Referenced by MeldProcess::MeldProcessDebugger::MeldProcessDebugger.
void MeldProcess::createScheduler()
void MeldProcess::deleteScheduler()
MeldProcessScheduler* MeldProcess::getScheduler()
Referenced by MeldProcess::MeldProcessDebugger::pauseSim, MeldProcess::MeldProcessDebugger::unPauseSim, MeldProcess::VMDebugPauseSimEvent::consume.
void MeldProcess::createVMServer(int p)
Referenced by BaseSimulator::Simulator::Simulator.
void MeldProcess::deleteVMServer()
Referenced by BaseSimulator::Simulator::~Simulator.
void MeldProcess::setVMConfiguration(string v, string p, bool d)
Referenced by BaseSimulator::Simulator::Simulator.
void MeldProcess::checkForReceivedVMCommands()
Referenced by MeldProcess::MeldProcessScheduler::SemWaitOrReadDebugMessage, MeldProcess::MeldProcessScheduler::startPaused, MeldProcess::MeldProcessVM::MeldProcessVM.
void MeldProcess::waitForOneVMCommand()
Referenced by MeldProcess::MeldProcessScheduler::startPaused.