SmartBlocks
NeighborDirection
states
presence
const GLfloat SmartBlocks::tabColors[12][4][12][4]
ostream& SmartBlocks::operator<<(ostream &f, const Capability &c)
References SmartBlocks::Capability::name, SmartBlocks::Capability::validationMatrix, SmartBlocks::Capability::linkNextPos, SmartBlocks::Capability::linkPrevPos, SmartBlocks::Capability::singleMotionDir.
bool SmartBlocks::compare(Validation *a, Validation *b)
References SmartBlocks::Validation::gain.
Referenced by SmartBlocks::SmartBlocksCapabilities::validateDirection.
int SmartBlocks::dir(SmartBlocks::PointCel *v)
References SmartBlocks::PointCel::x, SmartBlocks::PointCel::y.
Referenced by LightSource::calcMatrices, Catoms2D::Catoms2DBlock::getInterface, SmartBlocks::SmartBlocksCapabilities::validateDirection.
ostream& SmartBlocks::operator<<(ostream &f, const ValidationMatrix &sm)
References SmartBlocks::ValidationMatrix::grid.
ostream& SmartBlocks::operator<<(ostream &f, const PointCel &pt)
References SmartBlocks::PointCel::x, SmartBlocks::PointCel::y.
bool SmartBlocks::operator!=(const PointCel p1, const PointCel p2)
References SmartBlocks::PointCel::x, SmartBlocks::PointCel::y.
bool SmartBlocks::operator==(const PointCel p1, const PointCel p2)
References SmartBlocks::PointCel::x, SmartBlocks::PointCel::y.
ostream& SmartBlocks::operator<<(ostream &f, const PresenceMatrix &sm)
References SmartBlocks::PresenceMatrix::grid.
void SmartBlocks::createScheduler()
References SmartBlocks::SmartBlocksScheduler::createScheduler.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void SmartBlocks::deleteScheduler()
References SmartBlocks::SmartBlocksScheduler::deleteScheduler.
SmartBlocksScheduler* SmartBlocks::getScheduler()
References SmartBlocks::SmartBlocksScheduler::getScheduler.
Referenced by SmartBlocks::MotionStartEvent::consume, SmartBlocks::MotionStepEvent::consume, SmartBlocks::MotionStopEvent::consume, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator, SmartBlocks::SmartBlocksWorld::addBlock, SmartBlocks::SmartBlocksWorld::printStats.
void SmartBlocks::createSimulator(int argc, char *argv[], SmartBlocksBlockCode *(*smartBlocksBlockCodeBuildingFunction)(SmartBlocksBlock *))
void SmartBlocks::deleteSimulator()
SmartBlocksSimulator* SmartBlocks::getSimulator()
void SmartBlocks::createWorld(int gw, int gh, int argc, char *argv[])
References SmartBlocks::SmartBlocksWorld::createWorld.
Referenced by SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.
void SmartBlocks::deleteWorld()
References SmartBlocks::SmartBlocksWorld::deleteWorld.
SmartBlocksWorld* SmartBlocks::getWorld()
References SmartBlocks::SmartBlocksWorld::getWorld.
Referenced by SmartBlocks::SmartBlocksBlock::setPosition, SmartBlocks::SmartBlocksBlock::setColor, SmartBlocks::SmartBlocksGlBlock::glDraw, SmartBlocks::SmartBlocksSimulator::SmartBlocksSimulator.