RobotBlocks
states
presence
typedef boost::function<void (GenericCodeBlock*,MessagePtr,P2PNetworkInterface*)> RobotBlocks::eventFunc
std::ostream & RobotBlocks::operator<<(std::ostream &stream, RobotBlocksBlock const &bb)
References BaseSimulator::BuildingBlock::blockId, RobotBlocks::RobotBlocksBlock::color.
Referenced by RobotBlocks::RobotBlocksBlock::getInterface.
ostream& RobotBlocks::operator<<(ostream &f, const Capability &c)
References RobotBlocks::Capability::name, RobotBlocks::Capability::refPos, RobotBlocks::Capability::validationMatrix.
bool RobotBlocks::compare(Validation *a, Validation *b)
References RobotBlocks::Validation::nbreConditions, RobotBlocks::Validation::gain.
Referenced by RobotBlocks::RobotBlocksCapabilities::validateMulti.
ostream& RobotBlocks::operator<<(ostream &f, const ValidationMatrix &sm)
References RobotBlocks::ValidationMatrix::grid.
ostream& RobotBlocks::operator<<(ostream &f, const PointRel3D &pt)
References RobotBlocks::PointRel3D::x, RobotBlocks::PointRel3D::y, RobotBlocks::PointRel3D::z.
bool RobotBlocks::operator!=(const PointRel3D p1, const PointRel3D p2)
References RobotBlocks::PointRel3D::x, RobotBlocks::PointRel3D::y, RobotBlocks::PointRel3D::z.
bool RobotBlocks::operator==(const PointRel3D p1, const PointRel3D p2)
References RobotBlocks::PointRel3D::x, RobotBlocks::PointRel3D::y, RobotBlocks::PointRel3D::z.
ostream& RobotBlocks::operator<<(ostream &f, const PresenceMatrix &sm)
References RobotBlocks::PresenceMatrix::grid.
void RobotBlocks::createScheduler()
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.
void RobotBlocks::deleteScheduler()
RobotBlocksScheduler* RobotBlocks::getScheduler()
Referenced by RobotBlocks::MotionStartEvent::consume, RobotBlocks::MotionStepEvent::consume, RobotBlocks::MotionStopEvent::consume, RobotBlocks::GenericCodeBlock::GenericCodeBlock, RobotBlocks::RobotBlocksWorld::addBlock, RobotBlocks::RobotBlocksWorld::disconnectBlock.
void RobotBlocks::createSimulator(int argc, char *argv[], RobotBlocksBlockCode *(*robotBlocksBlockCodeBuildingFunction)(RobotBlocksBlock *))
void RobotBlocks::deleteSimulator()
RobotBlocksSimulator* RobotBlocks::getSimulator()
void RobotBlocks::createWorld(int slx, int sly, int slz, int argc, char *argv[])
References RobotBlocks::RobotBlocksWorld::createWorld.
Referenced by RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.
void RobotBlocks::deleteWorld()
References RobotBlocks::RobotBlocksWorld::deleteWorld.
RobotBlocksWorld* RobotBlocks::getWorld()
References RobotBlocks::RobotBlocksWorld::getWorld.
Referenced by RobotBlocks::RobotBlocksBlock::setPosition, RobotBlocks::RobotBlocksBlock::setColor, RobotBlocks::RobotBlocksBlock::setPrevNext, RobotBlocks::RobotBlocksSimulator::RobotBlocksSimulator.