shaders.cpp
GLuint depth_tex
Referenced by initShaders, shadowedRenderingStep3.
GLuint id_fb
Referenced by initShaders, shadowedRenderingStep1.
GLuint color_rb
Referenced by initShaders.
bool useShaders
Referenced by shadowedRenderingStep3, shadowedRenderingStep4.
GLhandleARB shadersProgram
Referenced by initShaders, shadowedRenderingStep3.
GLint locTex
Referenced by initShaders, shadowedRenderingStep3.
GLint locShadowMap
Referenced by initShaders, shadowedRenderingStep3.
GLint locTextureEnable
Referenced by enableTexture, initShaders.
void enableTexture(bool enable)
References locTextureEnable.
Referenced by BlinkyBlocks::BlinkyBlocksWorld::glDraw, Catoms2D::Catoms2DWorld::glDraw, ObjLoader::Mtl::glBind, RobotBlocks::RobotBlocksWorld::glDraw.
GLcharARB* lectureCodeShader(const char *titre)
Referenced by loadShader.
GLhandleARB loadShader(const char *titreVP, const char *titreFP)
References lectureCodeShader, ERRPUT, OUTPUT, shaderCompilationStatus.
Referenced by initShaders.
void initShaders()
References OUTPUT, shadersProgram, loadShader, locTex, ERRPUT, locShadowMap, locTextureEnable, id_fb, depth_tex, color_rb.
Referenced by GlutContext::init.
void shadowedRenderingStep1(Camera *camera)
References id_fb, Camera::ls, LightSource::matP, LightSource::matMV.
Referenced by GlutContext::reshapeFunc.
void shadowedRenderingStep2(int w, int h)
Referenced by GlutContext::reshapeFunc.
void shadowedRenderingStep3(Camera *camera)
References Camera::glProjection, Camera::glLookAt, Matrice::inverse, Camera::ls, LightSource::matP, LightSource::matMV, Matrice::m, LightSource::pos, LightSource::dir, LightSource::falloffAngle, WHITE, Color::rgba, useShaders, shadersProgram, locTex, locShadowMap, depth_tex.
Referenced by GlutContext::reshapeFunc.
void shadowedRenderingStep4()
References useShaders.
Referenced by GlutContext::reshapeFunc.
GLint shaderCompilationStatus(GLhandleARB shader)
References OUTPUT.
Referenced by loadShader.