vecteur.h
M_PI
const Vecteur operator*(double, const Vecteur)
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.
const double operator*(const Vecteur, const Vecteur)
v1 : first vector v2 : second vector
References Vecteur::pt.
const Vecteur operator+(const Vecteur, const Vecteur)
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.
const Vecteur operator-(const Vecteur, const Vecteur)
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.
const Vecteur operator-(const Vecteur)
References Vecteur::pt.
const Vecteur operator^(const Vecteur, const Vecteur)
v1 : first vector v2 : second vector
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.