vecteur.cpp
istream& operator>>(istream &f, Vecteur &p)
References Vecteur::pt.
ostream& operator<<(ostream &f, const Vecteur &p)
References Vecteur::pt.
const Vecteur operator*(double v, const Vecteur p)
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.
const double operator*(const Vecteur p1, const Vecteur p2)
v1 : first vector v2 : second vector
References Vecteur::pt.
const Vecteur operator+(const Vecteur p1, const Vecteur p2)
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.
const Vecteur operator-(const Vecteur p1, const Vecteur p2)
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.
const Vecteur operator-(const Vecteur p1)
References Vecteur::pt.
const Vecteur operator^(const Vecteur p1, const Vecteur p2)
v1 : first vector v2 : second vector
References Vecteur::pt.
Referenced by Vecteur::operator==, Vecteur::setPoint.